// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: context/v1/context.proto

package contextpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConversationContext_GetRecentTurns_FullMethodName = "/clydecontext.v1.ConversationContext/GetRecentTurns"
)

// ConversationContextClient is the client API for ConversationContext service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConversationContextClient interface {
	GetRecentTurns(ctx context.Context, in *GetRecentTurnsRequest, opts ...grpc.CallOption) (*GetRecentTurnsReply, error)
}

type conversationContextClient struct {
	cc grpc.ClientConnInterface
}

func NewConversationContextClient(cc grpc.ClientConnInterface) ConversationContextClient {
	return &conversationContextClient{cc}
}

func (c *conversationContextClient) GetRecentTurns(ctx context.Context, in *GetRecentTurnsRequest, opts ...grpc.CallOption) (*GetRecentTurnsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRecentTurnsReply)
	err := c.cc.Invoke(ctx, ConversationContext_GetRecentTurns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConversationContextServer is the server API for ConversationContext service.
// All implementations should embed UnimplementedConversationContextServer
// for forward compatibility.
type ConversationContextServer interface {
	GetRecentTurns(context.Context, *GetRecentTurnsRequest) (*GetRecentTurnsReply, error)
}

// UnimplementedConversationContextServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConversationContextServer struct{}

func (UnimplementedConversationContextServer) GetRecentTurns(context.Context, *GetRecentTurnsRequest) (*GetRecentTurnsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecentTurns not implemented")
}
func (UnimplementedConversationContextServer) testEmbeddedByValue() {}

// UnsafeConversationContextServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConversationContextServer will
// result in compilation errors.
type UnsafeConversationContextServer interface {
	mustEmbedUnimplementedConversationContextServer()
}

func RegisterConversationContextServer(s grpc.ServiceRegistrar, srv ConversationContextServer) {
	// If the following call panics, it indicates UnimplementedConversationContextServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConversationContext_ServiceDesc, srv)
}

func _ConversationContext_GetRecentTurns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecentTurnsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationContextServer).GetRecentTurns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversationContext_GetRecentTurns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationContextServer).GetRecentTurns(ctx, req.(*GetRecentTurnsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConversationContext_ServiceDesc is the grpc.ServiceDesc for ConversationContext service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConversationContext_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clydecontext.v1.ConversationContext",
	HandlerType: (*ConversationContextServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRecentTurns",
			Handler:    _ConversationContext_GetRecentTurns_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "context/v1/context.proto",
}
