// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: context/v1/context.proto

package contextpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRecentTurnsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceRef    string                 `protobuf:"bytes,1,opt,name=workspace_ref,json=workspaceRef,proto3" json:"workspace_ref,omitempty"`               // filesystem cwd of the session
	SessionRef      string                 `protobuf:"bytes,2,opt,name=session_ref,json=sessionRef,proto3" json:"session_ref,omitempty"`                     // optional; empty means newest for workspace
	TurnBudget      int32                  `protobuf:"varint,3,opt,name=turn_budget,json=turnBudget,proto3" json:"turn_budget,omitempty"`                    // default 4
	MaxCharsPerTurn int32                  `protobuf:"varint,4,opt,name=max_chars_per_turn,json=maxCharsPerTurn,proto3" json:"max_chars_per_turn,omitempty"` // default 280
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetRecentTurnsRequest) Reset() {
	*x = GetRecentTurnsRequest{}
	mi := &file_context_v1_context_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecentTurnsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecentTurnsRequest) ProtoMessage() {}

func (x *GetRecentTurnsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_context_v1_context_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecentTurnsRequest.ProtoReflect.Descriptor instead.
func (*GetRecentTurnsRequest) Descriptor() ([]byte, []int) {
	return file_context_v1_context_proto_rawDescGZIP(), []int{0}
}

func (x *GetRecentTurnsRequest) GetWorkspaceRef() string {
	if x != nil {
		return x.WorkspaceRef
	}
	return ""
}

func (x *GetRecentTurnsRequest) GetSessionRef() string {
	if x != nil {
		return x.SessionRef
	}
	return ""
}

func (x *GetRecentTurnsRequest) GetTurnBudget() int32 {
	if x != nil {
		return x.TurnBudget
	}
	return 0
}

func (x *GetRecentTurnsRequest) GetMaxCharsPerTurn() int32 {
	if x != nil {
		return x.MaxCharsPerTurn
	}
	return 0
}

type GetRecentTurnsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Turns         []*Turn                `protobuf:"bytes,1,rep,name=turns,proto3" json:"turns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecentTurnsReply) Reset() {
	*x = GetRecentTurnsReply{}
	mi := &file_context_v1_context_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecentTurnsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecentTurnsReply) ProtoMessage() {}

func (x *GetRecentTurnsReply) ProtoReflect() protoreflect.Message {
	mi := &file_context_v1_context_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecentTurnsReply.ProtoReflect.Descriptor instead.
func (*GetRecentTurnsReply) Descriptor() ([]byte, []int) {
	return file_context_v1_context_proto_rawDescGZIP(), []int{1}
}

func (x *GetRecentTurnsReply) GetTurns() []*Turn {
	if x != nil {
		return x.Turns
	}
	return nil
}

type Turn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Ts            string                 `protobuf:"bytes,3,opt,name=ts,proto3" json:"ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Turn) Reset() {
	*x = Turn{}
	mi := &file_context_v1_context_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Turn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Turn) ProtoMessage() {}

func (x *Turn) ProtoReflect() protoreflect.Message {
	mi := &file_context_v1_context_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Turn.ProtoReflect.Descriptor instead.
func (*Turn) Descriptor() ([]byte, []int) {
	return file_context_v1_context_proto_rawDescGZIP(), []int{2}
}

func (x *Turn) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Turn) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Turn) GetTs() string {
	if x != nil {
		return x.Ts
	}
	return ""
}

var File_context_v1_context_proto protoreflect.FileDescriptor

const file_context_v1_context_proto_rawDesc = "" +
	"\n" +
	"\x18context/v1/context.proto\x12\x0fclydecontext.v1\"\xab\x01\n" +
	"\x15GetRecentTurnsRequest\x12#\n" +
	"\rworkspace_ref\x18\x01 \x01(\tR\fworkspaceRef\x12\x1f\n" +
	"\vsession_ref\x18\x02 \x01(\tR\n" +
	"sessionRef\x12\x1f\n" +
	"\vturn_budget\x18\x03 \x01(\x05R\n" +
	"turnBudget\x12+\n" +
	"\x12max_chars_per_turn\x18\x04 \x01(\x05R\x0fmaxCharsPerTurn\"B\n" +
	"\x13GetRecentTurnsReply\x12+\n" +
	"\x05turns\x18\x01 \x03(\v2\x15.clydecontext.v1.TurnR\x05turns\">\n" +
	"\x04Turn\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x0e\n" +
	"\x02ts\x18\x03 \x01(\tR\x02ts2u\n" +
	"\x13ConversationContext\x12^\n" +
	"\x0eGetRecentTurns\x12&.clydecontext.v1.GetRecentTurnsRequest\x1a$.clydecontext.v1.GetRecentTurnsReplyB!Z\x1fgoodkind.io/clyde/api/contextpbb\x06proto3"

var (
	file_context_v1_context_proto_rawDescOnce sync.Once
	file_context_v1_context_proto_rawDescData []byte
)

func file_context_v1_context_proto_rawDescGZIP() []byte {
	file_context_v1_context_proto_rawDescOnce.Do(func() {
		file_context_v1_context_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_context_v1_context_proto_rawDesc), len(file_context_v1_context_proto_rawDesc)))
	})
	return file_context_v1_context_proto_rawDescData
}

var file_context_v1_context_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_context_v1_context_proto_goTypes = []any{
	(*GetRecentTurnsRequest)(nil), // 0: clydecontext.v1.GetRecentTurnsRequest
	(*GetRecentTurnsReply)(nil),   // 1: clydecontext.v1.GetRecentTurnsReply
	(*Turn)(nil),                  // 2: clydecontext.v1.Turn
}
var file_context_v1_context_proto_depIdxs = []int32{
	2, // 0: clydecontext.v1.GetRecentTurnsReply.turns:type_name -> clydecontext.v1.Turn
	0, // 1: clydecontext.v1.ConversationContext.GetRecentTurns:input_type -> clydecontext.v1.GetRecentTurnsRequest
	1, // 2: clydecontext.v1.ConversationContext.GetRecentTurns:output_type -> clydecontext.v1.GetRecentTurnsReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_context_v1_context_proto_init() }
func file_context_v1_context_proto_init() {
	if File_context_v1_context_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_context_v1_context_proto_rawDesc), len(file_context_v1_context_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_context_v1_context_proto_goTypes,
		DependencyIndexes: file_context_v1_context_proto_depIdxs,
		MessageInfos:      file_context_v1_context_proto_msgTypes,
	}.Build()
	File_context_v1_context_proto = out.File
	file_context_v1_context_proto_goTypes = nil
	file_context_v1_context_proto_depIdxs = nil
}
