package compact

import (
	"encoding/json"
	"fmt"
	"sort"
	"strconv"
	"strings"
	"time"
)

// ToolDetail enumerates the three rendering levels for tool pairs.
// Highest fidelity first; the target loop demotes oldest pairs one
// level at a time until the budget fits.
type ToolDetail int

const (
	// ToolDetailFull renders the call line plus a fenced code block
	// with the full result body (head/tail truncated at TruncTokens).
	ToolDetailFull ToolDetail = iota
	// ToolDetailLineOnly renders just the "Tool(args) -> N lines (T tok)"
	// line; the body block is omitted.
	ToolDetailLineOnly
	// ToolDetailDrop omits the pair entirely from the synthetic output.
	ToolDetailDrop
)

// SynthOptions controls how the post-boundary slice is rendered into
// the synthetic content array. Defaults are highest fidelity: keep
// images as image blocks, render every tool pair full, include every
// chat turn verbatim, and keep thinking blocks out (they never carry
// across turn boundaries in the live API anyway).
type SynthOptions struct {
	// DropThinking, if true, drops thinking and redacted_thinking
	// content. Default false; the orchestrator turns this on
	// unconditionally when running a target loop because thinking
	// content does not survive turn boundaries in the live API.
	DropThinking bool

	// ImagesAsPlaceholder, if true, replaces image blocks with a
	// `[image: media_type, N bytes]` text marker instead of carrying
	// the base64 data forward.
	ImagesAsPlaceholder bool

	// ToolDefault is the rendering level applied to every tool pair
	// that does not appear in ToolDetailOverride.
	ToolDefault ToolDetail

	// ToolDetailOverride lets the orchestrator demote specific (oldest)
	// tool_use ids without changing the default. The map is keyed by
	// tool_use id.
	ToolDetailOverride map[string]ToolDetail

	// DroppedChatEntries lists post-boundary entry indexes (into
	// Slice.PostBoundary) that should be omitted from the chat
	// transcript. The orchestrator populates this oldest-first while
	// always preserving the most recent assistant turn plus its
	// preceding user turn.
	DroppedChatEntries map[int]bool

	// DroppedSummaryChunks lists per-entry virtual chunks that should
	// be omitted from a prior synthetic compact summary. Keyed first by
	// post-boundary entry index, then by chunk key from
	// syntheticSummary.DropOrder.
	DroppedSummaryChunks map[int]map[string]bool

	// TruncTokens caps tool result body length when ToolDefault is
	// Full. Approximated as 4 chars per token. Default 4000.
	TruncTokens int

	// Summary, when non-empty, is inserted into the synthetic header as
	// a distilled recap of the dropped portion. Generated by the caller
	// (typically via a provider summarization call). Empty means the
	// header omits the "Summary of dropped content" section.
	Summary string
}

// DroppedStats counts what the current SynthOptions will drop or
// demote from the slice. Used to populate the static "What was
// dropped" section of the synthetic header so the continuing agent
// knows exactly what is missing.
type DroppedStats struct {
	ThinkingBlocks int
	Images         int
	ToolsLineOnly  int
	ToolsDropped   int
	ChatTurns      int
}

// ComputeDroppedStats walks the slice under the current opts and
// returns the counts of each dropped or demoted category.
func ComputeDroppedStats(slice *Slice, opts SynthOptions) DroppedStats {
	var s DroppedStats
	for _, e := range slice.PostBoundary {
		for _, b := range e.Content {
			switch contentBlockType(b.Type) {
			case contentBlockTypeText, contentBlockTypeToolResult:
			case contentBlockTypeThinking, contentBlockTypeRedactedThinking:
				if opts.DropThinking {
					s.ThinkingBlocks++
				}
			case contentBlockTypeImage:
				if opts.ImagesAsPlaceholder {
					s.Images++
				}
			case contentBlockTypeToolUse:
				detail := opts.ToolDefault
				if override, ok := opts.ToolDetailOverride[b.ToolUseID]; ok {
					detail = override
				}
				switch detail {
				case ToolDetailFull:
				case ToolDetailLineOnly:
					s.ToolsLineOnly++
				case ToolDetailDrop:
					s.ToolsDropped++
				}
			}
		}
	}
	for ei := range opts.DroppedChatEntries {
		if ei < 0 || ei >= len(slice.PostBoundary) {
			continue
		}
		t := slice.PostBoundary[ei].Type
		if t == "user" || t == "assistant" {
			s.ChatTurns++
		}
	}
	return s
}

// OutputBlock is one element of the synthetic content array. It is a
// closed sum: either a text block (Text set, Image nil) or an image
// block (Image set, Text empty). Marshaling routes through
// MarshalJSON so the on-disk shape matches the expected content-array
// schema exactly.
type OutputBlock struct {
	Text  string
	Image *OutputImage
}

// OutputImage is the typed payload of an image block: base64-encoded
// data plus media type.
type OutputImage struct {
	MediaType string
	DataB64   string
}

type outputImagePayload struct {
	Type   string            `json:"type"`
	Source outputImageSource `json:"source"`
}

type outputImageSource struct {
	Type      string `json:"type"`
	MediaType string `json:"media_type"`
	Data      string `json:"data"`
}

type outputTextPayload struct {
	Type string `json:"type"`
	Text string `json:"text"`
}

// MarshalJSON serializes an OutputBlock as either
// {"type":"text","text":"..."} or {"type":"image","source":{...}}.
func (b OutputBlock) MarshalJSON() ([]byte, error) {
	if b.Image != nil {
		payload := outputImagePayload{
			Type: string(contentBlockTypeImage),
			Source: outputImageSource{
				Type:      "base64",
				MediaType: b.Image.MediaType,
				Data:      b.Image.DataB64,
			},
		}
		encoded, err := json.Marshal(payload)
		if err != nil {
			return nil, fmt.Errorf("marshal image output block: %w", err)
		}
		return encoded, nil
	}
	payload := outputTextPayload{Type: string(contentBlockTypeText), Text: b.Text}
	encoded, err := json.Marshal(payload)
	if err != nil {
		return nil, fmt.Errorf("marshal text output block: %w", err)
	}
	return encoded, nil
}

// Synthesize builds the content array for the post-boundary user
// message. Output blocks are ordered: header, chat transcript, tool
// activity section, footer. Image blocks (when not placeholders) are
// inserted in the chat stream where they originally appeared so the
// model still sees them inline.
func Synthesize(slice *Slice, opts SynthOptions) []OutputBlock {
	if opts.TruncTokens <= 0 {
		opts.TruncTokens = 4000
	}
	out := []OutputBlock{}
	out = append(out, textBlock(renderHeader(slice, opts)))
	out = append(out, renderChat(slice, opts)...)
	if toolBlocks := renderToolActivity(slice, opts); len(toolBlocks) > 0 {
		out = append(out, toolBlocks...)
	}
	out = append(out, textBlock("## Continue from here.\n"))
	return out
}

// renderHeader builds the continuity notice, the static dropped-stats
// section, and (if present) the LLM summary block that together
// precede the surviving transcript. The wording is deliberate: the
// continuing model must not disclaim identity with earlier turns in
// the session.
func renderHeader(slice *Slice, opts SynthOptions) string {
	var sb strings.Builder
	sb.WriteString("## Context continuity notice\n\n")
	sb.WriteString("Your prior context has been truncated and distilled to fit the model window. You are the same agent, in the same session. You are not a successor. You are not a handoff recipient. First person references to earlier work remain yours. Decisions you made are yours. Files you touched are yours. Commitments you made to the user are yours. Do not disclaim memory. Do not attribute past actions to \"another agent.\"\n\n")
	sb.WriteString("If the user asks about something that appears to be missing below, use the `clyde` MCP tools (`clyde_search_conversation`, `clyde_get_conversation`) to recall the pre compaction transcript before answering. Do not guess. Do not say \"I don't remember\" without searching first.\n\n")

	stats := ComputeDroppedStats(slice, opts)
	if droppedStatsTotal(stats) > 0 {
		sb.WriteString("### What was dropped\n\n")
		writeDroppedStats(&sb, stats)
		sb.WriteString("\n")
	}

	if strings.TrimSpace(opts.Summary) != "" {
		sb.WriteString("### Summary of dropped content\n\n")
		sb.WriteString(strings.TrimSpace(opts.Summary))
		sb.WriteString("\n\n")
	}

	sb.WriteString("## Surviving transcript\n\n")
	return sb.String()
}

func droppedStatsTotal(stats DroppedStats) int {
	return stats.ThinkingBlocks + stats.Images + stats.ToolsLineOnly + stats.ToolsDropped + stats.ChatTurns
}

func writeDroppedStats(sb *strings.Builder, stats DroppedStats) {
	if stats.ThinkingBlocks > 0 {
		fmt.Fprintf(sb, "- %d thinking block(s) removed (never carry across turn boundaries)\n", stats.ThinkingBlocks)
	}
	if stats.Images > 0 {
		fmt.Fprintf(sb, "- %d image(s) replaced with text placeholders\n", stats.Images)
	}
	if stats.ToolsLineOnly > 0 {
		fmt.Fprintf(sb, "- %d tool call(s) demoted to one-line summaries (full output discarded)\n", stats.ToolsLineOnly)
	}
	if stats.ToolsDropped > 0 {
		fmt.Fprintf(sb, "- %d tool call(s) dropped entirely\n", stats.ToolsDropped)
	}
	if stats.ChatTurns > 0 {
		fmt.Fprintf(sb, "- %d chat turn(s) dropped (oldest first; last assistant + preceding user preserved)\n", stats.ChatTurns)
	}
}

// renderChat walks PostBoundary in order and emits a text block per
// chat turn, plus image blocks (or image placeholders) inline. Tool
// activity is excluded; that lives in its own section below.
func renderChat(slice *Slice, opts SynthOptions) []OutputBlock {
	var out []OutputBlock
	for ei, e := range slice.PostBoundary {
		if opts.DroppedChatEntries != nil && opts.DroppedChatEntries[ei] {
			continue
		}
		switch entryType(e.Type) {
		case entryTypeSystem:
		case entryTypeUser:
			if isToolResultOnly(e) {
				// Tool results render in the tool activity section.
				continue
			}
			text := chatTextFrom(e, opts)
			if text == "" && !hasRenderableImage(e, opts) {
				continue
			}
			label := turnLabel("User", e.Timestamp)
			if text != "" {
				out = append(out, textBlock(label+text+"\n\n"))
			} else {
				out = append(out, textBlock(label+"\n\n"))
			}
			out = append(out, renderInlineImages(e, opts)...)
		case entryTypeAssistant:
			text := chatTextFrom(e, opts)
			if text == "" && !hasRenderableImage(e, opts) {
				continue
			}
			label := turnLabel("Assistant", e.Timestamp)
			if text != "" {
				out = append(out, textBlock(label+text+"\n\n"))
			}
			out = append(out, renderInlineImages(e, opts)...)
		}
	}
	return out
}

// toolPairRender is a single tool_use plus rendering metadata used while
// emitting the trailing tool activity summary.
type toolPairRender struct {
	ei     int
	bi     int
	useID  string
	entry  Entry
	block  ContentBlock
	detail ToolDetail
}

// renderToolActivity emits one trailing section summarising tool
// invocations in the order they appeared.
func renderToolActivity(slice *Slice, opts SynthOptions) []OutputBlock {
	pairs := collectToolPairs(slice, opts)
	if len(pairs) == 0 {
		return nil
	}
	var sb strings.Builder
	sb.WriteString("## Tool activity\n\n")
	for _, p := range pairs {
		writeToolPair(&sb, slice, p, opts)
	}
	return []OutputBlock{textBlock(sb.String())}
}

// collectToolPairs walks the post-boundary slice and gathers every
// non-dropped tool_use into the order it appeared.
func collectToolPairs(slice *Slice, opts SynthOptions) []toolPairRender {
	var pairs []toolPairRender
	for ei, e := range slice.PostBoundary {
		if e.Type != "assistant" {
			continue
		}
		for bi, b := range e.Content {
			if b.Type != "tool_use" {
				continue
			}
			detail := opts.ToolDefault
			if override, ok := opts.ToolDetailOverride[b.ToolUseID]; ok {
				detail = override
			}
			if detail == ToolDetailDrop {
				continue
			}
			pairs = append(pairs, toolPairRender{
				ei: ei, bi: bi, useID: b.ToolUseID, entry: e, block: b, detail: detail,
			})
		}
	}
	return pairs
}

// writeToolPair appends one tool pair's markdown summary line and, when
// detail is full, its truncated result body.
func writeToolPair(sb *strings.Builder, slice *Slice, p toolPairRender, opts SynthOptions) {
	argSummary := summarizeToolArgs(p.block)
	resultBlock := lookupToolResultBlock(slice, p.useID)
	resultText, lines, tokens := flattenToolResult(resultBlock)
	fmt.Fprintf(sb, "- %s(%s) -> %d lines (~%d tok)", p.block.ToolName, argSummary, lines, tokens)
	if resultBlock != nil && resultBlock.ToolIsError {
		sb.WriteString(" [error]")
	}
	sb.WriteString("\n")
	if p.detail == ToolDetailFull && resultText != "" {
		truncated := truncHeadTail(resultText, opts.TruncTokens*4)
		sb.WriteString("```text\n")
		sb.WriteString(truncated)
		if !strings.HasSuffix(truncated, "\n") {
			sb.WriteString("\n")
		}
		sb.WriteString("```\n")
	}
	sb.WriteString("\n")
}

// lookupToolResultBlock returns a copy of the tool_result block paired
// with the given tool_use id, or nil when the slice has no paired result.
func lookupToolResultBlock(slice *Slice, useID string) *ContentBlock {
	pair, ok := slice.PairIndex[useID]
	if !ok || pair.ResultEntryIdx < 0 {
		return nil
	}
	rEntry := slice.PostBoundary[pair.ResultEntryIdx]
	if pair.ResultBlockIdx >= len(rEntry.Content) {
		return nil
	}
	rb := rEntry.Content[pair.ResultBlockIdx]
	return &rb
}

// chatTextFrom concatenates text blocks from one entry, optionally
// dropping thinking content (which we never carry across boundaries).
func chatTextFrom(e Entry, opts SynthOptions) string {
	var sb strings.Builder
	if e.TextOnly != "" {
		sb.WriteString(e.TextOnly)
	}
	for _, b := range e.Content {
		switch contentBlockType(b.Type) {
		case contentBlockTypeText:
			if b.Text != "" {
				if sb.Len() > 0 {
					sb.WriteString("\n")
				}
				sb.WriteString(b.Text)
			}
		case contentBlockTypeThinking, contentBlockTypeRedactedThinking:
			if !opts.DropThinking && b.Thinking != "" {
				if sb.Len() > 0 {
					sb.WriteString("\n")
				}
				sb.WriteString("[thinking] " + b.Thinking)
			}
		case contentBlockTypeImage, contentBlockTypeToolUse, contentBlockTypeToolResult:
		}
	}
	return strings.TrimSpace(sb.String())
}

// renderInlineImages emits image blocks (or placeholders) for one
// entry. Placed AFTER the entry's text label so the visual flow is
// "User: ... <image> Assistant: ...".
func renderInlineImages(e Entry, opts SynthOptions) []OutputBlock {
	var out []OutputBlock
	for _, b := range e.Content {
		if b.Type != "image" {
			continue
		}
		if opts.ImagesAsPlaceholder {
			placeholder := fmt.Sprintf("[image: %s, ~%d bytes]\n\n", b.ImageMediaType, b.ImageBytes)
			out = append(out, textBlock(placeholder))
			continue
		}
		if b.ImageDataB64 == "" {
			continue
		}
		out = append(out, OutputBlock{
			Text: "",
			Image: &OutputImage{
				MediaType: b.ImageMediaType,
				DataB64:   b.ImageDataB64,
			},
		})
	}
	return out
}

// hasRenderableImage tells the chat renderer whether to still emit a
// turn label even when text is empty (because we are about to emit an
// image block).
func hasRenderableImage(e Entry, opts SynthOptions) bool {
	for _, b := range e.Content {
		if b.Type != "image" {
			continue
		}
		if opts.ImagesAsPlaceholder || b.ImageDataB64 != "" {
			return true
		}
	}
	return false
}

// isToolResultOnly reports whether a user entry consists entirely of
// tool_result blocks (no text from the actual user). Such entries are
// excluded from the chat stream because they belong in the tool
// activity section.
func isToolResultOnly(e Entry) bool {
	if e.TextOnly != "" {
		return false
	}
	if len(e.Content) == 0 {
		return false
	}
	for _, b := range e.Content {
		if b.Type != "tool_result" {
			return false
		}
	}
	return true
}

// summarizeToolArgs renders a short, human-readable view of a
// tool_use input map. Long string values are truncated; nested maps
// collapse to "{...}" so the line stays readable.
func summarizeToolArgs(b ContentBlock) string {
	if len(b.ToolInput) == 0 {
		return ""
	}
	var input map[string]json.RawMessage
	if err := json.Unmarshal(b.ToolInput, &input); err != nil || len(input) == 0 {
		return summarizeRawJSON(b.ToolInput)
	}
	keys := make([]string, 0, len(input))
	for k := range input {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	parts := make([]string, 0, len(keys))
	for _, k := range keys {
		parts = append(parts, fmt.Sprintf("%s=%s", k, summarizeRawJSON(input[k])))
	}
	return strings.Join(parts, ", ")
}

func summarizeRawJSON(raw json.RawMessage) string {
	if len(raw) == 0 {
		return "<value>"
	}
	var asString string
	if json.Unmarshal(raw, &asString) == nil {
		if len(asString) > 80 {
			return fmt.Sprintf("%q...", asString[:77])
		}
		return fmt.Sprintf("%q", asString)
	}
	if len(raw) > 80 {
		return string(raw[:77]) + "..."
	}
	return string(raw)
}

// flattenToolResult concatenates a tool_result.content array into one
// text body and counts visible lines and rough token count.
func flattenToolResult(b *ContentBlock) (string, int, int) {
	if b == nil {
		return "", 0, 0
	}
	var sb strings.Builder
	for _, sub := range b.ToolContent {
		if sub.Type == "text" && sub.Text != "" {
			if sb.Len() > 0 {
				sb.WriteString("\n")
			}
			sb.WriteString(sub.Text)
		}
	}
	body := sb.String()
	if body == "" {
		return "", 0, 0
	}
	lines := strings.Count(body, "\n") + 1
	tokens := len(body) / 4
	return body, lines, tokens
}

// truncHeadTail keeps the first and last halves of body so the model
// sees both ends. Marker line announces the elision.
func truncHeadTail(body string, maxBytes int) string {
	if maxBytes <= 0 || len(body) <= maxBytes {
		return body
	}
	half := maxBytes / 2
	head := body[:half]
	tail := body[len(body)-half:]
	dropped := len(body) - len(head) - len(tail)
	return head + "\n\n... [elided " + strconv.Itoa(dropped) + " bytes] ...\n\n" + tail
}

func turnLabel(role string, ts time.Time) string {
	if ts.IsZero() {
		return fmt.Sprintf("**%s:** ", role)
	}
	return fmt.Sprintf("**%s (%s):** ", role, ts.UTC().Format("2006-01-02 15:04Z"))
}

func textBlock(s string) OutputBlock {
	return OutputBlock{Text: s, Image: nil}
}
