package session

import (
	"errors"
	"fmt"
	"regexp"
	"strings"
	"unicode"
	"unicode/utf8"
)

const (
	// MinNameLength is the minimum allowed legacy slug alias length.
	MinNameLength = 2

	// MaxNameLength is the maximum allowed legacy slug alias length.
	MaxNameLength = 64

	// MinDisplayNameLength is the minimum allowed exact display name length.
	MinDisplayNameLength = 1

	// MaxDisplayNameLength is the maximum allowed exact display name length.
	MaxDisplayNameLength = 200
)

var (
	// sessionNameRegex validates the legacy slug alias format:
	// - Must start and end with alphanumeric (lowercase)
	// - Can contain hyphens in the middle
	// - No consecutive hyphens
	sessionNameRegex = regexp.MustCompile(`^[a-z0-9]([a-z0-9-]*[a-z0-9])?$`)

	// ErrInvalidName is returned when legacy slug alias validation fails.
	ErrInvalidName = errors.New("invalid session name")

	// ErrInvalidDisplayName is returned when exact display-name validation fails.
	ErrInvalidDisplayName = errors.New("invalid display name")

	// autoGeneratedNameSuffix matches the workspace-plus-session-id-prefix names
	// Clyde assigns during adoption before a user/provider title takes over.
	autoGeneratedNameSuffix = regexp.MustCompile(`-[0-9a-f]{8}(-\d+)?$`)
)

type validationError struct {
	kind    error
	message string
}

func (err validationError) Error() string {
	return err.message
}

func (err validationError) Is(target error) bool {
	return target == err.kind
}

func invalidSessionNameError(reason string) error {
	return validationError{
		kind:    ErrInvalidName,
		message: ErrInvalidName.Error() + ": " + reason,
	}
}

func invalidDisplayNameError(reason string) error {
	return validationError{
		kind:    ErrInvalidDisplayName,
		message: ErrInvalidDisplayName.Error() + ": " + reason,
	}
}

// ValidateLegacySlugName checks whether name matches the pre-ClydeUUID slug
// alias format. It is a compatibility policy for migration and hook-boundary
// inputs only; session-domain create, lookup, rename, and parent linkage use
// exact display names plus stable ClydeUUID/provider identity instead.
func ValidateLegacySlugName(name string) error {
	if len(name) < MinNameLength {
		return invalidSessionNameError(fmt.Sprintf("name must be at least %d characters", MinNameLength))
	}

	if len(name) > MaxNameLength {
		return invalidSessionNameError(fmt.Sprintf("name must be at most %d characters", MaxNameLength))
	}

	if !sessionNameRegex.MatchString(name) {
		return invalidSessionNameError("name must be lowercase alphanumeric with hyphens, starting and ending with alphanumeric")
	}

	if strings.Contains(name, "--") {
		return invalidSessionNameError("name cannot contain consecutive hyphens")
	}

	return nil
}

// ValidateDisplayName checks whether name is safe to store as Clyde's exact
// human-visible session name. The policy intentionally does not slugify or
// lowercase: stable storage and parent linkage use ClydeUUID, while this value
// is for display and exact lookup.
func ValidateDisplayName(name string) error {
	if name != strings.TrimSpace(name) {
		return invalidDisplayNameError("name cannot have leading or trailing whitespace")
	}

	if utf8.RuneCountInString(name) < MinDisplayNameLength {
		return invalidDisplayNameError(fmt.Sprintf("name must be at least %d visible character", MinDisplayNameLength))
	}

	if !utf8.ValidString(name) {
		return invalidDisplayNameError("name must be valid UTF-8")
	}

	if utf8.RuneCountInString(name) > MaxDisplayNameLength {
		return invalidDisplayNameError(fmt.Sprintf("name must be at most %d characters", MaxDisplayNameLength))
	}

	for _, r := range name {
		if unicode.IsControl(r) {
			return invalidDisplayNameError("name cannot contain control characters")
		}
	}

	return nil
}

// NameCollisionMax bounds the counter suffix loop so an adversarial taken set
// cannot spin forever. Well above any realistic number of same-base sessions a
// user would ever create.
const NameCollisionMax = 1000

// UniqueLegacySlugName returns base if it is not in taken, otherwise appends a
// numeric suffix until the result is unique. It is for legacy slug aliases only.
func UniqueLegacySlugName(base string, taken map[string]bool) string {
	if base == "" {
		return ""
	}
	if !taken[base] {
		return base
	}
	for i := 2; i < NameCollisionMax; i++ {
		suffix := fmt.Sprintf("-%d", i)
		candidate := base
		if len(candidate)+len(suffix) > MaxNameLength {
			candidate = strings.TrimRight(candidate[:MaxNameLength-len(suffix)], "-")
		}
		candidate += suffix
		if !taken[candidate] {
			return candidate
		}
	}
	return base
}

// UniqueDisplayName returns base if it is not taken, otherwise appends a
// human-visible numeric suffix. Invalid display names return "" so callers can
// fall back to stable id based naming.
func UniqueDisplayName(base string, taken map[string]bool) string {
	base = strings.TrimSpace(base)
	if ValidateDisplayName(base) != nil {
		return ""
	}
	if !taken[base] {
		return base
	}
	for i := 2; i < NameCollisionMax; i++ {
		suffix := fmt.Sprintf(" (%d)", i)
		maxBaseRunes := MaxDisplayNameLength - utf8.RuneCountInString(suffix)
		candidateBase := truncateDisplayName(base, maxBaseRunes)
		if candidateBase == "" {
			return ""
		}
		candidate := candidateBase + suffix
		if !taken[candidate] {
			return candidate
		}
	}
	return base
}

func truncateDisplayName(value string, maxRunes int) string {
	if maxRunes <= 0 {
		return ""
	}
	if utf8.RuneCountInString(value) <= maxRunes {
		return value
	}
	out := make([]rune, 0, maxRunes)
	for _, r := range value {
		if len(out) == maxRunes {
			break
		}
		out = append(out, r)
	}
	return strings.TrimRightFunc(string(out), unicode.IsSpace)
}

// SanitizeLegacySlugName converts an arbitrary string into a valid legacy slug
// alias or returns "" when the input has no usable alphanumeric content.
func SanitizeLegacySlugName(raw string) string {
	if raw == "" {
		return ""
	}
	raw = strings.ToLower(raw)
	var builder strings.Builder
	builder.Grow(len(raw))
	for _, r := range raw {
		switch {
		case r >= 'a' && r <= 'z':
			builder.WriteRune(r)
		case r >= '0' && r <= '9':
			builder.WriteRune(r)
		default:
			builder.WriteByte('-')
		}
	}
	out := collapseHyphens(builder.String())
	out = strings.Trim(out, "-")
	if len(out) > MaxNameLength {
		out = strings.TrimRight(out[:MaxNameLength], "-")
	}
	if ValidateLegacySlugName(out) != nil {
		return ""
	}
	return out
}

func collapseHyphens(value string) string {
	if !strings.Contains(value, "--") {
		return value
	}
	var builder strings.Builder
	builder.Grow(len(value))
	prevHyphen := false
	for _, r := range value {
		if r == '-' {
			if prevHyphen {
				continue
			}
			prevHyphen = true
		} else {
			prevHyphen = false
		}
		builder.WriteRune(r)
	}
	return builder.String()
}

// IsAutoGeneratedName reports whether a name still has the default-shaped
// suffix Clyde assigns during adoption before auto-name claims ownership.
func IsAutoGeneratedName(name string) bool {
	return autoGeneratedNameSuffix.MatchString(name)
}
