// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: clyde/v1/daemon/context.proto

package clydev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProbeContextUsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionName   string                 `protobuf:"bytes,1,opt,name=session_name,json=sessionName,proto3" json:"session_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeContextUsageRequest) Reset() {
	*x = ProbeContextUsageRequest{}
	mi := &file_clyde_v1_daemon_context_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeContextUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeContextUsageRequest) ProtoMessage() {}

func (x *ProbeContextUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_context_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeContextUsageRequest.ProtoReflect.Descriptor instead.
func (*ProbeContextUsageRequest) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_context_proto_rawDescGZIP(), []int{0}
}

func (x *ProbeContextUsageRequest) GetSessionName() string {
	if x != nil {
		return x.SessionName
	}
	return ""
}

type ContextUsageCategory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tokens        int32                  `protobuf:"varint,2,opt,name=tokens,proto3" json:"tokens,omitempty"`
	Color         string                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	IsDeferred    bool                   `protobuf:"varint,4,opt,name=is_deferred,json=isDeferred,proto3" json:"is_deferred,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextUsageCategory) Reset() {
	*x = ContextUsageCategory{}
	mi := &file_clyde_v1_daemon_context_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextUsageCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextUsageCategory) ProtoMessage() {}

func (x *ContextUsageCategory) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_context_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextUsageCategory.ProtoReflect.Descriptor instead.
func (*ContextUsageCategory) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_context_proto_rawDescGZIP(), []int{1}
}

func (x *ContextUsageCategory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContextUsageCategory) GetTokens() int32 {
	if x != nil {
		return x.Tokens
	}
	return 0
}

func (x *ContextUsageCategory) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *ContextUsageCategory) GetIsDeferred() bool {
	if x != nil {
		return x.IsDeferred
	}
	return false
}

type ProbeContextUsageResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	SessionName   string                  `protobuf:"bytes,1,opt,name=session_name,json=sessionName,proto3" json:"session_name,omitempty"`
	SessionId     string                  `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Model         string                  `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	TotalTokens   int32                   `protobuf:"varint,4,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	MaxTokens     int32                   `protobuf:"varint,5,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	Percentage    int32                   `protobuf:"varint,6,opt,name=percentage,proto3" json:"percentage,omitempty"`
	Categories    []*ContextUsageCategory `protobuf:"bytes,7,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeContextUsageResponse) Reset() {
	*x = ProbeContextUsageResponse{}
	mi := &file_clyde_v1_daemon_context_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeContextUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeContextUsageResponse) ProtoMessage() {}

func (x *ProbeContextUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_context_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeContextUsageResponse.ProtoReflect.Descriptor instead.
func (*ProbeContextUsageResponse) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_context_proto_rawDescGZIP(), []int{2}
}

func (x *ProbeContextUsageResponse) GetSessionName() string {
	if x != nil {
		return x.SessionName
	}
	return ""
}

func (x *ProbeContextUsageResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ProbeContextUsageResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ProbeContextUsageResponse) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *ProbeContextUsageResponse) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *ProbeContextUsageResponse) GetPercentage() int32 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *ProbeContextUsageResponse) GetCategories() []*ContextUsageCategory {
	if x != nil {
		return x.Categories
	}
	return nil
}

// CalibrationRecord mirrors the per-session calibration file written
// by compactengine.SaveCalibration. Fields match
// compact.Calibration exactly so the RPC envelope and the on-disk
// record stay in lock step.
type CalibrationRecord struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StaticOverhead int64                  `protobuf:"varint,1,opt,name=static_overhead,json=staticOverhead,proto3" json:"static_overhead,omitempty"`
	CapturedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=captured_at,json=capturedAt,proto3" json:"captured_at,omitempty"`
	Model          string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CalibrationRecord) Reset() {
	*x = CalibrationRecord{}
	mi := &file_clyde_v1_daemon_context_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalibrationRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalibrationRecord) ProtoMessage() {}

func (x *CalibrationRecord) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_context_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalibrationRecord.ProtoReflect.Descriptor instead.
func (*CalibrationRecord) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_context_proto_rawDescGZIP(), []int{3}
}

func (x *CalibrationRecord) GetStaticOverhead() int64 {
	if x != nil {
		return x.StaticOverhead
	}
	return 0
}

func (x *CalibrationRecord) GetCapturedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CapturedAt
	}
	return nil
}

func (x *CalibrationRecord) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type CalibrateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionName   string                 `protobuf:"bytes,1,opt,name=session_name,json=sessionName,proto3" json:"session_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalibrateSessionRequest) Reset() {
	*x = CalibrateSessionRequest{}
	mi := &file_clyde_v1_daemon_context_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalibrateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalibrateSessionRequest) ProtoMessage() {}

func (x *CalibrateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_context_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalibrateSessionRequest.ProtoReflect.Descriptor instead.
func (*CalibrateSessionRequest) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_context_proto_rawDescGZIP(), []int{4}
}

func (x *CalibrateSessionRequest) GetSessionName() string {
	if x != nil {
		return x.SessionName
	}
	return ""
}

type CalibrateSessionResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionName     string                 `protobuf:"bytes,1,opt,name=session_name,json=sessionName,proto3" json:"session_name,omitempty"`
	SessionId       string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Calibration     *CalibrationRecord     `protobuf:"bytes,3,opt,name=calibration,proto3" json:"calibration,omitempty"`
	TotalTokens     int32                  `protobuf:"varint,4,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	CategoriesCount int32                  `protobuf:"varint,5,opt,name=categories_count,json=categoriesCount,proto3" json:"categories_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CalibrateSessionResponse) Reset() {
	*x = CalibrateSessionResponse{}
	mi := &file_clyde_v1_daemon_context_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalibrateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalibrateSessionResponse) ProtoMessage() {}

func (x *CalibrateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_context_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalibrateSessionResponse.ProtoReflect.Descriptor instead.
func (*CalibrateSessionResponse) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_context_proto_rawDescGZIP(), []int{5}
}

func (x *CalibrateSessionResponse) GetSessionName() string {
	if x != nil {
		return x.SessionName
	}
	return ""
}

func (x *CalibrateSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CalibrateSessionResponse) GetCalibration() *CalibrationRecord {
	if x != nil {
		return x.Calibration
	}
	return nil
}

func (x *CalibrateSessionResponse) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *CalibrateSessionResponse) GetCategoriesCount() int32 {
	if x != nil {
		return x.CategoriesCount
	}
	return 0
}

type SetCalibrationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionName    string                 `protobuf:"bytes,1,opt,name=session_name,json=sessionName,proto3" json:"session_name,omitempty"`
	StaticOverhead int64                  `protobuf:"varint,2,opt,name=static_overhead,json=staticOverhead,proto3" json:"static_overhead,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SetCalibrationRequest) Reset() {
	*x = SetCalibrationRequest{}
	mi := &file_clyde_v1_daemon_context_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCalibrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCalibrationRequest) ProtoMessage() {}

func (x *SetCalibrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_context_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCalibrationRequest.ProtoReflect.Descriptor instead.
func (*SetCalibrationRequest) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_context_proto_rawDescGZIP(), []int{6}
}

func (x *SetCalibrationRequest) GetSessionName() string {
	if x != nil {
		return x.SessionName
	}
	return ""
}

func (x *SetCalibrationRequest) GetStaticOverhead() int64 {
	if x != nil {
		return x.StaticOverhead
	}
	return 0
}

type SetCalibrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionName   string                 `protobuf:"bytes,1,opt,name=session_name,json=sessionName,proto3" json:"session_name,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Calibration   *CalibrationRecord     `protobuf:"bytes,3,opt,name=calibration,proto3" json:"calibration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCalibrationResponse) Reset() {
	*x = SetCalibrationResponse{}
	mi := &file_clyde_v1_daemon_context_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCalibrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCalibrationResponse) ProtoMessage() {}

func (x *SetCalibrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_context_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCalibrationResponse.ProtoReflect.Descriptor instead.
func (*SetCalibrationResponse) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_context_proto_rawDescGZIP(), []int{7}
}

func (x *SetCalibrationResponse) GetSessionName() string {
	if x != nil {
		return x.SessionName
	}
	return ""
}

func (x *SetCalibrationResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SetCalibrationResponse) GetCalibration() *CalibrationRecord {
	if x != nil {
		return x.Calibration
	}
	return nil
}

var File_clyde_v1_daemon_context_proto protoreflect.FileDescriptor

const file_clyde_v1_daemon_context_proto_rawDesc = "" +
	"\n" +
	"\x1dclyde/v1/daemon/context.proto\x12\bclyde.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"=\n" +
	"\x18ProbeContextUsageRequest\x12!\n" +
	"\fsession_name\x18\x01 \x01(\tR\vsessionName\"y\n" +
	"\x14ContextUsageCategory\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06tokens\x18\x02 \x01(\x05R\x06tokens\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\x12\x1f\n" +
	"\vis_deferred\x18\x04 \x01(\bR\n" +
	"isDeferred\"\x95\x02\n" +
	"\x19ProbeContextUsageResponse\x12!\n" +
	"\fsession_name\x18\x01 \x01(\tR\vsessionName\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12!\n" +
	"\ftotal_tokens\x18\x04 \x01(\x05R\vtotalTokens\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x05 \x01(\x05R\tmaxTokens\x12\x1e\n" +
	"\n" +
	"percentage\x18\x06 \x01(\x05R\n" +
	"percentage\x12>\n" +
	"\n" +
	"categories\x18\a \x03(\v2\x1e.clyde.v1.ContextUsageCategoryR\n" +
	"categories\"\x8f\x01\n" +
	"\x11CalibrationRecord\x12'\n" +
	"\x0fstatic_overhead\x18\x01 \x01(\x03R\x0estaticOverhead\x12;\n" +
	"\vcaptured_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"capturedAt\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\"<\n" +
	"\x17CalibrateSessionRequest\x12!\n" +
	"\fsession_name\x18\x01 \x01(\tR\vsessionName\"\xe9\x01\n" +
	"\x18CalibrateSessionResponse\x12!\n" +
	"\fsession_name\x18\x01 \x01(\tR\vsessionName\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12=\n" +
	"\vcalibration\x18\x03 \x01(\v2\x1b.clyde.v1.CalibrationRecordR\vcalibration\x12!\n" +
	"\ftotal_tokens\x18\x04 \x01(\x05R\vtotalTokens\x12)\n" +
	"\x10categories_count\x18\x05 \x01(\x05R\x0fcategoriesCount\"c\n" +
	"\x15SetCalibrationRequest\x12!\n" +
	"\fsession_name\x18\x01 \x01(\tR\vsessionName\x12'\n" +
	"\x0fstatic_overhead\x18\x02 \x01(\x03R\x0estaticOverhead\"\x99\x01\n" +
	"\x16SetCalibrationResponse\x12!\n" +
	"\fsession_name\x18\x01 \x01(\tR\vsessionName\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12=\n" +
	"\vcalibration\x18\x03 \x01(\v2\x1b.clyde.v1.CalibrationRecordR\vcalibrationB(Z&goodkind.io/clyde/api/clyde/v1;clydev1b\x06proto3"

var (
	file_clyde_v1_daemon_context_proto_rawDescOnce sync.Once
	file_clyde_v1_daemon_context_proto_rawDescData []byte
)

func file_clyde_v1_daemon_context_proto_rawDescGZIP() []byte {
	file_clyde_v1_daemon_context_proto_rawDescOnce.Do(func() {
		file_clyde_v1_daemon_context_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clyde_v1_daemon_context_proto_rawDesc), len(file_clyde_v1_daemon_context_proto_rawDesc)))
	})
	return file_clyde_v1_daemon_context_proto_rawDescData
}

var file_clyde_v1_daemon_context_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_clyde_v1_daemon_context_proto_goTypes = []any{
	(*ProbeContextUsageRequest)(nil),  // 0: clyde.v1.ProbeContextUsageRequest
	(*ContextUsageCategory)(nil),      // 1: clyde.v1.ContextUsageCategory
	(*ProbeContextUsageResponse)(nil), // 2: clyde.v1.ProbeContextUsageResponse
	(*CalibrationRecord)(nil),         // 3: clyde.v1.CalibrationRecord
	(*CalibrateSessionRequest)(nil),   // 4: clyde.v1.CalibrateSessionRequest
	(*CalibrateSessionResponse)(nil),  // 5: clyde.v1.CalibrateSessionResponse
	(*SetCalibrationRequest)(nil),     // 6: clyde.v1.SetCalibrationRequest
	(*SetCalibrationResponse)(nil),    // 7: clyde.v1.SetCalibrationResponse
	(*timestamppb.Timestamp)(nil),     // 8: google.protobuf.Timestamp
}
var file_clyde_v1_daemon_context_proto_depIdxs = []int32{
	1, // 0: clyde.v1.ProbeContextUsageResponse.categories:type_name -> clyde.v1.ContextUsageCategory
	8, // 1: clyde.v1.CalibrationRecord.captured_at:type_name -> google.protobuf.Timestamp
	3, // 2: clyde.v1.CalibrateSessionResponse.calibration:type_name -> clyde.v1.CalibrationRecord
	3, // 3: clyde.v1.SetCalibrationResponse.calibration:type_name -> clyde.v1.CalibrationRecord
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_clyde_v1_daemon_context_proto_init() }
func file_clyde_v1_daemon_context_proto_init() {
	if File_clyde_v1_daemon_context_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clyde_v1_daemon_context_proto_rawDesc), len(file_clyde_v1_daemon_context_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_clyde_v1_daemon_context_proto_goTypes,
		DependencyIndexes: file_clyde_v1_daemon_context_proto_depIdxs,
		MessageInfos:      file_clyde_v1_daemon_context_proto_msgTypes,
	}.Build()
	File_clyde_v1_daemon_context_proto = out.File
	file_clyde_v1_daemon_context_proto_goTypes = nil
	file_clyde_v1_daemon_context_proto_depIdxs = nil
}
