// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: clyde/v1/daemon/provider.proto

package clydev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Provider int32

const (
	Provider_PROVIDER_UNSPECIFIED   Provider = 0
	Provider_PROVIDER_CLAUDE        Provider = 1
	Provider_PROVIDER_CODEX         Provider = 2
	Provider_PROVIDER_ANTHROPIC     Provider = 3
	Provider_PROVIDER_OPENAI_COMPAT Provider = 4
	Provider_PROVIDER_MITM          Provider = 5
	Provider_PROVIDER_ARTIFACT      Provider = 6
	Provider_PROVIDER_CURSOR        Provider = 7
	Provider_PROVIDER_CONDUCTOR     Provider = 8
	Provider_PROVIDER_ZED           Provider = 9
	Provider_PROVIDER_COPILOT       Provider = 10
)

// Enum value maps for Provider.
var (
	Provider_name = map[int32]string{
		0:  "PROVIDER_UNSPECIFIED",
		1:  "PROVIDER_CLAUDE",
		2:  "PROVIDER_CODEX",
		3:  "PROVIDER_ANTHROPIC",
		4:  "PROVIDER_OPENAI_COMPAT",
		5:  "PROVIDER_MITM",
		6:  "PROVIDER_ARTIFACT",
		7:  "PROVIDER_CURSOR",
		8:  "PROVIDER_CONDUCTOR",
		9:  "PROVIDER_ZED",
		10: "PROVIDER_COPILOT",
	}
	Provider_value = map[string]int32{
		"PROVIDER_UNSPECIFIED":   0,
		"PROVIDER_CLAUDE":        1,
		"PROVIDER_CODEX":         2,
		"PROVIDER_ANTHROPIC":     3,
		"PROVIDER_OPENAI_COMPAT": 4,
		"PROVIDER_MITM":          5,
		"PROVIDER_ARTIFACT":      6,
		"PROVIDER_CURSOR":        7,
		"PROVIDER_CONDUCTOR":     8,
		"PROVIDER_ZED":           9,
		"PROVIDER_COPILOT":       10,
	}
)

func (x Provider) Enum() *Provider {
	p := new(Provider)
	*p = x
	return p
}

func (x Provider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Provider) Descriptor() protoreflect.EnumDescriptor {
	return file_clyde_v1_daemon_provider_proto_enumTypes[0].Descriptor()
}

func (Provider) Type() protoreflect.EnumType {
	return &file_clyde_v1_daemon_provider_proto_enumTypes[0]
}

func (x Provider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Provider.Descriptor instead.
func (Provider) EnumDescriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_provider_proto_rawDescGZIP(), []int{0}
}

type GetProviderStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderStatsRequest) Reset() {
	*x = GetProviderStatsRequest{}
	mi := &file_clyde_v1_daemon_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderStatsRequest) ProtoMessage() {}

func (x *GetProviderStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderStatsRequest.ProtoReflect.Descriptor instead.
func (*GetProviderStatsRequest) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_provider_proto_rawDescGZIP(), []int{0}
}

type SubscribeProviderStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeProviderStatsRequest) Reset() {
	*x = SubscribeProviderStatsRequest{}
	mi := &file_clyde_v1_daemon_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeProviderStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeProviderStatsRequest) ProtoMessage() {}

func (x *SubscribeProviderStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeProviderStatsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeProviderStatsRequest) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_provider_proto_rawDescGZIP(), []int{1}
}

type ProviderStats struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Provider                   Provider               `protobuf:"varint,1,opt,name=provider,proto3,enum=clyde.v1.Provider" json:"provider,omitempty"`
	Requests                   int32                  `protobuf:"varint,2,opt,name=requests,proto3" json:"requests,omitempty"`
	Inflight                   int32                  `protobuf:"varint,3,opt,name=inflight,proto3" json:"inflight,omitempty"`
	Streaming                  int32                  `protobuf:"varint,4,opt,name=streaming,proto3" json:"streaming,omitempty"`
	InputTokens                int64                  `protobuf:"varint,5,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens               int64                  `protobuf:"varint,6,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	CacheReadTokens            int64                  `protobuf:"varint,7,opt,name=cache_read_tokens,json=cacheReadTokens,proto3" json:"cache_read_tokens,omitempty"`
	CacheCreationTokens        int64                  `protobuf:"varint,8,opt,name=cache_creation_tokens,json=cacheCreationTokens,proto3" json:"cache_creation_tokens,omitempty"`
	HitRatio                   float64                `protobuf:"fixed64,9,opt,name=hit_ratio,json=hitRatio,proto3" json:"hit_ratio,omitempty"`
	EstimatedCostMicrocents    int64                  `protobuf:"varint,10,opt,name=estimated_cost_microcents,json=estimatedCostMicrocents,proto3" json:"estimated_cost_microcents,omitempty"`
	LastSeenUnix               int64                  `protobuf:"varint,11,opt,name=last_seen_unix,json=lastSeenUnix,proto3" json:"last_seen_unix,omitempty"`
	Error                      string                 `protobuf:"bytes,12,opt,name=error,proto3" json:"error,omitempty"`
	DerivedCacheCreationTokens int64                  `protobuf:"varint,13,opt,name=derived_cache_creation_tokens,json=derivedCacheCreationTokens,proto3" json:"derived_cache_creation_tokens,omitempty"`
	ProviderDetail             string                 `protobuf:"bytes,14,opt,name=provider_detail,json=providerDetail,proto3" json:"provider_detail,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *ProviderStats) Reset() {
	*x = ProviderStats{}
	mi := &file_clyde_v1_daemon_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderStats) ProtoMessage() {}

func (x *ProviderStats) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderStats.ProtoReflect.Descriptor instead.
func (*ProviderStats) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_provider_proto_rawDescGZIP(), []int{2}
}

func (x *ProviderStats) GetProvider() Provider {
	if x != nil {
		return x.Provider
	}
	return Provider_PROVIDER_UNSPECIFIED
}

func (x *ProviderStats) GetRequests() int32 {
	if x != nil {
		return x.Requests
	}
	return 0
}

func (x *ProviderStats) GetInflight() int32 {
	if x != nil {
		return x.Inflight
	}
	return 0
}

func (x *ProviderStats) GetStreaming() int32 {
	if x != nil {
		return x.Streaming
	}
	return 0
}

func (x *ProviderStats) GetInputTokens() int64 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *ProviderStats) GetOutputTokens() int64 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *ProviderStats) GetCacheReadTokens() int64 {
	if x != nil {
		return x.CacheReadTokens
	}
	return 0
}

func (x *ProviderStats) GetCacheCreationTokens() int64 {
	if x != nil {
		return x.CacheCreationTokens
	}
	return 0
}

func (x *ProviderStats) GetHitRatio() float64 {
	if x != nil {
		return x.HitRatio
	}
	return 0
}

func (x *ProviderStats) GetEstimatedCostMicrocents() int64 {
	if x != nil {
		return x.EstimatedCostMicrocents
	}
	return 0
}

func (x *ProviderStats) GetLastSeenUnix() int64 {
	if x != nil {
		return x.LastSeenUnix
	}
	return 0
}

func (x *ProviderStats) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ProviderStats) GetDerivedCacheCreationTokens() int64 {
	if x != nil {
		return x.DerivedCacheCreationTokens
	}
	return 0
}

func (x *ProviderStats) GetProviderDetail() string {
	if x != nil {
		return x.ProviderDetail
	}
	return ""
}

type GetProviderStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []*ProviderStats       `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	LoadedAtUnix  int64                  `protobuf:"varint,2,opt,name=loaded_at_unix,json=loadedAtUnix,proto3" json:"loaded_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderStatsResponse) Reset() {
	*x = GetProviderStatsResponse{}
	mi := &file_clyde_v1_daemon_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderStatsResponse) ProtoMessage() {}

func (x *GetProviderStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderStatsResponse.ProtoReflect.Descriptor instead.
func (*GetProviderStatsResponse) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_provider_proto_rawDescGZIP(), []int{3}
}

func (x *GetProviderStatsResponse) GetProviders() []*ProviderStats {
	if x != nil {
		return x.Providers
	}
	return nil
}

func (x *GetProviderStatsResponse) GetLoadedAtUnix() int64 {
	if x != nil {
		return x.LoadedAtUnix
	}
	return 0
}

type ProviderStatsEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *ProviderStats         `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	EmittedAtUnix int64                  `protobuf:"varint,2,opt,name=emitted_at_unix,json=emittedAtUnix,proto3" json:"emitted_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderStatsEvent) Reset() {
	*x = ProviderStatsEvent{}
	mi := &file_clyde_v1_daemon_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderStatsEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderStatsEvent) ProtoMessage() {}

func (x *ProviderStatsEvent) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderStatsEvent.ProtoReflect.Descriptor instead.
func (*ProviderStatsEvent) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_provider_proto_rawDescGZIP(), []int{4}
}

func (x *ProviderStatsEvent) GetStats() *ProviderStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *ProviderStatsEvent) GetEmittedAtUnix() int64 {
	if x != nil {
		return x.EmittedAtUnix
	}
	return 0
}

type ReloadDaemonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadDaemonRequest) Reset() {
	*x = ReloadDaemonRequest{}
	mi := &file_clyde_v1_daemon_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadDaemonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadDaemonRequest) ProtoMessage() {}

func (x *ReloadDaemonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadDaemonRequest.ProtoReflect.Descriptor instead.
func (*ReloadDaemonRequest) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_provider_proto_rawDescGZIP(), []int{5}
}

type ReloadDaemonResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BinaryReloaded bool                   `protobuf:"varint,1,opt,name=binary_reloaded,json=binaryReloaded,proto3" json:"binary_reloaded,omitempty"`
	ActiveSurfaces int64                  `protobuf:"varint,2,opt,name=active_surfaces,json=activeSurfaces,proto3" json:"active_surfaces,omitempty"`
	NewPid         int64                  `protobuf:"varint,3,opt,name=new_pid,json=newPid,proto3" json:"new_pid,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReloadDaemonResponse) Reset() {
	*x = ReloadDaemonResponse{}
	mi := &file_clyde_v1_daemon_provider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadDaemonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadDaemonResponse) ProtoMessage() {}

func (x *ReloadDaemonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_provider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadDaemonResponse.ProtoReflect.Descriptor instead.
func (*ReloadDaemonResponse) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_provider_proto_rawDescGZIP(), []int{6}
}

func (x *ReloadDaemonResponse) GetBinaryReloaded() bool {
	if x != nil {
		return x.BinaryReloaded
	}
	return false
}

func (x *ReloadDaemonResponse) GetActiveSurfaces() int64 {
	if x != nil {
		return x.ActiveSurfaces
	}
	return 0
}

func (x *ReloadDaemonResponse) GetNewPid() int64 {
	if x != nil {
		return x.NewPid
	}
	return 0
}

var File_clyde_v1_daemon_provider_proto protoreflect.FileDescriptor

const file_clyde_v1_daemon_provider_proto_rawDesc = "" +
	"\n" +
	"\x1eclyde/v1/daemon/provider.proto\x12\bclyde.v1\"\x19\n" +
	"\x17GetProviderStatsRequest\"\x1f\n" +
	"\x1dSubscribeProviderStatsRequest\"\xbe\x04\n" +
	"\rProviderStats\x12.\n" +
	"\bprovider\x18\x01 \x01(\x0e2\x12.clyde.v1.ProviderR\bprovider\x12\x1a\n" +
	"\brequests\x18\x02 \x01(\x05R\brequests\x12\x1a\n" +
	"\binflight\x18\x03 \x01(\x05R\binflight\x12\x1c\n" +
	"\tstreaming\x18\x04 \x01(\x05R\tstreaming\x12!\n" +
	"\finput_tokens\x18\x05 \x01(\x03R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x06 \x01(\x03R\foutputTokens\x12*\n" +
	"\x11cache_read_tokens\x18\a \x01(\x03R\x0fcacheReadTokens\x122\n" +
	"\x15cache_creation_tokens\x18\b \x01(\x03R\x13cacheCreationTokens\x12\x1b\n" +
	"\thit_ratio\x18\t \x01(\x01R\bhitRatio\x12:\n" +
	"\x19estimated_cost_microcents\x18\n" +
	" \x01(\x03R\x17estimatedCostMicrocents\x12$\n" +
	"\x0elast_seen_unix\x18\v \x01(\x03R\flastSeenUnix\x12\x14\n" +
	"\x05error\x18\f \x01(\tR\x05error\x12A\n" +
	"\x1dderived_cache_creation_tokens\x18\r \x01(\x03R\x1aderivedCacheCreationTokens\x12'\n" +
	"\x0fprovider_detail\x18\x0e \x01(\tR\x0eproviderDetail\"w\n" +
	"\x18GetProviderStatsResponse\x125\n" +
	"\tproviders\x18\x01 \x03(\v2\x17.clyde.v1.ProviderStatsR\tproviders\x12$\n" +
	"\x0eloaded_at_unix\x18\x02 \x01(\x03R\floadedAtUnix\"k\n" +
	"\x12ProviderStatsEvent\x12-\n" +
	"\x05stats\x18\x01 \x01(\v2\x17.clyde.v1.ProviderStatsR\x05stats\x12&\n" +
	"\x0femitted_at_unix\x18\x02 \x01(\x03R\remittedAtUnix\"\x15\n" +
	"\x13ReloadDaemonRequest\"\x81\x01\n" +
	"\x14ReloadDaemonResponse\x12'\n" +
	"\x0fbinary_reloaded\x18\x01 \x01(\bR\x0ebinaryReloaded\x12'\n" +
	"\x0factive_surfaces\x18\x02 \x01(\x03R\x0eactiveSurfaces\x12\x17\n" +
	"\anew_pid\x18\x03 \x01(\x03R\x06newPid*\x80\x02\n" +
	"\bProvider\x12\x18\n" +
	"\x14PROVIDER_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fPROVIDER_CLAUDE\x10\x01\x12\x12\n" +
	"\x0ePROVIDER_CODEX\x10\x02\x12\x16\n" +
	"\x12PROVIDER_ANTHROPIC\x10\x03\x12\x1a\n" +
	"\x16PROVIDER_OPENAI_COMPAT\x10\x04\x12\x11\n" +
	"\rPROVIDER_MITM\x10\x05\x12\x15\n" +
	"\x11PROVIDER_ARTIFACT\x10\x06\x12\x13\n" +
	"\x0fPROVIDER_CURSOR\x10\a\x12\x16\n" +
	"\x12PROVIDER_CONDUCTOR\x10\b\x12\x10\n" +
	"\fPROVIDER_ZED\x10\t\x12\x14\n" +
	"\x10PROVIDER_COPILOT\x10\n" +
	"B(Z&goodkind.io/clyde/api/clyde/v1;clydev1b\x06proto3"

var (
	file_clyde_v1_daemon_provider_proto_rawDescOnce sync.Once
	file_clyde_v1_daemon_provider_proto_rawDescData []byte
)

func file_clyde_v1_daemon_provider_proto_rawDescGZIP() []byte {
	file_clyde_v1_daemon_provider_proto_rawDescOnce.Do(func() {
		file_clyde_v1_daemon_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clyde_v1_daemon_provider_proto_rawDesc), len(file_clyde_v1_daemon_provider_proto_rawDesc)))
	})
	return file_clyde_v1_daemon_provider_proto_rawDescData
}

var file_clyde_v1_daemon_provider_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_clyde_v1_daemon_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_clyde_v1_daemon_provider_proto_goTypes = []any{
	(Provider)(0),                         // 0: clyde.v1.Provider
	(*GetProviderStatsRequest)(nil),       // 1: clyde.v1.GetProviderStatsRequest
	(*SubscribeProviderStatsRequest)(nil), // 2: clyde.v1.SubscribeProviderStatsRequest
	(*ProviderStats)(nil),                 // 3: clyde.v1.ProviderStats
	(*GetProviderStatsResponse)(nil),      // 4: clyde.v1.GetProviderStatsResponse
	(*ProviderStatsEvent)(nil),            // 5: clyde.v1.ProviderStatsEvent
	(*ReloadDaemonRequest)(nil),           // 6: clyde.v1.ReloadDaemonRequest
	(*ReloadDaemonResponse)(nil),          // 7: clyde.v1.ReloadDaemonResponse
}
var file_clyde_v1_daemon_provider_proto_depIdxs = []int32{
	0, // 0: clyde.v1.ProviderStats.provider:type_name -> clyde.v1.Provider
	3, // 1: clyde.v1.GetProviderStatsResponse.providers:type_name -> clyde.v1.ProviderStats
	3, // 2: clyde.v1.ProviderStatsEvent.stats:type_name -> clyde.v1.ProviderStats
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_clyde_v1_daemon_provider_proto_init() }
func file_clyde_v1_daemon_provider_proto_init() {
	if File_clyde_v1_daemon_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clyde_v1_daemon_provider_proto_rawDesc), len(file_clyde_v1_daemon_provider_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_clyde_v1_daemon_provider_proto_goTypes,
		DependencyIndexes: file_clyde_v1_daemon_provider_proto_depIdxs,
		EnumInfos:         file_clyde_v1_daemon_provider_proto_enumTypes,
		MessageInfos:      file_clyde_v1_daemon_provider_proto_msgTypes,
	}.Build()
	File_clyde_v1_daemon_provider_proto = out.File
	file_clyde_v1_daemon_provider_proto_goTypes = nil
	file_clyde_v1_daemon_provider_proto_depIdxs = nil
}
