// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: clyde/v1/daemon/service.proto

package clydev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SearchSource names where the returned matches came from, replacing the old
// warming bool with an explicit provenance the caller can branch on.
type SearchSource int32

const (
	SearchSource_SEARCH_SOURCE_UNSPECIFIED SearchSource = 0
	// SEARCH_SOURCE_SEMANTIC means the vector engine produced the matches.
	SearchSource_SEARCH_SOURCE_SEMANTIC SearchSource = 1
	// SEARCH_SOURCE_LITERAL means the engine was unavailable or empty and the
	// literal transcript scan produced the matches.
	SearchSource_SEARCH_SOURCE_LITERAL SearchSource = 2
	// SEARCH_SOURCE_LITERAL_DISABLED_COLD means the engine produced nothing and
	// the literal fallback is disabled, so no matches were returned on purpose.
	SearchSource_SEARCH_SOURCE_LITERAL_DISABLED_COLD SearchSource = 3
)

// Enum value maps for SearchSource.
var (
	SearchSource_name = map[int32]string{
		0: "SEARCH_SOURCE_UNSPECIFIED",
		1: "SEARCH_SOURCE_SEMANTIC",
		2: "SEARCH_SOURCE_LITERAL",
		3: "SEARCH_SOURCE_LITERAL_DISABLED_COLD",
	}
	SearchSource_value = map[string]int32{
		"SEARCH_SOURCE_UNSPECIFIED":           0,
		"SEARCH_SOURCE_SEMANTIC":              1,
		"SEARCH_SOURCE_LITERAL":               2,
		"SEARCH_SOURCE_LITERAL_DISABLED_COLD": 3,
	}
)

func (x SearchSource) Enum() *SearchSource {
	p := new(SearchSource)
	*p = x
	return p
}

func (x SearchSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchSource) Descriptor() protoreflect.EnumDescriptor {
	return file_clyde_v1_daemon_service_proto_enumTypes[0].Descriptor()
}

func (SearchSource) Type() protoreflect.EnumType {
	return &file_clyde_v1_daemon_service_proto_enumTypes[0]
}

func (x SearchSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchSource.Descriptor instead.
func (SearchSource) EnumDescriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{0}
}

type LogsInventoryRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StateRoot        string                 `protobuf:"bytes,1,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	LargestFileLimit int64                  `protobuf:"varint,2,opt,name=largest_file_limit,json=largestFileLimit,proto3" json:"largest_file_limit,omitempty"`
	Deep             bool                   `protobuf:"varint,3,opt,name=deep,proto3" json:"deep,omitempty"`
	Json             bool                   `protobuf:"varint,4,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LogsInventoryRequest) Reset() {
	*x = LogsInventoryRequest{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsInventoryRequest) ProtoMessage() {}

func (x *LogsInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsInventoryRequest.ProtoReflect.Descriptor instead.
func (*LogsInventoryRequest) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{0}
}

func (x *LogsInventoryRequest) GetStateRoot() string {
	if x != nil {
		return x.StateRoot
	}
	return ""
}

func (x *LogsInventoryRequest) GetLargestFileLimit() int64 {
	if x != nil {
		return x.LargestFileLimit
	}
	return 0
}

func (x *LogsInventoryRequest) GetDeep() bool {
	if x != nil {
		return x.Deep
	}
	return false
}

func (x *LogsInventoryRequest) GetJson() bool {
	if x != nil {
		return x.Json
	}
	return false
}

type LogsInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsInventoryResponse) Reset() {
	*x = LogsInventoryResponse{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsInventoryResponse) ProtoMessage() {}

func (x *LogsInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsInventoryResponse.ProtoReflect.Descriptor instead.
func (*LogsInventoryResponse) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{1}
}

func (x *LogsInventoryResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type SeedBaselineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Upstream      string                 `protobuf:"bytes,1,opt,name=upstream,proto3" json:"upstream,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	Output        string                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	IncludeUa     []string               `protobuf:"bytes,4,rep,name=include_ua,json=includeUa,proto3" json:"include_ua,omitempty"`
	ExcludeUa     []string               `protobuf:"bytes,5,rep,name=exclude_ua,json=excludeUa,proto3" json:"exclude_ua,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeedBaselineRequest) Reset() {
	*x = SeedBaselineRequest{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeedBaselineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeedBaselineRequest) ProtoMessage() {}

func (x *SeedBaselineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeedBaselineRequest.ProtoReflect.Descriptor instead.
func (*SeedBaselineRequest) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{2}
}

func (x *SeedBaselineRequest) GetUpstream() string {
	if x != nil {
		return x.Upstream
	}
	return ""
}

func (x *SeedBaselineRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *SeedBaselineRequest) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *SeedBaselineRequest) GetIncludeUa() []string {
	if x != nil {
		return x.IncludeUa
	}
	return nil
}

func (x *SeedBaselineRequest) GetExcludeUa() []string {
	if x != nil {
		return x.ExcludeUa
	}
	return nil
}

type SeedBaselineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Written       string                 `protobuf:"bytes,1,opt,name=written,proto3" json:"written,omitempty"`
	Upstream      string                 `protobuf:"bytes,2,opt,name=upstream,proto3" json:"upstream,omitempty"`
	Flavors       int64                  `protobuf:"varint,3,opt,name=flavors,proto3" json:"flavors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeedBaselineResponse) Reset() {
	*x = SeedBaselineResponse{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeedBaselineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeedBaselineResponse) ProtoMessage() {}

func (x *SeedBaselineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeedBaselineResponse.ProtoReflect.Descriptor instead.
func (*SeedBaselineResponse) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{3}
}

func (x *SeedBaselineResponse) GetWritten() string {
	if x != nil {
		return x.Written
	}
	return ""
}

func (x *SeedBaselineResponse) GetUpstream() string {
	if x != nil {
		return x.Upstream
	}
	return ""
}

func (x *SeedBaselineResponse) GetFlavors() int64 {
	if x != nil {
		return x.Flavors
	}
	return 0
}

type ShowCaptureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Json          bool                   `protobuf:"varint,2,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowCaptureRequest) Reset() {
	*x = ShowCaptureRequest{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowCaptureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowCaptureRequest) ProtoMessage() {}

func (x *ShowCaptureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowCaptureRequest.ProtoReflect.Descriptor instead.
func (*ShowCaptureRequest) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{4}
}

func (x *ShowCaptureRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ShowCaptureRequest) GetJson() bool {
	if x != nil {
		return x.Json
	}
	return false
}

type ShowCaptureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowCaptureResponse) Reset() {
	*x = ShowCaptureResponse{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowCaptureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowCaptureResponse) ProtoMessage() {}

func (x *ShowCaptureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowCaptureResponse.ProtoReflect.Descriptor instead.
func (*ShowCaptureResponse) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{5}
}

func (x *ShowCaptureResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type GetMITMStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMITMStatusRequest) Reset() {
	*x = GetMITMStatusRequest{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMITMStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMITMStatusRequest) ProtoMessage() {}

func (x *GetMITMStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMITMStatusRequest.ProtoReflect.Descriptor instead.
func (*GetMITMStatusRequest) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{6}
}

type MITMListenerStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Up            bool                   `protobuf:"varint,3,opt,name=up,proto3" json:"up,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MITMListenerStatus) Reset() {
	*x = MITMListenerStatus{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MITMListenerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MITMListenerStatus) ProtoMessage() {}

func (x *MITMListenerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MITMListenerStatus.ProtoReflect.Descriptor instead.
func (*MITMListenerStatus) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{7}
}

func (x *MITMListenerStatus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MITMListenerStatus) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *MITMListenerStatus) GetUp() bool {
	if x != nil {
		return x.Up
	}
	return false
}

type GetMITMStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Listeners     []*MITMListenerStatus  `protobuf:"bytes,1,rep,name=listeners,proto3" json:"listeners,omitempty"`
	CaCertPath    string                 `protobuf:"bytes,2,opt,name=ca_cert_path,json=caCertPath,proto3" json:"ca_cert_path,omitempty"`
	CaKeyPath     string                 `protobuf:"bytes,3,opt,name=ca_key_path,json=caKeyPath,proto3" json:"ca_key_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMITMStatusResponse) Reset() {
	*x = GetMITMStatusResponse{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMITMStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMITMStatusResponse) ProtoMessage() {}

func (x *GetMITMStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMITMStatusResponse.ProtoReflect.Descriptor instead.
func (*GetMITMStatusResponse) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetMITMStatusResponse) GetListeners() []*MITMListenerStatus {
	if x != nil {
		return x.Listeners
	}
	return nil
}

func (x *GetMITMStatusResponse) GetCaCertPath() string {
	if x != nil {
		return x.CaCertPath
	}
	return ""
}

func (x *GetMITMStatusResponse) GetCaKeyPath() string {
	if x != nil {
		return x.CaKeyPath
	}
	return ""
}

type ListConversationsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Limit           int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset          int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Provider        Provider               `protobuf:"varint,3,opt,name=provider,proto3,enum=clyde.v1.Provider" json:"provider,omitempty"`
	Workspace       string                 `protobuf:"bytes,4,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Query           string                 `protobuf:"bytes,5,opt,name=query,proto3" json:"query,omitempty"`
	IncludeArchived bool                   `protobuf:"varint,6,opt,name=include_archived,json=includeArchived,proto3" json:"include_archived,omitempty"`
	All             bool                   `protobuf:"varint,7,opt,name=all,proto3" json:"all,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListConversationsRequest) Reset() {
	*x = ListConversationsRequest{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsRequest) ProtoMessage() {}

func (x *ListConversationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsRequest.ProtoReflect.Descriptor instead.
func (*ListConversationsRequest) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{9}
}

func (x *ListConversationsRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListConversationsRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListConversationsRequest) GetProvider() Provider {
	if x != nil {
		return x.Provider
	}
	return Provider_PROVIDER_UNSPECIFIED
}

func (x *ListConversationsRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *ListConversationsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ListConversationsRequest) GetIncludeArchived() bool {
	if x != nil {
		return x.IncludeArchived
	}
	return false
}

func (x *ListConversationsRequest) GetAll() bool {
	if x != nil {
		return x.All
	}
	return false
}

type GetConversationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	LastN          int64                  `protobuf:"varint,2,opt,name=last_n,json=lastN,proto3" json:"last_n,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetConversationRequest) Reset() {
	*x = GetConversationRequest{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationRequest) ProtoMessage() {}

func (x *GetConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationRequest.ProtoReflect.Descriptor instead.
func (*GetConversationRequest) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetConversationRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *GetConversationRequest) GetLastN() int64 {
	if x != nil {
		return x.LastN
	}
	return 0
}

// ConversationChunk is one UTF-8 text slice of a streamed transcript or context
// window. The full payload is the concatenation of every chunk's text in
// receive order; chunk boundaries carry no semantics and may split a multibyte
// rune only at the transport layer, which the reassembler stitches back.
type ConversationChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          []byte                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationChunk) Reset() {
	*x = ConversationChunk{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationChunk) ProtoMessage() {}

func (x *ConversationChunk) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationChunk.ProtoReflect.Descriptor instead.
func (*ConversationChunk) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{11}
}

func (x *ConversationChunk) GetText() []byte {
	if x != nil {
		return x.Text
	}
	return nil
}

// ExportChunk is one byte slice of a streamed export body. The full export is
// the concatenation of every chunk's body in receive order.
type ExportChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          []byte                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportChunk) Reset() {
	*x = ExportChunk{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportChunk) ProtoMessage() {}

func (x *ExportChunk) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportChunk.ProtoReflect.Descriptor instead.
func (*ExportChunk) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{12}
}

func (x *ExportChunk) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type GetConversationContextRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Timestamp      string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	MessageIndex   int64                  `protobuf:"varint,3,opt,name=message_index,json=messageIndex,proto3" json:"message_index,omitempty"`
	Before         int64                  `protobuf:"varint,4,opt,name=before,proto3" json:"before,omitempty"`
	After          int64                  `protobuf:"varint,5,opt,name=after,proto3" json:"after,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetConversationContextRequest) Reset() {
	*x = GetConversationContextRequest{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationContextRequest) ProtoMessage() {}

func (x *GetConversationContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationContextRequest.ProtoReflect.Descriptor instead.
func (*GetConversationContextRequest) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetConversationContextRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *GetConversationContextRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *GetConversationContextRequest) GetMessageIndex() int64 {
	if x != nil {
		return x.MessageIndex
	}
	return 0
}

func (x *GetConversationContextRequest) GetBefore() int64 {
	if x != nil {
		return x.Before
	}
	return 0
}

func (x *GetConversationContextRequest) GetAfter() int64 {
	if x != nil {
		return x.After
	}
	return 0
}

type SearchConversationsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Query           string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit           int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Provider        Provider               `protobuf:"varint,3,opt,name=provider,proto3,enum=clyde.v1.Provider" json:"provider,omitempty"`
	Workspace       string                 `protobuf:"bytes,4,opt,name=workspace,proto3" json:"workspace,omitempty"`
	IncludeArchived bool                   `protobuf:"varint,5,opt,name=include_archived,json=includeArchived,proto3" json:"include_archived,omitempty"`
	Roles           []string               `protobuf:"bytes,6,rep,name=roles,proto3" json:"roles,omitempty"`
	FromUnix        int64                  `protobuf:"varint,7,opt,name=from_unix,json=fromUnix,proto3" json:"from_unix,omitempty"`
	UntilUnix       int64                  `protobuf:"varint,8,opt,name=until_unix,json=untilUnix,proto3" json:"until_unix,omitempty"`
	MinScore        float64                `protobuf:"fixed64,9,opt,name=min_score,json=minScore,proto3" json:"min_score,omitempty"`
	// per_conversation_limit caps hits per conversation so one large transcript
	// does not monopolize the result list. Zero means uncapped.
	PerConversationLimit int64 `protobuf:"varint,10,opt,name=per_conversation_limit,json=perConversationLimit,proto3" json:"per_conversation_limit,omitempty"`
	// conversation_id scopes discovery to a single conversation, the within-search
	// behavior. Empty means corpus-wide discovery.
	ConversationId string `protobuf:"bytes,11,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	// context_window is the number of messages before and after each hit to render
	// inline on the match. Zero means the daemon's default small window.
	ContextWindow int64 `protobuf:"varint,12,opt,name=context_window,json=contextWindow,proto3" json:"context_window,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchConversationsRequest) Reset() {
	*x = SearchConversationsRequest{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchConversationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchConversationsRequest) ProtoMessage() {}

func (x *SearchConversationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchConversationsRequest.ProtoReflect.Descriptor instead.
func (*SearchConversationsRequest) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{14}
}

func (x *SearchConversationsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchConversationsRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchConversationsRequest) GetProvider() Provider {
	if x != nil {
		return x.Provider
	}
	return Provider_PROVIDER_UNSPECIFIED
}

func (x *SearchConversationsRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *SearchConversationsRequest) GetIncludeArchived() bool {
	if x != nil {
		return x.IncludeArchived
	}
	return false
}

func (x *SearchConversationsRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *SearchConversationsRequest) GetFromUnix() int64 {
	if x != nil {
		return x.FromUnix
	}
	return 0
}

func (x *SearchConversationsRequest) GetUntilUnix() int64 {
	if x != nil {
		return x.UntilUnix
	}
	return 0
}

func (x *SearchConversationsRequest) GetMinScore() float64 {
	if x != nil {
		return x.MinScore
	}
	return 0
}

func (x *SearchConversationsRequest) GetPerConversationLimit() int64 {
	if x != nil {
		return x.PerConversationLimit
	}
	return 0
}

func (x *SearchConversationsRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *SearchConversationsRequest) GetContextWindow() int64 {
	if x != nil {
		return x.ContextWindow
	}
	return 0
}

type ConversationSearchMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conversation  *ConversationRecord    `protobuf:"bytes,1,opt,name=conversation,proto3" json:"conversation,omitempty"`
	MessageIndex  int64                  `protobuf:"varint,2,opt,name=message_index,json=messageIndex,proto3" json:"message_index,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	TimestampUnix int64                  `protobuf:"varint,4,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	Snippet       string                 `protobuf:"bytes,5,opt,name=snippet,proto3" json:"snippet,omitempty"`
	// score is the engine's retrieval relevance; zero on literal-scan matches.
	Score float64 `protobuf:"fixed64,6,opt,name=score,proto3" json:"score,omitempty"`
	// context_window is the rendered messages surrounding this hit, so the caller
	// rarely needs a second read call.
	ContextWindow string `protobuf:"bytes,7,opt,name=context_window,json=contextWindow,proto3" json:"context_window,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationSearchMatch) Reset() {
	*x = ConversationSearchMatch{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationSearchMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationSearchMatch) ProtoMessage() {}

func (x *ConversationSearchMatch) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationSearchMatch.ProtoReflect.Descriptor instead.
func (*ConversationSearchMatch) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{15}
}

func (x *ConversationSearchMatch) GetConversation() *ConversationRecord {
	if x != nil {
		return x.Conversation
	}
	return nil
}

func (x *ConversationSearchMatch) GetMessageIndex() int64 {
	if x != nil {
		return x.MessageIndex
	}
	return 0
}

func (x *ConversationSearchMatch) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ConversationSearchMatch) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

func (x *ConversationSearchMatch) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

func (x *ConversationSearchMatch) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ConversationSearchMatch) GetContextWindow() string {
	if x != nil {
		return x.ContextWindow
	}
	return ""
}

// SearchFacetCount is one facet value and how many matched conversations carry
// it.
type SearchFacetCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchFacetCount) Reset() {
	*x = SearchFacetCount{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchFacetCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFacetCount) ProtoMessage() {}

func (x *SearchFacetCount) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFacetCount.ProtoReflect.Descriptor instead.
func (*SearchFacetCount) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{16}
}

func (x *SearchFacetCount) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SearchFacetCount) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// SearchFacets summarizes the result set by workspace, provider, and model so
// the caller can narrow without a second query.
type SearchFacets struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspaces    []*SearchFacetCount    `protobuf:"bytes,1,rep,name=workspaces,proto3" json:"workspaces,omitempty"`
	Providers     []*SearchFacetCount    `protobuf:"bytes,2,rep,name=providers,proto3" json:"providers,omitempty"`
	Models        []*SearchFacetCount    `protobuf:"bytes,3,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchFacets) Reset() {
	*x = SearchFacets{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchFacets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFacets) ProtoMessage() {}

func (x *SearchFacets) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFacets.ProtoReflect.Descriptor instead.
func (*SearchFacets) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{17}
}

func (x *SearchFacets) GetWorkspaces() []*SearchFacetCount {
	if x != nil {
		return x.Workspaces
	}
	return nil
}

func (x *SearchFacets) GetProviders() []*SearchFacetCount {
	if x != nil {
		return x.Providers
	}
	return nil
}

func (x *SearchFacets) GetModels() []*SearchFacetCount {
	if x != nil {
		return x.Models
	}
	return nil
}

// SearchFreshness is the conversation-index sync state at query time, so the
// caller can tell whether a thin result means a cold index versus a true miss.
type SearchFreshness struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifest      int64                  `protobuf:"varint,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	Needed        int64                  `protobuf:"varint,2,opt,name=needed,proto3" json:"needed,omitempty"`
	Embedded      int64                  `protobuf:"varint,3,opt,name=embedded,proto3" json:"embedded,omitempty"`
	Pending       int64                  `protobuf:"varint,4,opt,name=pending,proto3" json:"pending,omitempty"`
	LastSyncUnix  int64                  `protobuf:"varint,5,opt,name=last_sync_unix,json=lastSyncUnix,proto3" json:"last_sync_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchFreshness) Reset() {
	*x = SearchFreshness{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchFreshness) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFreshness) ProtoMessage() {}

func (x *SearchFreshness) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFreshness.ProtoReflect.Descriptor instead.
func (*SearchFreshness) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{18}
}

func (x *SearchFreshness) GetManifest() int64 {
	if x != nil {
		return x.Manifest
	}
	return 0
}

func (x *SearchFreshness) GetNeeded() int64 {
	if x != nil {
		return x.Needed
	}
	return 0
}

func (x *SearchFreshness) GetEmbedded() int64 {
	if x != nil {
		return x.Embedded
	}
	return 0
}

func (x *SearchFreshness) GetPending() int64 {
	if x != nil {
		return x.Pending
	}
	return 0
}

func (x *SearchFreshness) GetLastSyncUnix() int64 {
	if x != nil {
		return x.LastSyncUnix
	}
	return 0
}

// FilterStage records how many candidate conversations remained after one
// filter was applied, so a legitimately narrow result shows its funnel.
type FilterStage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Remaining     int64                  `protobuf:"varint,2,opt,name=remaining,proto3" json:"remaining,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterStage) Reset() {
	*x = FilterStage{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterStage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterStage) ProtoMessage() {}

func (x *FilterStage) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterStage.ProtoReflect.Descriptor instead.
func (*FilterStage) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{19}
}

func (x *FilterStage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FilterStage) GetRemaining() int64 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

// FilterAccounting is the ordered funnel of filter stages for the query.
type FilterAccounting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stages        []*FilterStage         `protobuf:"bytes,1,rep,name=stages,proto3" json:"stages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterAccounting) Reset() {
	*x = FilterAccounting{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterAccounting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterAccounting) ProtoMessage() {}

func (x *FilterAccounting) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterAccounting.ProtoReflect.Descriptor instead.
func (*FilterAccounting) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{20}
}

func (x *FilterAccounting) GetStages() []*FilterStage {
	if x != nil {
		return x.Stages
	}
	return nil
}

type SearchConversationsResponse struct {
	state                protoimpl.MessageState     `protogen:"open.v1"`
	Matches              []*ConversationSearchMatch `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	ConversationsScanned int64                      `protobuf:"varint,2,opt,name=conversations_scanned,json=conversationsScanned,proto3" json:"conversations_scanned,omitempty"`
	ReturnedCount        int64                      `protobuf:"varint,3,opt,name=returned_count,json=returnedCount,proto3" json:"returned_count,omitempty"`
	Limit                int64                      `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	HasMore              bool                       `protobuf:"varint,5,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	Source               SearchSource               `protobuf:"varint,6,opt,name=source,proto3,enum=clyde.v1.SearchSource" json:"source,omitempty"`
	Facets               *SearchFacets              `protobuf:"bytes,7,opt,name=facets,proto3" json:"facets,omitempty"`
	Freshness            *SearchFreshness           `protobuf:"bytes,8,opt,name=freshness,proto3" json:"freshness,omitempty"`
	FilterAccounting     *FilterAccounting          `protobuf:"bytes,9,opt,name=filter_accounting,json=filterAccounting,proto3" json:"filter_accounting,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SearchConversationsResponse) Reset() {
	*x = SearchConversationsResponse{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchConversationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchConversationsResponse) ProtoMessage() {}

func (x *SearchConversationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchConversationsResponse.ProtoReflect.Descriptor instead.
func (*SearchConversationsResponse) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{21}
}

func (x *SearchConversationsResponse) GetMatches() []*ConversationSearchMatch {
	if x != nil {
		return x.Matches
	}
	return nil
}

func (x *SearchConversationsResponse) GetConversationsScanned() int64 {
	if x != nil {
		return x.ConversationsScanned
	}
	return 0
}

func (x *SearchConversationsResponse) GetReturnedCount() int64 {
	if x != nil {
		return x.ReturnedCount
	}
	return 0
}

func (x *SearchConversationsResponse) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchConversationsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *SearchConversationsResponse) GetSource() SearchSource {
	if x != nil {
		return x.Source
	}
	return SearchSource_SEARCH_SOURCE_UNSPECIFIED
}

func (x *SearchConversationsResponse) GetFacets() *SearchFacets {
	if x != nil {
		return x.Facets
	}
	return nil
}

func (x *SearchConversationsResponse) GetFreshness() *SearchFreshness {
	if x != nil {
		return x.Freshness
	}
	return nil
}

func (x *SearchConversationsResponse) GetFilterAccounting() *FilterAccounting {
	if x != nil {
		return x.FilterAccounting
	}
	return nil
}

type ExportTranscriptRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ConversationId         string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Format                 string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	Whitespace             string                 `protobuf:"bytes,3,opt,name=whitespace,proto3" json:"whitespace,omitempty"`
	HistoryStart           int64                  `protobuf:"varint,4,opt,name=history_start,json=historyStart,proto3" json:"history_start,omitempty"`
	IncludeSystemPrompts   bool                   `protobuf:"varint,5,opt,name=include_system_prompts,json=includeSystemPrompts,proto3" json:"include_system_prompts,omitempty"`
	IncludeToolOutputs     bool                   `protobuf:"varint,6,opt,name=include_tool_outputs,json=includeToolOutputs,proto3" json:"include_tool_outputs,omitempty"`
	IncludeRawJsonMetadata bool                   `protobuf:"varint,7,opt,name=include_raw_json_metadata,json=includeRawJsonMetadata,proto3" json:"include_raw_json_metadata,omitempty"`
	IncludeThinking        bool                   `protobuf:"varint,8,opt,name=include_thinking,json=includeThinking,proto3" json:"include_thinking,omitempty"`
	IncludeToolCalls       bool                   `protobuf:"varint,9,opt,name=include_tool_calls,json=includeToolCalls,proto3" json:"include_tool_calls,omitempty"`
	IncludeChat            bool                   `protobuf:"varint,10,opt,name=include_chat,json=includeChat,proto3" json:"include_chat,omitempty"`
	IncludeSystemMessages  bool                   `protobuf:"varint,11,opt,name=include_system_messages,json=includeSystemMessages,proto3" json:"include_system_messages,omitempty"`
	CompactionScope        string                 `protobuf:"bytes,12,opt,name=compaction_scope,json=compactionScope,proto3" json:"compaction_scope,omitempty"`
	CompactionDetail       string                 `protobuf:"bytes,13,opt,name=compaction_detail,json=compactionDetail,proto3" json:"compaction_detail,omitempty"`
	CompactionCheckpoint   int64                  `protobuf:"varint,14,opt,name=compaction_checkpoint,json=compactionCheckpoint,proto3" json:"compaction_checkpoint,omitempty"`
	IncludeToolSummaries   bool                   `protobuf:"varint,15,opt,name=include_tool_summaries,json=includeToolSummaries,proto3" json:"include_tool_summaries,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ExportTranscriptRequest) Reset() {
	*x = ExportTranscriptRequest{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportTranscriptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportTranscriptRequest) ProtoMessage() {}

func (x *ExportTranscriptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportTranscriptRequest.ProtoReflect.Descriptor instead.
func (*ExportTranscriptRequest) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{22}
}

func (x *ExportTranscriptRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ExportTranscriptRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ExportTranscriptRequest) GetWhitespace() string {
	if x != nil {
		return x.Whitespace
	}
	return ""
}

func (x *ExportTranscriptRequest) GetHistoryStart() int64 {
	if x != nil {
		return x.HistoryStart
	}
	return 0
}

func (x *ExportTranscriptRequest) GetIncludeSystemPrompts() bool {
	if x != nil {
		return x.IncludeSystemPrompts
	}
	return false
}

func (x *ExportTranscriptRequest) GetIncludeToolOutputs() bool {
	if x != nil {
		return x.IncludeToolOutputs
	}
	return false
}

func (x *ExportTranscriptRequest) GetIncludeRawJsonMetadata() bool {
	if x != nil {
		return x.IncludeRawJsonMetadata
	}
	return false
}

func (x *ExportTranscriptRequest) GetIncludeThinking() bool {
	if x != nil {
		return x.IncludeThinking
	}
	return false
}

func (x *ExportTranscriptRequest) GetIncludeToolCalls() bool {
	if x != nil {
		return x.IncludeToolCalls
	}
	return false
}

func (x *ExportTranscriptRequest) GetIncludeChat() bool {
	if x != nil {
		return x.IncludeChat
	}
	return false
}

func (x *ExportTranscriptRequest) GetIncludeSystemMessages() bool {
	if x != nil {
		return x.IncludeSystemMessages
	}
	return false
}

func (x *ExportTranscriptRequest) GetCompactionScope() string {
	if x != nil {
		return x.CompactionScope
	}
	return ""
}

func (x *ExportTranscriptRequest) GetCompactionDetail() string {
	if x != nil {
		return x.CompactionDetail
	}
	return ""
}

func (x *ExportTranscriptRequest) GetCompactionCheckpoint() int64 {
	if x != nil {
		return x.CompactionCheckpoint
	}
	return 0
}

func (x *ExportTranscriptRequest) GetIncludeToolSummaries() bool {
	if x != nil {
		return x.IncludeToolSummaries
	}
	return false
}

type ConversationLineage struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Kind              string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	ParentProvider    Provider               `protobuf:"varint,2,opt,name=parent_provider,json=parentProvider,proto3,enum=clyde.v1.Provider" json:"parent_provider,omitempty"`
	ParentNativeId    string                 `protobuf:"bytes,3,opt,name=parent_native_id,json=parentNativeId,proto3" json:"parent_native_id,omitempty"`
	ParentMessageUuid string                 `protobuf:"bytes,4,opt,name=parent_message_uuid,json=parentMessageUuid,proto3" json:"parent_message_uuid,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ConversationLineage) Reset() {
	*x = ConversationLineage{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationLineage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationLineage) ProtoMessage() {}

func (x *ConversationLineage) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationLineage.ProtoReflect.Descriptor instead.
func (*ConversationLineage) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{23}
}

func (x *ConversationLineage) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ConversationLineage) GetParentProvider() Provider {
	if x != nil {
		return x.ParentProvider
	}
	return Provider_PROVIDER_UNSPECIFIED
}

func (x *ConversationLineage) GetParentNativeId() string {
	if x != nil {
		return x.ParentNativeId
	}
	return ""
}

func (x *ConversationLineage) GetParentMessageUuid() string {
	if x != nil {
		return x.ParentMessageUuid
	}
	return ""
}

type ConversationRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Provider      Provider               `protobuf:"varint,2,opt,name=provider,proto3,enum=clyde.v1.Provider" json:"provider,omitempty"`
	NativeId      string                 `protobuf:"bytes,3,opt,name=native_id,json=nativeId,proto3" json:"native_id,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	WorkspaceRoot string                 `protobuf:"bytes,5,opt,name=workspace_root,json=workspaceRoot,proto3" json:"workspace_root,omitempty"`
	ArtifactPath  string                 `protobuf:"bytes,6,opt,name=artifact_path,json=artifactPath,proto3" json:"artifact_path,omitempty"`
	ArtifactKind  string                 `protobuf:"bytes,7,opt,name=artifact_kind,json=artifactKind,proto3" json:"artifact_kind,omitempty"`
	Model         string                 `protobuf:"bytes,8,opt,name=model,proto3" json:"model,omitempty"`
	CreatedAtUnix int64                  `protobuf:"varint,9,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	UpdatedAtUnix int64                  `protobuf:"varint,10,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,11,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Archived      bool                   `protobuf:"varint,12,opt,name=archived,proto3" json:"archived,omitempty"`
	Lineage       *ConversationLineage   `protobuf:"bytes,13,opt,name=lineage,proto3" json:"lineage,omitempty"`
	// parent_conversation_id is the resolved derived id of this conversation's
	// fork parent when that parent is present in the index, and empty otherwise.
	ParentConversationId string `protobuf:"bytes,14,opt,name=parent_conversation_id,json=parentConversationId,proto3" json:"parent_conversation_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ConversationRecord) Reset() {
	*x = ConversationRecord{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationRecord) ProtoMessage() {}

func (x *ConversationRecord) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationRecord.ProtoReflect.Descriptor instead.
func (*ConversationRecord) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{24}
}

func (x *ConversationRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConversationRecord) GetProvider() Provider {
	if x != nil {
		return x.Provider
	}
	return Provider_PROVIDER_UNSPECIFIED
}

func (x *ConversationRecord) GetNativeId() string {
	if x != nil {
		return x.NativeId
	}
	return ""
}

func (x *ConversationRecord) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ConversationRecord) GetWorkspaceRoot() string {
	if x != nil {
		return x.WorkspaceRoot
	}
	return ""
}

func (x *ConversationRecord) GetArtifactPath() string {
	if x != nil {
		return x.ArtifactPath
	}
	return ""
}

func (x *ConversationRecord) GetArtifactKind() string {
	if x != nil {
		return x.ArtifactKind
	}
	return ""
}

func (x *ConversationRecord) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ConversationRecord) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *ConversationRecord) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

func (x *ConversationRecord) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ConversationRecord) GetArchived() bool {
	if x != nil {
		return x.Archived
	}
	return false
}

func (x *ConversationRecord) GetLineage() *ConversationLineage {
	if x != nil {
		return x.Lineage
	}
	return nil
}

func (x *ConversationRecord) GetParentConversationId() string {
	if x != nil {
		return x.ParentConversationId
	}
	return ""
}

type ListConversationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conversations []*ConversationRecord  `protobuf:"bytes,1,rep,name=conversations,proto3" json:"conversations,omitempty"`
	TotalMatched  int64                  `protobuf:"varint,2,opt,name=total_matched,json=totalMatched,proto3" json:"total_matched,omitempty"`
	ReturnedCount int64                  `protobuf:"varint,3,opt,name=returned_count,json=returnedCount,proto3" json:"returned_count,omitempty"`
	Offset        int64                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int64                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	NextOffset    int64                  `protobuf:"varint,6,opt,name=next_offset,json=nextOffset,proto3" json:"next_offset,omitempty"`
	HasMore       bool                   `protobuf:"varint,7,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversationsResponse) Reset() {
	*x = ListConversationsResponse{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsResponse) ProtoMessage() {}

func (x *ListConversationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsResponse.ProtoReflect.Descriptor instead.
func (*ListConversationsResponse) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{25}
}

func (x *ListConversationsResponse) GetConversations() []*ConversationRecord {
	if x != nil {
		return x.Conversations
	}
	return nil
}

func (x *ListConversationsResponse) GetTotalMatched() int64 {
	if x != nil {
		return x.TotalMatched
	}
	return 0
}

func (x *ListConversationsResponse) GetReturnedCount() int64 {
	if x != nil {
		return x.ReturnedCount
	}
	return 0
}

func (x *ListConversationsResponse) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListConversationsResponse) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListConversationsResponse) GetNextOffset() int64 {
	if x != nil {
		return x.NextOffset
	}
	return 0
}

func (x *ListConversationsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

var File_clyde_v1_daemon_service_proto protoreflect.FileDescriptor

const file_clyde_v1_daemon_service_proto_rawDesc = "" +
	"\n" +
	"\x1dclyde/v1/daemon/service.proto\x12\bclyde.v1\x1a\x1eclyde/v1/daemon/provider.proto\"\x8b\x01\n" +
	"\x14LogsInventoryRequest\x12\x1d\n" +
	"\n" +
	"state_root\x18\x01 \x01(\tR\tstateRoot\x12,\n" +
	"\x12largest_file_limit\x18\x02 \x01(\x03R\x10largestFileLimit\x12\x12\n" +
	"\x04deep\x18\x03 \x01(\bR\x04deep\x12\x12\n" +
	"\x04json\x18\x04 \x01(\bR\x04json\"/\n" +
	"\x15LogsInventoryResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\"\x9b\x01\n" +
	"\x13SeedBaselineRequest\x12\x1a\n" +
	"\bupstream\x18\x01 \x01(\tR\bupstream\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\x12\x1d\n" +
	"\n" +
	"include_ua\x18\x04 \x03(\tR\tincludeUa\x12\x1d\n" +
	"\n" +
	"exclude_ua\x18\x05 \x03(\tR\texcludeUa\"f\n" +
	"\x14SeedBaselineResponse\x12\x18\n" +
	"\awritten\x18\x01 \x01(\tR\awritten\x12\x1a\n" +
	"\bupstream\x18\x02 \x01(\tR\bupstream\x12\x18\n" +
	"\aflavors\x18\x03 \x01(\x03R\aflavors\"8\n" +
	"\x12ShowCaptureRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04json\x18\x02 \x01(\bR\x04json\"-\n" +
	"\x13ShowCaptureResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\"\x16\n" +
	"\x14GetMITMStatusRequest\"N\n" +
	"\x12MITMListenerStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x0e\n" +
	"\x02up\x18\x03 \x01(\bR\x02up\"\x95\x01\n" +
	"\x15GetMITMStatusResponse\x12:\n" +
	"\tlisteners\x18\x01 \x03(\v2\x1c.clyde.v1.MITMListenerStatusR\tlisteners\x12 \n" +
	"\fca_cert_path\x18\x02 \x01(\tR\n" +
	"caCertPath\x12\x1e\n" +
	"\vca_key_path\x18\x03 \x01(\tR\tcaKeyPath\"\xe9\x01\n" +
	"\x18ListConversationsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12.\n" +
	"\bprovider\x18\x03 \x01(\x0e2\x12.clyde.v1.ProviderR\bprovider\x12\x1c\n" +
	"\tworkspace\x18\x04 \x01(\tR\tworkspace\x12\x14\n" +
	"\x05query\x18\x05 \x01(\tR\x05query\x12)\n" +
	"\x10include_archived\x18\x06 \x01(\bR\x0fincludeArchived\x12\x10\n" +
	"\x03all\x18\a \x01(\bR\x03all\"X\n" +
	"\x16GetConversationRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x15\n" +
	"\x06last_n\x18\x02 \x01(\x03R\x05lastN\"'\n" +
	"\x11ConversationChunk\x12\x12\n" +
	"\x04text\x18\x01 \x01(\fR\x04text\"!\n" +
	"\vExportChunk\x12\x12\n" +
	"\x04body\x18\x01 \x01(\fR\x04body\"\xb9\x01\n" +
	"\x1dGetConversationContextRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x12#\n" +
	"\rmessage_index\x18\x03 \x01(\x03R\fmessageIndex\x12\x16\n" +
	"\x06before\x18\x04 \x01(\x03R\x06before\x12\x14\n" +
	"\x05after\x18\x05 \x01(\x03R\x05after\"\xb6\x03\n" +
	"\x1aSearchConversationsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12.\n" +
	"\bprovider\x18\x03 \x01(\x0e2\x12.clyde.v1.ProviderR\bprovider\x12\x1c\n" +
	"\tworkspace\x18\x04 \x01(\tR\tworkspace\x12)\n" +
	"\x10include_archived\x18\x05 \x01(\bR\x0fincludeArchived\x12\x14\n" +
	"\x05roles\x18\x06 \x03(\tR\x05roles\x12\x1b\n" +
	"\tfrom_unix\x18\a \x01(\x03R\bfromUnix\x12\x1d\n" +
	"\n" +
	"until_unix\x18\b \x01(\x03R\tuntilUnix\x12\x1b\n" +
	"\tmin_score\x18\t \x01(\x01R\bminScore\x124\n" +
	"\x16per_conversation_limit\x18\n" +
	" \x01(\x03R\x14perConversationLimit\x12'\n" +
	"\x0fconversation_id\x18\v \x01(\tR\x0econversationId\x12%\n" +
	"\x0econtext_window\x18\f \x01(\x03R\rcontextWindow\"\x92\x02\n" +
	"\x17ConversationSearchMatch\x12@\n" +
	"\fconversation\x18\x01 \x01(\v2\x1c.clyde.v1.ConversationRecordR\fconversation\x12#\n" +
	"\rmessage_index\x18\x02 \x01(\x03R\fmessageIndex\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12%\n" +
	"\x0etimestamp_unix\x18\x04 \x01(\x03R\rtimestampUnix\x12\x18\n" +
	"\asnippet\x18\x05 \x01(\tR\asnippet\x12\x14\n" +
	"\x05score\x18\x06 \x01(\x01R\x05score\x12%\n" +
	"\x0econtext_window\x18\a \x01(\tR\rcontextWindow\">\n" +
	"\x10SearchFacetCount\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"\xb8\x01\n" +
	"\fSearchFacets\x12:\n" +
	"\n" +
	"workspaces\x18\x01 \x03(\v2\x1a.clyde.v1.SearchFacetCountR\n" +
	"workspaces\x128\n" +
	"\tproviders\x18\x02 \x03(\v2\x1a.clyde.v1.SearchFacetCountR\tproviders\x122\n" +
	"\x06models\x18\x03 \x03(\v2\x1a.clyde.v1.SearchFacetCountR\x06models\"\xa1\x01\n" +
	"\x0fSearchFreshness\x12\x1a\n" +
	"\bmanifest\x18\x01 \x01(\x03R\bmanifest\x12\x16\n" +
	"\x06needed\x18\x02 \x01(\x03R\x06needed\x12\x1a\n" +
	"\bembedded\x18\x03 \x01(\x03R\bembedded\x12\x18\n" +
	"\apending\x18\x04 \x01(\x03R\apending\x12$\n" +
	"\x0elast_sync_unix\x18\x05 \x01(\x03R\flastSyncUnix\"?\n" +
	"\vFilterStage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tremaining\x18\x02 \x01(\x03R\tremaining\"A\n" +
	"\x10FilterAccounting\x12-\n" +
	"\x06stages\x18\x01 \x03(\v2\x15.clyde.v1.FilterStageR\x06stages\"\xc9\x03\n" +
	"\x1bSearchConversationsResponse\x12;\n" +
	"\amatches\x18\x01 \x03(\v2!.clyde.v1.ConversationSearchMatchR\amatches\x123\n" +
	"\x15conversations_scanned\x18\x02 \x01(\x03R\x14conversationsScanned\x12%\n" +
	"\x0ereturned_count\x18\x03 \x01(\x03R\rreturnedCount\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x03R\x05limit\x12\x19\n" +
	"\bhas_more\x18\x05 \x01(\bR\ahasMore\x12.\n" +
	"\x06source\x18\x06 \x01(\x0e2\x16.clyde.v1.SearchSourceR\x06source\x12.\n" +
	"\x06facets\x18\a \x01(\v2\x16.clyde.v1.SearchFacetsR\x06facets\x127\n" +
	"\tfreshness\x18\b \x01(\v2\x19.clyde.v1.SearchFreshnessR\tfreshness\x12G\n" +
	"\x11filter_accounting\x18\t \x01(\v2\x1a.clyde.v1.FilterAccountingR\x10filterAccounting\"\xb9\x05\n" +
	"\x17ExportTranscriptRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12\x1e\n" +
	"\n" +
	"whitespace\x18\x03 \x01(\tR\n" +
	"whitespace\x12#\n" +
	"\rhistory_start\x18\x04 \x01(\x03R\fhistoryStart\x124\n" +
	"\x16include_system_prompts\x18\x05 \x01(\bR\x14includeSystemPrompts\x120\n" +
	"\x14include_tool_outputs\x18\x06 \x01(\bR\x12includeToolOutputs\x129\n" +
	"\x19include_raw_json_metadata\x18\a \x01(\bR\x16includeRawJsonMetadata\x12)\n" +
	"\x10include_thinking\x18\b \x01(\bR\x0fincludeThinking\x12,\n" +
	"\x12include_tool_calls\x18\t \x01(\bR\x10includeToolCalls\x12!\n" +
	"\finclude_chat\x18\n" +
	" \x01(\bR\vincludeChat\x126\n" +
	"\x17include_system_messages\x18\v \x01(\bR\x15includeSystemMessages\x12)\n" +
	"\x10compaction_scope\x18\f \x01(\tR\x0fcompactionScope\x12+\n" +
	"\x11compaction_detail\x18\r \x01(\tR\x10compactionDetail\x123\n" +
	"\x15compaction_checkpoint\x18\x0e \x01(\x03R\x14compactionCheckpoint\x124\n" +
	"\x16include_tool_summaries\x18\x0f \x01(\bR\x14includeToolSummaries\"\xc0\x01\n" +
	"\x13ConversationLineage\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12;\n" +
	"\x0fparent_provider\x18\x02 \x01(\x0e2\x12.clyde.v1.ProviderR\x0eparentProvider\x12(\n" +
	"\x10parent_native_id\x18\x03 \x01(\tR\x0eparentNativeId\x12.\n" +
	"\x13parent_message_uuid\x18\x04 \x01(\tR\x11parentMessageUuid\"\x88\x04\n" +
	"\x12ConversationRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\bprovider\x18\x02 \x01(\x0e2\x12.clyde.v1.ProviderR\bprovider\x12\x1b\n" +
	"\tnative_id\x18\x03 \x01(\tR\bnativeId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12%\n" +
	"\x0eworkspace_root\x18\x05 \x01(\tR\rworkspaceRoot\x12#\n" +
	"\rartifact_path\x18\x06 \x01(\tR\fartifactPath\x12#\n" +
	"\rartifact_kind\x18\a \x01(\tR\fartifactKind\x12\x14\n" +
	"\x05model\x18\b \x01(\tR\x05model\x12&\n" +
	"\x0fcreated_at_unix\x18\t \x01(\x03R\rcreatedAtUnix\x12&\n" +
	"\x0fupdated_at_unix\x18\n" +
	" \x01(\x03R\rupdatedAtUnix\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\v \x01(\x03R\tsizeBytes\x12\x1a\n" +
	"\barchived\x18\f \x01(\bR\barchived\x127\n" +
	"\alineage\x18\r \x01(\v2\x1d.clyde.v1.ConversationLineageR\alineage\x124\n" +
	"\x16parent_conversation_id\x18\x0e \x01(\tR\x14parentConversationId\"\x95\x02\n" +
	"\x19ListConversationsResponse\x12B\n" +
	"\rconversations\x18\x01 \x03(\v2\x1c.clyde.v1.ConversationRecordR\rconversations\x12#\n" +
	"\rtotal_matched\x18\x02 \x01(\x03R\ftotalMatched\x12%\n" +
	"\x0ereturned_count\x18\x03 \x01(\x03R\rreturnedCount\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x03R\x05limit\x12\x1f\n" +
	"\vnext_offset\x18\x06 \x01(\x03R\n" +
	"nextOffset\x12\x19\n" +
	"\bhas_more\x18\a \x01(\bR\ahasMore*\x8d\x01\n" +
	"\fSearchSource\x12\x1d\n" +
	"\x19SEARCH_SOURCE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16SEARCH_SOURCE_SEMANTIC\x10\x01\x12\x19\n" +
	"\x15SEARCH_SOURCE_LITERAL\x10\x02\x12'\n" +
	"#SEARCH_SOURCE_LITERAL_DISABLED_COLD\x10\x032\xfd\b\n" +
	"\fClydeService\x12M\n" +
	"\fReloadDaemon\x12\x1d.clyde.v1.ReloadDaemonRequest\x1a\x1e.clyde.v1.ReloadDaemonResponse\x12M\n" +
	"\fRebindDaemon\x12\x1d.clyde.v1.ReloadDaemonRequest\x1a\x1e.clyde.v1.ReloadDaemonResponse\x12Y\n" +
	"\x10GetProviderStats\x12!.clyde.v1.GetProviderStatsRequest\x1a\".clyde.v1.GetProviderStatsResponse\x12a\n" +
	"\x16SubscribeProviderStats\x12'.clyde.v1.SubscribeProviderStatsRequest\x1a\x1c.clyde.v1.ProviderStatsEvent0\x01\x12\\\n" +
	"\x11ListConversations\x12\".clyde.v1.ListConversationsRequest\x1a#.clyde.v1.ListConversationsResponse\x12b\n" +
	"\x13SearchConversations\x12$.clyde.v1.SearchConversationsRequest\x1a%.clyde.v1.SearchConversationsResponse\x12U\n" +
	"\x12StreamConversation\x12 .clyde.v1.GetConversationRequest\x1a\x1b.clyde.v1.ConversationChunk0\x01\x12c\n" +
	"\x19StreamConversationContext\x12'.clyde.v1.GetConversationContextRequest\x1a\x1b.clyde.v1.ConversationChunk0\x01\x12T\n" +
	"\x16StreamExportTranscript\x12!.clyde.v1.ExportTranscriptRequest\x1a\x15.clyde.v1.ExportChunk0\x01\x12P\n" +
	"\rGetMITMStatus\x12\x1e.clyde.v1.GetMITMStatusRequest\x1a\x1f.clyde.v1.GetMITMStatusResponse\x12J\n" +
	"\vShowCapture\x12\x1c.clyde.v1.ShowCaptureRequest\x1a\x1d.clyde.v1.ShowCaptureResponse\x12M\n" +
	"\fSeedBaseline\x12\x1d.clyde.v1.SeedBaselineRequest\x1a\x1e.clyde.v1.SeedBaselineResponse\x12P\n" +
	"\rLogsInventory\x12\x1e.clyde.v1.LogsInventoryRequest\x1a\x1f.clyde.v1.LogsInventoryResponseB(Z&goodkind.io/clyde/api/clyde/v1;clydev1b\x06proto3"

var (
	file_clyde_v1_daemon_service_proto_rawDescOnce sync.Once
	file_clyde_v1_daemon_service_proto_rawDescData []byte
)

func file_clyde_v1_daemon_service_proto_rawDescGZIP() []byte {
	file_clyde_v1_daemon_service_proto_rawDescOnce.Do(func() {
		file_clyde_v1_daemon_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clyde_v1_daemon_service_proto_rawDesc), len(file_clyde_v1_daemon_service_proto_rawDesc)))
	})
	return file_clyde_v1_daemon_service_proto_rawDescData
}

var file_clyde_v1_daemon_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_clyde_v1_daemon_service_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_clyde_v1_daemon_service_proto_goTypes = []any{
	(SearchSource)(0),                     // 0: clyde.v1.SearchSource
	(*LogsInventoryRequest)(nil),          // 1: clyde.v1.LogsInventoryRequest
	(*LogsInventoryResponse)(nil),         // 2: clyde.v1.LogsInventoryResponse
	(*SeedBaselineRequest)(nil),           // 3: clyde.v1.SeedBaselineRequest
	(*SeedBaselineResponse)(nil),          // 4: clyde.v1.SeedBaselineResponse
	(*ShowCaptureRequest)(nil),            // 5: clyde.v1.ShowCaptureRequest
	(*ShowCaptureResponse)(nil),           // 6: clyde.v1.ShowCaptureResponse
	(*GetMITMStatusRequest)(nil),          // 7: clyde.v1.GetMITMStatusRequest
	(*MITMListenerStatus)(nil),            // 8: clyde.v1.MITMListenerStatus
	(*GetMITMStatusResponse)(nil),         // 9: clyde.v1.GetMITMStatusResponse
	(*ListConversationsRequest)(nil),      // 10: clyde.v1.ListConversationsRequest
	(*GetConversationRequest)(nil),        // 11: clyde.v1.GetConversationRequest
	(*ConversationChunk)(nil),             // 12: clyde.v1.ConversationChunk
	(*ExportChunk)(nil),                   // 13: clyde.v1.ExportChunk
	(*GetConversationContextRequest)(nil), // 14: clyde.v1.GetConversationContextRequest
	(*SearchConversationsRequest)(nil),    // 15: clyde.v1.SearchConversationsRequest
	(*ConversationSearchMatch)(nil),       // 16: clyde.v1.ConversationSearchMatch
	(*SearchFacetCount)(nil),              // 17: clyde.v1.SearchFacetCount
	(*SearchFacets)(nil),                  // 18: clyde.v1.SearchFacets
	(*SearchFreshness)(nil),               // 19: clyde.v1.SearchFreshness
	(*FilterStage)(nil),                   // 20: clyde.v1.FilterStage
	(*FilterAccounting)(nil),              // 21: clyde.v1.FilterAccounting
	(*SearchConversationsResponse)(nil),   // 22: clyde.v1.SearchConversationsResponse
	(*ExportTranscriptRequest)(nil),       // 23: clyde.v1.ExportTranscriptRequest
	(*ConversationLineage)(nil),           // 24: clyde.v1.ConversationLineage
	(*ConversationRecord)(nil),            // 25: clyde.v1.ConversationRecord
	(*ListConversationsResponse)(nil),     // 26: clyde.v1.ListConversationsResponse
	(Provider)(0),                         // 27: clyde.v1.Provider
	(*ReloadDaemonRequest)(nil),           // 28: clyde.v1.ReloadDaemonRequest
	(*GetProviderStatsRequest)(nil),       // 29: clyde.v1.GetProviderStatsRequest
	(*SubscribeProviderStatsRequest)(nil), // 30: clyde.v1.SubscribeProviderStatsRequest
	(*ReloadDaemonResponse)(nil),          // 31: clyde.v1.ReloadDaemonResponse
	(*GetProviderStatsResponse)(nil),      // 32: clyde.v1.GetProviderStatsResponse
	(*ProviderStatsEvent)(nil),            // 33: clyde.v1.ProviderStatsEvent
}
var file_clyde_v1_daemon_service_proto_depIdxs = []int32{
	8,  // 0: clyde.v1.GetMITMStatusResponse.listeners:type_name -> clyde.v1.MITMListenerStatus
	27, // 1: clyde.v1.ListConversationsRequest.provider:type_name -> clyde.v1.Provider
	27, // 2: clyde.v1.SearchConversationsRequest.provider:type_name -> clyde.v1.Provider
	25, // 3: clyde.v1.ConversationSearchMatch.conversation:type_name -> clyde.v1.ConversationRecord
	17, // 4: clyde.v1.SearchFacets.workspaces:type_name -> clyde.v1.SearchFacetCount
	17, // 5: clyde.v1.SearchFacets.providers:type_name -> clyde.v1.SearchFacetCount
	17, // 6: clyde.v1.SearchFacets.models:type_name -> clyde.v1.SearchFacetCount
	20, // 7: clyde.v1.FilterAccounting.stages:type_name -> clyde.v1.FilterStage
	16, // 8: clyde.v1.SearchConversationsResponse.matches:type_name -> clyde.v1.ConversationSearchMatch
	0,  // 9: clyde.v1.SearchConversationsResponse.source:type_name -> clyde.v1.SearchSource
	18, // 10: clyde.v1.SearchConversationsResponse.facets:type_name -> clyde.v1.SearchFacets
	19, // 11: clyde.v1.SearchConversationsResponse.freshness:type_name -> clyde.v1.SearchFreshness
	21, // 12: clyde.v1.SearchConversationsResponse.filter_accounting:type_name -> clyde.v1.FilterAccounting
	27, // 13: clyde.v1.ConversationLineage.parent_provider:type_name -> clyde.v1.Provider
	27, // 14: clyde.v1.ConversationRecord.provider:type_name -> clyde.v1.Provider
	24, // 15: clyde.v1.ConversationRecord.lineage:type_name -> clyde.v1.ConversationLineage
	25, // 16: clyde.v1.ListConversationsResponse.conversations:type_name -> clyde.v1.ConversationRecord
	28, // 17: clyde.v1.ClydeService.ReloadDaemon:input_type -> clyde.v1.ReloadDaemonRequest
	28, // 18: clyde.v1.ClydeService.RebindDaemon:input_type -> clyde.v1.ReloadDaemonRequest
	29, // 19: clyde.v1.ClydeService.GetProviderStats:input_type -> clyde.v1.GetProviderStatsRequest
	30, // 20: clyde.v1.ClydeService.SubscribeProviderStats:input_type -> clyde.v1.SubscribeProviderStatsRequest
	10, // 21: clyde.v1.ClydeService.ListConversations:input_type -> clyde.v1.ListConversationsRequest
	15, // 22: clyde.v1.ClydeService.SearchConversations:input_type -> clyde.v1.SearchConversationsRequest
	11, // 23: clyde.v1.ClydeService.StreamConversation:input_type -> clyde.v1.GetConversationRequest
	14, // 24: clyde.v1.ClydeService.StreamConversationContext:input_type -> clyde.v1.GetConversationContextRequest
	23, // 25: clyde.v1.ClydeService.StreamExportTranscript:input_type -> clyde.v1.ExportTranscriptRequest
	7,  // 26: clyde.v1.ClydeService.GetMITMStatus:input_type -> clyde.v1.GetMITMStatusRequest
	5,  // 27: clyde.v1.ClydeService.ShowCapture:input_type -> clyde.v1.ShowCaptureRequest
	3,  // 28: clyde.v1.ClydeService.SeedBaseline:input_type -> clyde.v1.SeedBaselineRequest
	1,  // 29: clyde.v1.ClydeService.LogsInventory:input_type -> clyde.v1.LogsInventoryRequest
	31, // 30: clyde.v1.ClydeService.ReloadDaemon:output_type -> clyde.v1.ReloadDaemonResponse
	31, // 31: clyde.v1.ClydeService.RebindDaemon:output_type -> clyde.v1.ReloadDaemonResponse
	32, // 32: clyde.v1.ClydeService.GetProviderStats:output_type -> clyde.v1.GetProviderStatsResponse
	33, // 33: clyde.v1.ClydeService.SubscribeProviderStats:output_type -> clyde.v1.ProviderStatsEvent
	26, // 34: clyde.v1.ClydeService.ListConversations:output_type -> clyde.v1.ListConversationsResponse
	22, // 35: clyde.v1.ClydeService.SearchConversations:output_type -> clyde.v1.SearchConversationsResponse
	12, // 36: clyde.v1.ClydeService.StreamConversation:output_type -> clyde.v1.ConversationChunk
	12, // 37: clyde.v1.ClydeService.StreamConversationContext:output_type -> clyde.v1.ConversationChunk
	13, // 38: clyde.v1.ClydeService.StreamExportTranscript:output_type -> clyde.v1.ExportChunk
	9,  // 39: clyde.v1.ClydeService.GetMITMStatus:output_type -> clyde.v1.GetMITMStatusResponse
	6,  // 40: clyde.v1.ClydeService.ShowCapture:output_type -> clyde.v1.ShowCaptureResponse
	4,  // 41: clyde.v1.ClydeService.SeedBaseline:output_type -> clyde.v1.SeedBaselineResponse
	2,  // 42: clyde.v1.ClydeService.LogsInventory:output_type -> clyde.v1.LogsInventoryResponse
	30, // [30:43] is the sub-list for method output_type
	17, // [17:30] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_clyde_v1_daemon_service_proto_init() }
func file_clyde_v1_daemon_service_proto_init() {
	if File_clyde_v1_daemon_service_proto != nil {
		return
	}
	file_clyde_v1_daemon_provider_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clyde_v1_daemon_service_proto_rawDesc), len(file_clyde_v1_daemon_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clyde_v1_daemon_service_proto_goTypes,
		DependencyIndexes: file_clyde_v1_daemon_service_proto_depIdxs,
		EnumInfos:         file_clyde_v1_daemon_service_proto_enumTypes,
		MessageInfos:      file_clyde_v1_daemon_service_proto_msgTypes,
	}.Build()
	File_clyde_v1_daemon_service_proto = out.File
	file_clyde_v1_daemon_service_proto_goTypes = nil
	file_clyde_v1_daemon_service_proto_depIdxs = nil
}
