// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: clyde/v1/daemon/service.proto

package clydev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SearchStatus is the lifecycle state of an async search job.
type SearchStatus int32

const (
	SearchStatus_SEARCH_STATUS_UNSPECIFIED SearchStatus = 0
	SearchStatus_SEARCH_STATUS_PENDING     SearchStatus = 1
	SearchStatus_SEARCH_STATUS_RUNNING     SearchStatus = 2
	SearchStatus_SEARCH_STATUS_COMPLETE    SearchStatus = 3
	SearchStatus_SEARCH_STATUS_FAILED      SearchStatus = 4
	SearchStatus_SEARCH_STATUS_CANCELED    SearchStatus = 5
)

// Enum value maps for SearchStatus.
var (
	SearchStatus_name = map[int32]string{
		0: "SEARCH_STATUS_UNSPECIFIED",
		1: "SEARCH_STATUS_PENDING",
		2: "SEARCH_STATUS_RUNNING",
		3: "SEARCH_STATUS_COMPLETE",
		4: "SEARCH_STATUS_FAILED",
		5: "SEARCH_STATUS_CANCELED",
	}
	SearchStatus_value = map[string]int32{
		"SEARCH_STATUS_UNSPECIFIED": 0,
		"SEARCH_STATUS_PENDING":     1,
		"SEARCH_STATUS_RUNNING":     2,
		"SEARCH_STATUS_COMPLETE":    3,
		"SEARCH_STATUS_FAILED":      4,
		"SEARCH_STATUS_CANCELED":    5,
	}
)

func (x SearchStatus) Enum() *SearchStatus {
	p := new(SearchStatus)
	*p = x
	return p
}

func (x SearchStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_clyde_v1_daemon_service_proto_enumTypes[0].Descriptor()
}

func (SearchStatus) Type() protoreflect.EnumType {
	return &file_clyde_v1_daemon_service_proto_enumTypes[0]
}

func (x SearchStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchStatus.Descriptor instead.
func (SearchStatus) EnumDescriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{0}
}

type LogsInventoryRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StateRoot        string                 `protobuf:"bytes,1,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	LargestFileLimit int64                  `protobuf:"varint,2,opt,name=largest_file_limit,json=largestFileLimit,proto3" json:"largest_file_limit,omitempty"`
	Deep             bool                   `protobuf:"varint,3,opt,name=deep,proto3" json:"deep,omitempty"`
	Json             bool                   `protobuf:"varint,4,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LogsInventoryRequest) Reset() {
	*x = LogsInventoryRequest{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsInventoryRequest) ProtoMessage() {}

func (x *LogsInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsInventoryRequest.ProtoReflect.Descriptor instead.
func (*LogsInventoryRequest) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{0}
}

func (x *LogsInventoryRequest) GetStateRoot() string {
	if x != nil {
		return x.StateRoot
	}
	return ""
}

func (x *LogsInventoryRequest) GetLargestFileLimit() int64 {
	if x != nil {
		return x.LargestFileLimit
	}
	return 0
}

func (x *LogsInventoryRequest) GetDeep() bool {
	if x != nil {
		return x.Deep
	}
	return false
}

func (x *LogsInventoryRequest) GetJson() bool {
	if x != nil {
		return x.Json
	}
	return false
}

type LogsInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsInventoryResponse) Reset() {
	*x = LogsInventoryResponse{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsInventoryResponse) ProtoMessage() {}

func (x *LogsInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsInventoryResponse.ProtoReflect.Descriptor instead.
func (*LogsInventoryResponse) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{1}
}

func (x *LogsInventoryResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type SeedBaselineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Upstream      string                 `protobuf:"bytes,1,opt,name=upstream,proto3" json:"upstream,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	Output        string                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	IncludeUa     []string               `protobuf:"bytes,4,rep,name=include_ua,json=includeUa,proto3" json:"include_ua,omitempty"`
	ExcludeUa     []string               `protobuf:"bytes,5,rep,name=exclude_ua,json=excludeUa,proto3" json:"exclude_ua,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeedBaselineRequest) Reset() {
	*x = SeedBaselineRequest{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeedBaselineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeedBaselineRequest) ProtoMessage() {}

func (x *SeedBaselineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeedBaselineRequest.ProtoReflect.Descriptor instead.
func (*SeedBaselineRequest) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{2}
}

func (x *SeedBaselineRequest) GetUpstream() string {
	if x != nil {
		return x.Upstream
	}
	return ""
}

func (x *SeedBaselineRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *SeedBaselineRequest) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *SeedBaselineRequest) GetIncludeUa() []string {
	if x != nil {
		return x.IncludeUa
	}
	return nil
}

func (x *SeedBaselineRequest) GetExcludeUa() []string {
	if x != nil {
		return x.ExcludeUa
	}
	return nil
}

type SeedBaselineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Written       string                 `protobuf:"bytes,1,opt,name=written,proto3" json:"written,omitempty"`
	Upstream      string                 `protobuf:"bytes,2,opt,name=upstream,proto3" json:"upstream,omitempty"`
	Flavors       int64                  `protobuf:"varint,3,opt,name=flavors,proto3" json:"flavors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeedBaselineResponse) Reset() {
	*x = SeedBaselineResponse{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeedBaselineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeedBaselineResponse) ProtoMessage() {}

func (x *SeedBaselineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeedBaselineResponse.ProtoReflect.Descriptor instead.
func (*SeedBaselineResponse) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{3}
}

func (x *SeedBaselineResponse) GetWritten() string {
	if x != nil {
		return x.Written
	}
	return ""
}

func (x *SeedBaselineResponse) GetUpstream() string {
	if x != nil {
		return x.Upstream
	}
	return ""
}

func (x *SeedBaselineResponse) GetFlavors() int64 {
	if x != nil {
		return x.Flavors
	}
	return 0
}

type ShowCaptureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Json          bool                   `protobuf:"varint,2,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowCaptureRequest) Reset() {
	*x = ShowCaptureRequest{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowCaptureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowCaptureRequest) ProtoMessage() {}

func (x *ShowCaptureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowCaptureRequest.ProtoReflect.Descriptor instead.
func (*ShowCaptureRequest) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{4}
}

func (x *ShowCaptureRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ShowCaptureRequest) GetJson() bool {
	if x != nil {
		return x.Json
	}
	return false
}

type ShowCaptureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowCaptureResponse) Reset() {
	*x = ShowCaptureResponse{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowCaptureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowCaptureResponse) ProtoMessage() {}

func (x *ShowCaptureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowCaptureResponse.ProtoReflect.Descriptor instead.
func (*ShowCaptureResponse) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{5}
}

func (x *ShowCaptureResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type GetMITMStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMITMStatusRequest) Reset() {
	*x = GetMITMStatusRequest{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMITMStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMITMStatusRequest) ProtoMessage() {}

func (x *GetMITMStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMITMStatusRequest.ProtoReflect.Descriptor instead.
func (*GetMITMStatusRequest) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{6}
}

type MITMListenerStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Up            bool                   `protobuf:"varint,3,opt,name=up,proto3" json:"up,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MITMListenerStatus) Reset() {
	*x = MITMListenerStatus{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MITMListenerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MITMListenerStatus) ProtoMessage() {}

func (x *MITMListenerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MITMListenerStatus.ProtoReflect.Descriptor instead.
func (*MITMListenerStatus) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{7}
}

func (x *MITMListenerStatus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MITMListenerStatus) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *MITMListenerStatus) GetUp() bool {
	if x != nil {
		return x.Up
	}
	return false
}

type GetMITMStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Listeners     []*MITMListenerStatus  `protobuf:"bytes,1,rep,name=listeners,proto3" json:"listeners,omitempty"`
	CaCertPath    string                 `protobuf:"bytes,2,opt,name=ca_cert_path,json=caCertPath,proto3" json:"ca_cert_path,omitempty"`
	CaKeyPath     string                 `protobuf:"bytes,3,opt,name=ca_key_path,json=caKeyPath,proto3" json:"ca_key_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMITMStatusResponse) Reset() {
	*x = GetMITMStatusResponse{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMITMStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMITMStatusResponse) ProtoMessage() {}

func (x *GetMITMStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMITMStatusResponse.ProtoReflect.Descriptor instead.
func (*GetMITMStatusResponse) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetMITMStatusResponse) GetListeners() []*MITMListenerStatus {
	if x != nil {
		return x.Listeners
	}
	return nil
}

func (x *GetMITMStatusResponse) GetCaCertPath() string {
	if x != nil {
		return x.CaCertPath
	}
	return ""
}

func (x *GetMITMStatusResponse) GetCaKeyPath() string {
	if x != nil {
		return x.CaKeyPath
	}
	return ""
}

type ListConversationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversationsRequest) Reset() {
	*x = ListConversationsRequest{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsRequest) ProtoMessage() {}

func (x *ListConversationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsRequest.ProtoReflect.Descriptor instead.
func (*ListConversationsRequest) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{9}
}

type GetConversationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	LastN          int64                  `protobuf:"varint,2,opt,name=last_n,json=lastN,proto3" json:"last_n,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetConversationRequest) Reset() {
	*x = GetConversationRequest{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationRequest) ProtoMessage() {}

func (x *GetConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationRequest.ProtoReflect.Descriptor instead.
func (*GetConversationRequest) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetConversationRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *GetConversationRequest) GetLastN() int64 {
	if x != nil {
		return x.LastN
	}
	return 0
}

type GetConversationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConversationResponse) Reset() {
	*x = GetConversationResponse{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationResponse) ProtoMessage() {}

func (x *GetConversationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationResponse.ProtoReflect.Descriptor instead.
func (*GetConversationResponse) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetConversationResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type GetConversationContextRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Timestamp      string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	MessageIndex   int64                  `protobuf:"varint,3,opt,name=message_index,json=messageIndex,proto3" json:"message_index,omitempty"`
	Before         int64                  `protobuf:"varint,4,opt,name=before,proto3" json:"before,omitempty"`
	After          int64                  `protobuf:"varint,5,opt,name=after,proto3" json:"after,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetConversationContextRequest) Reset() {
	*x = GetConversationContextRequest{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationContextRequest) ProtoMessage() {}

func (x *GetConversationContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationContextRequest.ProtoReflect.Descriptor instead.
func (*GetConversationContextRequest) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetConversationContextRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *GetConversationContextRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *GetConversationContextRequest) GetMessageIndex() int64 {
	if x != nil {
		return x.MessageIndex
	}
	return 0
}

func (x *GetConversationContextRequest) GetBefore() int64 {
	if x != nil {
		return x.Before
	}
	return 0
}

func (x *GetConversationContextRequest) GetAfter() int64 {
	if x != nil {
		return x.After
	}
	return 0
}

type GetConversationContextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConversationContextResponse) Reset() {
	*x = GetConversationContextResponse{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationContextResponse) ProtoMessage() {}

func (x *GetConversationContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationContextResponse.ProtoReflect.Descriptor instead.
func (*GetConversationContextResponse) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetConversationContextResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SearchConversationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Query          string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Depth          string                 `protobuf:"bytes,3,opt,name=depth,proto3" json:"depth,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SearchConversationRequest) Reset() {
	*x = SearchConversationRequest{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchConversationRequest) ProtoMessage() {}

func (x *SearchConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchConversationRequest.ProtoReflect.Descriptor instead.
func (*SearchConversationRequest) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{14}
}

func (x *SearchConversationRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *SearchConversationRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchConversationRequest) GetDepth() string {
	if x != nil {
		return x.Depth
	}
	return ""
}

type SearchConversationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	ResultId      string                 `protobuf:"bytes,2,opt,name=result_id,json=resultId,proto3" json:"result_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchConversationResponse) Reset() {
	*x = SearchConversationResponse{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchConversationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchConversationResponse) ProtoMessage() {}

func (x *SearchConversationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchConversationResponse.ProtoReflect.Descriptor instead.
func (*SearchConversationResponse) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{15}
}

func (x *SearchConversationResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SearchConversationResponse) GetResultId() string {
	if x != nil {
		return x.ResultId
	}
	return ""
}

// SearchProgress is the live advancement of a running search across its chunk
// sweep and its rerank layers.
type SearchProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunksDone    int64                  `protobuf:"varint,1,opt,name=chunks_done,json=chunksDone,proto3" json:"chunks_done,omitempty"`
	ChunksTotal   int64                  `protobuf:"varint,2,opt,name=chunks_total,json=chunksTotal,proto3" json:"chunks_total,omitempty"`
	LayerIndex    int64                  `protobuf:"varint,3,opt,name=layer_index,json=layerIndex,proto3" json:"layer_index,omitempty"`
	LayerTotal    int64                  `protobuf:"varint,4,opt,name=layer_total,json=layerTotal,proto3" json:"layer_total,omitempty"`
	LayerName     string                 `protobuf:"bytes,5,opt,name=layer_name,json=layerName,proto3" json:"layer_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchProgress) Reset() {
	*x = SearchProgress{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProgress) ProtoMessage() {}

func (x *SearchProgress) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProgress.ProtoReflect.Descriptor instead.
func (*SearchProgress) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{16}
}

func (x *SearchProgress) GetChunksDone() int64 {
	if x != nil {
		return x.ChunksDone
	}
	return 0
}

func (x *SearchProgress) GetChunksTotal() int64 {
	if x != nil {
		return x.ChunksTotal
	}
	return 0
}

func (x *SearchProgress) GetLayerIndex() int64 {
	if x != nil {
		return x.LayerIndex
	}
	return 0
}

func (x *SearchProgress) GetLayerTotal() int64 {
	if x != nil {
		return x.LayerTotal
	}
	return 0
}

func (x *SearchProgress) GetLayerName() string {
	if x != nil {
		return x.LayerName
	}
	return ""
}

type GetSearchStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultId      string                 `protobuf:"bytes,1,opt,name=result_id,json=resultId,proto3" json:"result_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSearchStatusRequest) Reset() {
	*x = GetSearchStatusRequest{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSearchStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSearchStatusRequest) ProtoMessage() {}

func (x *GetSearchStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSearchStatusRequest.ProtoReflect.Descriptor instead.
func (*GetSearchStatusRequest) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{17}
}

func (x *GetSearchStatusRequest) GetResultId() string {
	if x != nil {
		return x.ResultId
	}
	return ""
}

type GetSearchStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	ResultId      string                 `protobuf:"bytes,2,opt,name=result_id,json=resultId,proto3" json:"result_id,omitempty"`
	Status        SearchStatus           `protobuf:"varint,3,opt,name=status,proto3,enum=clyde.v1.SearchStatus" json:"status,omitempty"`
	Progress      *SearchProgress        `protobuf:"bytes,4,opt,name=progress,proto3" json:"progress,omitempty"`
	ResultText    string                 `protobuf:"bytes,5,opt,name=result_text,json=resultText,proto3" json:"result_text,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSearchStatusResponse) Reset() {
	*x = GetSearchStatusResponse{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSearchStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSearchStatusResponse) ProtoMessage() {}

func (x *GetSearchStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSearchStatusResponse.ProtoReflect.Descriptor instead.
func (*GetSearchStatusResponse) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{18}
}

func (x *GetSearchStatusResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetSearchStatusResponse) GetResultId() string {
	if x != nil {
		return x.ResultId
	}
	return ""
}

func (x *GetSearchStatusResponse) GetStatus() SearchStatus {
	if x != nil {
		return x.Status
	}
	return SearchStatus_SEARCH_STATUS_UNSPECIFIED
}

func (x *GetSearchStatusResponse) GetProgress() *SearchProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

func (x *GetSearchStatusResponse) GetResultText() string {
	if x != nil {
		return x.ResultText
	}
	return ""
}

func (x *GetSearchStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CancelSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultId      string                 `protobuf:"bytes,1,opt,name=result_id,json=resultId,proto3" json:"result_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelSearchRequest) Reset() {
	*x = CancelSearchRequest{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSearchRequest) ProtoMessage() {}

func (x *CancelSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSearchRequest.ProtoReflect.Descriptor instead.
func (*CancelSearchRequest) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{19}
}

func (x *CancelSearchRequest) GetResultId() string {
	if x != nil {
		return x.ResultId
	}
	return ""
}

type CancelSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        SearchStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=clyde.v1.SearchStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelSearchResponse) Reset() {
	*x = CancelSearchResponse{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSearchResponse) ProtoMessage() {}

func (x *CancelSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSearchResponse.ProtoReflect.Descriptor instead.
func (*CancelSearchResponse) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{20}
}

func (x *CancelSearchResponse) GetStatus() SearchStatus {
	if x != nil {
		return x.Status
	}
	return SearchStatus_SEARCH_STATUS_UNSPECIFIED
}

type AnalyzeSearchResultsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultId      string                 `protobuf:"bytes,1,opt,name=result_id,json=resultId,proto3" json:"result_id,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeSearchResultsRequest) Reset() {
	*x = AnalyzeSearchResultsRequest{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeSearchResultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeSearchResultsRequest) ProtoMessage() {}

func (x *AnalyzeSearchResultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeSearchResultsRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeSearchResultsRequest) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{21}
}

func (x *AnalyzeSearchResultsRequest) GetResultId() string {
	if x != nil {
		return x.ResultId
	}
	return ""
}

func (x *AnalyzeSearchResultsRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type AnalyzeSearchResultsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeSearchResultsResponse) Reset() {
	*x = AnalyzeSearchResultsResponse{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeSearchResultsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeSearchResultsResponse) ProtoMessage() {}

func (x *AnalyzeSearchResultsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeSearchResultsResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeSearchResultsResponse) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{22}
}

func (x *AnalyzeSearchResultsResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ExportTranscriptRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ConversationId         string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Format                 string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	Whitespace             string                 `protobuf:"bytes,3,opt,name=whitespace,proto3" json:"whitespace,omitempty"`
	HistoryStart           int64                  `protobuf:"varint,4,opt,name=history_start,json=historyStart,proto3" json:"history_start,omitempty"`
	IncludeSystemPrompts   bool                   `protobuf:"varint,5,opt,name=include_system_prompts,json=includeSystemPrompts,proto3" json:"include_system_prompts,omitempty"`
	IncludeToolOutputs     bool                   `protobuf:"varint,6,opt,name=include_tool_outputs,json=includeToolOutputs,proto3" json:"include_tool_outputs,omitempty"`
	IncludeRawJsonMetadata bool                   `protobuf:"varint,7,opt,name=include_raw_json_metadata,json=includeRawJsonMetadata,proto3" json:"include_raw_json_metadata,omitempty"`
	IncludeThinking        bool                   `protobuf:"varint,8,opt,name=include_thinking,json=includeThinking,proto3" json:"include_thinking,omitempty"`
	IncludeToolCalls       bool                   `protobuf:"varint,9,opt,name=include_tool_calls,json=includeToolCalls,proto3" json:"include_tool_calls,omitempty"`
	IncludeChat            bool                   `protobuf:"varint,10,opt,name=include_chat,json=includeChat,proto3" json:"include_chat,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ExportTranscriptRequest) Reset() {
	*x = ExportTranscriptRequest{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportTranscriptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportTranscriptRequest) ProtoMessage() {}

func (x *ExportTranscriptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportTranscriptRequest.ProtoReflect.Descriptor instead.
func (*ExportTranscriptRequest) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{23}
}

func (x *ExportTranscriptRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ExportTranscriptRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ExportTranscriptRequest) GetWhitespace() string {
	if x != nil {
		return x.Whitespace
	}
	return ""
}

func (x *ExportTranscriptRequest) GetHistoryStart() int64 {
	if x != nil {
		return x.HistoryStart
	}
	return 0
}

func (x *ExportTranscriptRequest) GetIncludeSystemPrompts() bool {
	if x != nil {
		return x.IncludeSystemPrompts
	}
	return false
}

func (x *ExportTranscriptRequest) GetIncludeToolOutputs() bool {
	if x != nil {
		return x.IncludeToolOutputs
	}
	return false
}

func (x *ExportTranscriptRequest) GetIncludeRawJsonMetadata() bool {
	if x != nil {
		return x.IncludeRawJsonMetadata
	}
	return false
}

func (x *ExportTranscriptRequest) GetIncludeThinking() bool {
	if x != nil {
		return x.IncludeThinking
	}
	return false
}

func (x *ExportTranscriptRequest) GetIncludeToolCalls() bool {
	if x != nil {
		return x.IncludeToolCalls
	}
	return false
}

func (x *ExportTranscriptRequest) GetIncludeChat() bool {
	if x != nil {
		return x.IncludeChat
	}
	return false
}

type ExportTranscriptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          []byte                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportTranscriptResponse) Reset() {
	*x = ExportTranscriptResponse{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportTranscriptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportTranscriptResponse) ProtoMessage() {}

func (x *ExportTranscriptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportTranscriptResponse.ProtoReflect.Descriptor instead.
func (*ExportTranscriptResponse) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{24}
}

func (x *ExportTranscriptResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type ConversationRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Provider      Provider               `protobuf:"varint,2,opt,name=provider,proto3,enum=clyde.v1.Provider" json:"provider,omitempty"`
	NativeId      string                 `protobuf:"bytes,3,opt,name=native_id,json=nativeId,proto3" json:"native_id,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	WorkspaceRoot string                 `protobuf:"bytes,5,opt,name=workspace_root,json=workspaceRoot,proto3" json:"workspace_root,omitempty"`
	ArtifactPath  string                 `protobuf:"bytes,6,opt,name=artifact_path,json=artifactPath,proto3" json:"artifact_path,omitempty"`
	ArtifactKind  string                 `protobuf:"bytes,7,opt,name=artifact_kind,json=artifactKind,proto3" json:"artifact_kind,omitempty"`
	Model         string                 `protobuf:"bytes,8,opt,name=model,proto3" json:"model,omitempty"`
	CreatedAtUnix int64                  `protobuf:"varint,9,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	UpdatedAtUnix int64                  `protobuf:"varint,10,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,11,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Archived      bool                   `protobuf:"varint,12,opt,name=archived,proto3" json:"archived,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationRecord) Reset() {
	*x = ConversationRecord{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationRecord) ProtoMessage() {}

func (x *ConversationRecord) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationRecord.ProtoReflect.Descriptor instead.
func (*ConversationRecord) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{25}
}

func (x *ConversationRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConversationRecord) GetProvider() Provider {
	if x != nil {
		return x.Provider
	}
	return Provider_PROVIDER_UNSPECIFIED
}

func (x *ConversationRecord) GetNativeId() string {
	if x != nil {
		return x.NativeId
	}
	return ""
}

func (x *ConversationRecord) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ConversationRecord) GetWorkspaceRoot() string {
	if x != nil {
		return x.WorkspaceRoot
	}
	return ""
}

func (x *ConversationRecord) GetArtifactPath() string {
	if x != nil {
		return x.ArtifactPath
	}
	return ""
}

func (x *ConversationRecord) GetArtifactKind() string {
	if x != nil {
		return x.ArtifactKind
	}
	return ""
}

func (x *ConversationRecord) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ConversationRecord) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *ConversationRecord) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

func (x *ConversationRecord) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ConversationRecord) GetArchived() bool {
	if x != nil {
		return x.Archived
	}
	return false
}

type ListConversationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conversations []*ConversationRecord  `protobuf:"bytes,1,rep,name=conversations,proto3" json:"conversations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversationsResponse) Reset() {
	*x = ListConversationsResponse{}
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsResponse) ProtoMessage() {}

func (x *ListConversationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsResponse.ProtoReflect.Descriptor instead.
func (*ListConversationsResponse) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_service_proto_rawDescGZIP(), []int{26}
}

func (x *ListConversationsResponse) GetConversations() []*ConversationRecord {
	if x != nil {
		return x.Conversations
	}
	return nil
}

var File_clyde_v1_daemon_service_proto protoreflect.FileDescriptor

const file_clyde_v1_daemon_service_proto_rawDesc = "" +
	"\n" +
	"\x1dclyde/v1/daemon/service.proto\x12\bclyde.v1\x1a\x1eclyde/v1/daemon/provider.proto\"\x8b\x01\n" +
	"\x14LogsInventoryRequest\x12\x1d\n" +
	"\n" +
	"state_root\x18\x01 \x01(\tR\tstateRoot\x12,\n" +
	"\x12largest_file_limit\x18\x02 \x01(\x03R\x10largestFileLimit\x12\x12\n" +
	"\x04deep\x18\x03 \x01(\bR\x04deep\x12\x12\n" +
	"\x04json\x18\x04 \x01(\bR\x04json\"/\n" +
	"\x15LogsInventoryResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\"\x9b\x01\n" +
	"\x13SeedBaselineRequest\x12\x1a\n" +
	"\bupstream\x18\x01 \x01(\tR\bupstream\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\x12\x1d\n" +
	"\n" +
	"include_ua\x18\x04 \x03(\tR\tincludeUa\x12\x1d\n" +
	"\n" +
	"exclude_ua\x18\x05 \x03(\tR\texcludeUa\"f\n" +
	"\x14SeedBaselineResponse\x12\x18\n" +
	"\awritten\x18\x01 \x01(\tR\awritten\x12\x1a\n" +
	"\bupstream\x18\x02 \x01(\tR\bupstream\x12\x18\n" +
	"\aflavors\x18\x03 \x01(\x03R\aflavors\"8\n" +
	"\x12ShowCaptureRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04json\x18\x02 \x01(\bR\x04json\"-\n" +
	"\x13ShowCaptureResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\"\x16\n" +
	"\x14GetMITMStatusRequest\"N\n" +
	"\x12MITMListenerStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x0e\n" +
	"\x02up\x18\x03 \x01(\bR\x02up\"\x95\x01\n" +
	"\x15GetMITMStatusResponse\x12:\n" +
	"\tlisteners\x18\x01 \x03(\v2\x1c.clyde.v1.MITMListenerStatusR\tlisteners\x12 \n" +
	"\fca_cert_path\x18\x02 \x01(\tR\n" +
	"caCertPath\x12\x1e\n" +
	"\vca_key_path\x18\x03 \x01(\tR\tcaKeyPath\"\x1a\n" +
	"\x18ListConversationsRequest\"X\n" +
	"\x16GetConversationRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x15\n" +
	"\x06last_n\x18\x02 \x01(\x03R\x05lastN\"-\n" +
	"\x17GetConversationResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\xb9\x01\n" +
	"\x1dGetConversationContextRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x12#\n" +
	"\rmessage_index\x18\x03 \x01(\x03R\fmessageIndex\x12\x16\n" +
	"\x06before\x18\x04 \x01(\x03R\x06before\x12\x14\n" +
	"\x05after\x18\x05 \x01(\x03R\x05after\"4\n" +
	"\x1eGetConversationContextResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"p\n" +
	"\x19SearchConversationRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x14\n" +
	"\x05depth\x18\x03 \x01(\tR\x05depth\"M\n" +
	"\x1aSearchConversationResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1b\n" +
	"\tresult_id\x18\x02 \x01(\tR\bresultId\"\xb5\x01\n" +
	"\x0eSearchProgress\x12\x1f\n" +
	"\vchunks_done\x18\x01 \x01(\x03R\n" +
	"chunksDone\x12!\n" +
	"\fchunks_total\x18\x02 \x01(\x03R\vchunksTotal\x12\x1f\n" +
	"\vlayer_index\x18\x03 \x01(\x03R\n" +
	"layerIndex\x12\x1f\n" +
	"\vlayer_total\x18\x04 \x01(\x03R\n" +
	"layerTotal\x12\x1d\n" +
	"\n" +
	"layer_name\x18\x05 \x01(\tR\tlayerName\"5\n" +
	"\x16GetSearchStatusRequest\x12\x1b\n" +
	"\tresult_id\x18\x01 \x01(\tR\bresultId\"\xe9\x01\n" +
	"\x17GetSearchStatusResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x1b\n" +
	"\tresult_id\x18\x02 \x01(\tR\bresultId\x12.\n" +
	"\x06status\x18\x03 \x01(\x0e2\x16.clyde.v1.SearchStatusR\x06status\x124\n" +
	"\bprogress\x18\x04 \x01(\v2\x18.clyde.v1.SearchProgressR\bprogress\x12\x1f\n" +
	"\vresult_text\x18\x05 \x01(\tR\n" +
	"resultText\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"2\n" +
	"\x13CancelSearchRequest\x12\x1b\n" +
	"\tresult_id\x18\x01 \x01(\tR\bresultId\"F\n" +
	"\x14CancelSearchResponse\x12.\n" +
	"\x06status\x18\x01 \x01(\x0e2\x16.clyde.v1.SearchStatusR\x06status\"R\n" +
	"\x1bAnalyzeSearchResultsRequest\x12\x1b\n" +
	"\tresult_id\x18\x01 \x01(\tR\bresultId\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\"2\n" +
	"\x1cAnalyzeSearchResultsResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\xbe\x03\n" +
	"\x17ExportTranscriptRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12\x1e\n" +
	"\n" +
	"whitespace\x18\x03 \x01(\tR\n" +
	"whitespace\x12#\n" +
	"\rhistory_start\x18\x04 \x01(\x03R\fhistoryStart\x124\n" +
	"\x16include_system_prompts\x18\x05 \x01(\bR\x14includeSystemPrompts\x120\n" +
	"\x14include_tool_outputs\x18\x06 \x01(\bR\x12includeToolOutputs\x129\n" +
	"\x19include_raw_json_metadata\x18\a \x01(\bR\x16includeRawJsonMetadata\x12)\n" +
	"\x10include_thinking\x18\b \x01(\bR\x0fincludeThinking\x12,\n" +
	"\x12include_tool_calls\x18\t \x01(\bR\x10includeToolCalls\x12!\n" +
	"\finclude_chat\x18\n" +
	" \x01(\bR\vincludeChat\".\n" +
	"\x18ExportTranscriptResponse\x12\x12\n" +
	"\x04body\x18\x01 \x01(\fR\x04body\"\x99\x03\n" +
	"\x12ConversationRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\bprovider\x18\x02 \x01(\x0e2\x12.clyde.v1.ProviderR\bprovider\x12\x1b\n" +
	"\tnative_id\x18\x03 \x01(\tR\bnativeId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12%\n" +
	"\x0eworkspace_root\x18\x05 \x01(\tR\rworkspaceRoot\x12#\n" +
	"\rartifact_path\x18\x06 \x01(\tR\fartifactPath\x12#\n" +
	"\rartifact_kind\x18\a \x01(\tR\fartifactKind\x12\x14\n" +
	"\x05model\x18\b \x01(\tR\x05model\x12&\n" +
	"\x0fcreated_at_unix\x18\t \x01(\x03R\rcreatedAtUnix\x12&\n" +
	"\x0fupdated_at_unix\x18\n" +
	" \x01(\x03R\rupdatedAtUnix\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\v \x01(\x03R\tsizeBytes\x12\x1a\n" +
	"\barchived\x18\f \x01(\bR\barchived\"_\n" +
	"\x19ListConversationsResponse\x12B\n" +
	"\rconversations\x18\x01 \x03(\v2\x1c.clyde.v1.ConversationRecordR\rconversations*\xb5\x01\n" +
	"\fSearchStatus\x12\x1d\n" +
	"\x19SEARCH_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SEARCH_STATUS_PENDING\x10\x01\x12\x19\n" +
	"\x15SEARCH_STATUS_RUNNING\x10\x02\x12\x1a\n" +
	"\x16SEARCH_STATUS_COMPLETE\x10\x03\x12\x18\n" +
	"\x14SEARCH_STATUS_FAILED\x10\x04\x12\x1a\n" +
	"\x16SEARCH_STATUS_CANCELED\x10\x052\xc7\n" +
	"\n" +
	"\fClydeService\x12M\n" +
	"\fReloadDaemon\x12\x1d.clyde.v1.ReloadDaemonRequest\x1a\x1e.clyde.v1.ReloadDaemonResponse\x12Y\n" +
	"\x10GetProviderStats\x12!.clyde.v1.GetProviderStatsRequest\x1a\".clyde.v1.GetProviderStatsResponse\x12a\n" +
	"\x16SubscribeProviderStats\x12'.clyde.v1.SubscribeProviderStatsRequest\x1a\x1c.clyde.v1.ProviderStatsEvent0\x01\x12\\\n" +
	"\x11ListConversations\x12\".clyde.v1.ListConversationsRequest\x1a#.clyde.v1.ListConversationsResponse\x12V\n" +
	"\x0fGetConversation\x12 .clyde.v1.GetConversationRequest\x1a!.clyde.v1.GetConversationResponse\x12k\n" +
	"\x16GetConversationContext\x12'.clyde.v1.GetConversationContextRequest\x1a(.clyde.v1.GetConversationContextResponse\x12_\n" +
	"\x12SearchConversation\x12#.clyde.v1.SearchConversationRequest\x1a$.clyde.v1.SearchConversationResponse\x12V\n" +
	"\x0fGetSearchStatus\x12 .clyde.v1.GetSearchStatusRequest\x1a!.clyde.v1.GetSearchStatusResponse\x12M\n" +
	"\fCancelSearch\x12\x1d.clyde.v1.CancelSearchRequest\x1a\x1e.clyde.v1.CancelSearchResponse\x12e\n" +
	"\x14AnalyzeSearchResults\x12%.clyde.v1.AnalyzeSearchResultsRequest\x1a&.clyde.v1.AnalyzeSearchResultsResponse\x12Y\n" +
	"\x10ExportTranscript\x12!.clyde.v1.ExportTranscriptRequest\x1a\".clyde.v1.ExportTranscriptResponse\x12P\n" +
	"\rGetMITMStatus\x12\x1e.clyde.v1.GetMITMStatusRequest\x1a\x1f.clyde.v1.GetMITMStatusResponse\x12J\n" +
	"\vShowCapture\x12\x1c.clyde.v1.ShowCaptureRequest\x1a\x1d.clyde.v1.ShowCaptureResponse\x12M\n" +
	"\fSeedBaseline\x12\x1d.clyde.v1.SeedBaselineRequest\x1a\x1e.clyde.v1.SeedBaselineResponse\x12P\n" +
	"\rLogsInventory\x12\x1e.clyde.v1.LogsInventoryRequest\x1a\x1f.clyde.v1.LogsInventoryResponseB(Z&goodkind.io/clyde/api/clyde/v1;clydev1b\x06proto3"

var (
	file_clyde_v1_daemon_service_proto_rawDescOnce sync.Once
	file_clyde_v1_daemon_service_proto_rawDescData []byte
)

func file_clyde_v1_daemon_service_proto_rawDescGZIP() []byte {
	file_clyde_v1_daemon_service_proto_rawDescOnce.Do(func() {
		file_clyde_v1_daemon_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clyde_v1_daemon_service_proto_rawDesc), len(file_clyde_v1_daemon_service_proto_rawDesc)))
	})
	return file_clyde_v1_daemon_service_proto_rawDescData
}

var file_clyde_v1_daemon_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_clyde_v1_daemon_service_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_clyde_v1_daemon_service_proto_goTypes = []any{
	(SearchStatus)(0),                      // 0: clyde.v1.SearchStatus
	(*LogsInventoryRequest)(nil),           // 1: clyde.v1.LogsInventoryRequest
	(*LogsInventoryResponse)(nil),          // 2: clyde.v1.LogsInventoryResponse
	(*SeedBaselineRequest)(nil),            // 3: clyde.v1.SeedBaselineRequest
	(*SeedBaselineResponse)(nil),           // 4: clyde.v1.SeedBaselineResponse
	(*ShowCaptureRequest)(nil),             // 5: clyde.v1.ShowCaptureRequest
	(*ShowCaptureResponse)(nil),            // 6: clyde.v1.ShowCaptureResponse
	(*GetMITMStatusRequest)(nil),           // 7: clyde.v1.GetMITMStatusRequest
	(*MITMListenerStatus)(nil),             // 8: clyde.v1.MITMListenerStatus
	(*GetMITMStatusResponse)(nil),          // 9: clyde.v1.GetMITMStatusResponse
	(*ListConversationsRequest)(nil),       // 10: clyde.v1.ListConversationsRequest
	(*GetConversationRequest)(nil),         // 11: clyde.v1.GetConversationRequest
	(*GetConversationResponse)(nil),        // 12: clyde.v1.GetConversationResponse
	(*GetConversationContextRequest)(nil),  // 13: clyde.v1.GetConversationContextRequest
	(*GetConversationContextResponse)(nil), // 14: clyde.v1.GetConversationContextResponse
	(*SearchConversationRequest)(nil),      // 15: clyde.v1.SearchConversationRequest
	(*SearchConversationResponse)(nil),     // 16: clyde.v1.SearchConversationResponse
	(*SearchProgress)(nil),                 // 17: clyde.v1.SearchProgress
	(*GetSearchStatusRequest)(nil),         // 18: clyde.v1.GetSearchStatusRequest
	(*GetSearchStatusResponse)(nil),        // 19: clyde.v1.GetSearchStatusResponse
	(*CancelSearchRequest)(nil),            // 20: clyde.v1.CancelSearchRequest
	(*CancelSearchResponse)(nil),           // 21: clyde.v1.CancelSearchResponse
	(*AnalyzeSearchResultsRequest)(nil),    // 22: clyde.v1.AnalyzeSearchResultsRequest
	(*AnalyzeSearchResultsResponse)(nil),   // 23: clyde.v1.AnalyzeSearchResultsResponse
	(*ExportTranscriptRequest)(nil),        // 24: clyde.v1.ExportTranscriptRequest
	(*ExportTranscriptResponse)(nil),       // 25: clyde.v1.ExportTranscriptResponse
	(*ConversationRecord)(nil),             // 26: clyde.v1.ConversationRecord
	(*ListConversationsResponse)(nil),      // 27: clyde.v1.ListConversationsResponse
	(Provider)(0),                          // 28: clyde.v1.Provider
	(*ReloadDaemonRequest)(nil),            // 29: clyde.v1.ReloadDaemonRequest
	(*GetProviderStatsRequest)(nil),        // 30: clyde.v1.GetProviderStatsRequest
	(*SubscribeProviderStatsRequest)(nil),  // 31: clyde.v1.SubscribeProviderStatsRequest
	(*ReloadDaemonResponse)(nil),           // 32: clyde.v1.ReloadDaemonResponse
	(*GetProviderStatsResponse)(nil),       // 33: clyde.v1.GetProviderStatsResponse
	(*ProviderStatsEvent)(nil),             // 34: clyde.v1.ProviderStatsEvent
}
var file_clyde_v1_daemon_service_proto_depIdxs = []int32{
	8,  // 0: clyde.v1.GetMITMStatusResponse.listeners:type_name -> clyde.v1.MITMListenerStatus
	0,  // 1: clyde.v1.GetSearchStatusResponse.status:type_name -> clyde.v1.SearchStatus
	17, // 2: clyde.v1.GetSearchStatusResponse.progress:type_name -> clyde.v1.SearchProgress
	0,  // 3: clyde.v1.CancelSearchResponse.status:type_name -> clyde.v1.SearchStatus
	28, // 4: clyde.v1.ConversationRecord.provider:type_name -> clyde.v1.Provider
	26, // 5: clyde.v1.ListConversationsResponse.conversations:type_name -> clyde.v1.ConversationRecord
	29, // 6: clyde.v1.ClydeService.ReloadDaemon:input_type -> clyde.v1.ReloadDaemonRequest
	30, // 7: clyde.v1.ClydeService.GetProviderStats:input_type -> clyde.v1.GetProviderStatsRequest
	31, // 8: clyde.v1.ClydeService.SubscribeProviderStats:input_type -> clyde.v1.SubscribeProviderStatsRequest
	10, // 9: clyde.v1.ClydeService.ListConversations:input_type -> clyde.v1.ListConversationsRequest
	11, // 10: clyde.v1.ClydeService.GetConversation:input_type -> clyde.v1.GetConversationRequest
	13, // 11: clyde.v1.ClydeService.GetConversationContext:input_type -> clyde.v1.GetConversationContextRequest
	15, // 12: clyde.v1.ClydeService.SearchConversation:input_type -> clyde.v1.SearchConversationRequest
	18, // 13: clyde.v1.ClydeService.GetSearchStatus:input_type -> clyde.v1.GetSearchStatusRequest
	20, // 14: clyde.v1.ClydeService.CancelSearch:input_type -> clyde.v1.CancelSearchRequest
	22, // 15: clyde.v1.ClydeService.AnalyzeSearchResults:input_type -> clyde.v1.AnalyzeSearchResultsRequest
	24, // 16: clyde.v1.ClydeService.ExportTranscript:input_type -> clyde.v1.ExportTranscriptRequest
	7,  // 17: clyde.v1.ClydeService.GetMITMStatus:input_type -> clyde.v1.GetMITMStatusRequest
	5,  // 18: clyde.v1.ClydeService.ShowCapture:input_type -> clyde.v1.ShowCaptureRequest
	3,  // 19: clyde.v1.ClydeService.SeedBaseline:input_type -> clyde.v1.SeedBaselineRequest
	1,  // 20: clyde.v1.ClydeService.LogsInventory:input_type -> clyde.v1.LogsInventoryRequest
	32, // 21: clyde.v1.ClydeService.ReloadDaemon:output_type -> clyde.v1.ReloadDaemonResponse
	33, // 22: clyde.v1.ClydeService.GetProviderStats:output_type -> clyde.v1.GetProviderStatsResponse
	34, // 23: clyde.v1.ClydeService.SubscribeProviderStats:output_type -> clyde.v1.ProviderStatsEvent
	27, // 24: clyde.v1.ClydeService.ListConversations:output_type -> clyde.v1.ListConversationsResponse
	12, // 25: clyde.v1.ClydeService.GetConversation:output_type -> clyde.v1.GetConversationResponse
	14, // 26: clyde.v1.ClydeService.GetConversationContext:output_type -> clyde.v1.GetConversationContextResponse
	16, // 27: clyde.v1.ClydeService.SearchConversation:output_type -> clyde.v1.SearchConversationResponse
	19, // 28: clyde.v1.ClydeService.GetSearchStatus:output_type -> clyde.v1.GetSearchStatusResponse
	21, // 29: clyde.v1.ClydeService.CancelSearch:output_type -> clyde.v1.CancelSearchResponse
	23, // 30: clyde.v1.ClydeService.AnalyzeSearchResults:output_type -> clyde.v1.AnalyzeSearchResultsResponse
	25, // 31: clyde.v1.ClydeService.ExportTranscript:output_type -> clyde.v1.ExportTranscriptResponse
	9,  // 32: clyde.v1.ClydeService.GetMITMStatus:output_type -> clyde.v1.GetMITMStatusResponse
	6,  // 33: clyde.v1.ClydeService.ShowCapture:output_type -> clyde.v1.ShowCaptureResponse
	4,  // 34: clyde.v1.ClydeService.SeedBaseline:output_type -> clyde.v1.SeedBaselineResponse
	2,  // 35: clyde.v1.ClydeService.LogsInventory:output_type -> clyde.v1.LogsInventoryResponse
	21, // [21:36] is the sub-list for method output_type
	6,  // [6:21] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_clyde_v1_daemon_service_proto_init() }
func file_clyde_v1_daemon_service_proto_init() {
	if File_clyde_v1_daemon_service_proto != nil {
		return
	}
	file_clyde_v1_daemon_provider_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clyde_v1_daemon_service_proto_rawDesc), len(file_clyde_v1_daemon_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clyde_v1_daemon_service_proto_goTypes,
		DependencyIndexes: file_clyde_v1_daemon_service_proto_depIdxs,
		EnumInfos:         file_clyde_v1_daemon_service_proto_enumTypes,
		MessageInfos:      file_clyde_v1_daemon_service_proto_msgTypes,
	}.Build()
	File_clyde_v1_daemon_service_proto = out.File
	file_clyde_v1_daemon_service_proto_goTypes = nil
	file_clyde_v1_daemon_service_proto_depIdxs = nil
}
