// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: clyde/v1/daemon/service.proto

package clydev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_clyde_v1_daemon_service_proto protoreflect.FileDescriptor

const file_clyde_v1_daemon_service_proto_rawDesc = "" +
	"\n" +
	"\x1dclyde/v1/daemon/service.proto\x12\bclyde.v1\x1a\x1eclyde/v1/daemon/provider.proto2\x9b\x02\n" +
	"\fClydeService\x12M\n" +
	"\fReloadDaemon\x12\x1d.clyde.v1.ReloadDaemonRequest\x1a\x1e.clyde.v1.ReloadDaemonResponse\x12Y\n" +
	"\x10GetProviderStats\x12!.clyde.v1.GetProviderStatsRequest\x1a\".clyde.v1.GetProviderStatsResponse\x12a\n" +
	"\x16SubscribeProviderStats\x12'.clyde.v1.SubscribeProviderStatsRequest\x1a\x1c.clyde.v1.ProviderStatsEvent0\x01B(Z&goodkind.io/clyde/api/clyde/v1;clydev1b\x06proto3"

var file_clyde_v1_daemon_service_proto_goTypes = []any{
	(*ReloadDaemonRequest)(nil),           // 0: clyde.v1.ReloadDaemonRequest
	(*GetProviderStatsRequest)(nil),       // 1: clyde.v1.GetProviderStatsRequest
	(*SubscribeProviderStatsRequest)(nil), // 2: clyde.v1.SubscribeProviderStatsRequest
	(*ReloadDaemonResponse)(nil),          // 3: clyde.v1.ReloadDaemonResponse
	(*GetProviderStatsResponse)(nil),      // 4: clyde.v1.GetProviderStatsResponse
	(*ProviderStatsEvent)(nil),            // 5: clyde.v1.ProviderStatsEvent
}
var file_clyde_v1_daemon_service_proto_depIdxs = []int32{
	0, // 0: clyde.v1.ClydeService.ReloadDaemon:input_type -> clyde.v1.ReloadDaemonRequest
	1, // 1: clyde.v1.ClydeService.GetProviderStats:input_type -> clyde.v1.GetProviderStatsRequest
	2, // 2: clyde.v1.ClydeService.SubscribeProviderStats:input_type -> clyde.v1.SubscribeProviderStatsRequest
	3, // 3: clyde.v1.ClydeService.ReloadDaemon:output_type -> clyde.v1.ReloadDaemonResponse
	4, // 4: clyde.v1.ClydeService.GetProviderStats:output_type -> clyde.v1.GetProviderStatsResponse
	5, // 5: clyde.v1.ClydeService.SubscribeProviderStats:output_type -> clyde.v1.ProviderStatsEvent
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_clyde_v1_daemon_service_proto_init() }
func file_clyde_v1_daemon_service_proto_init() {
	if File_clyde_v1_daemon_service_proto != nil {
		return
	}
	file_clyde_v1_daemon_provider_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clyde_v1_daemon_service_proto_rawDesc), len(file_clyde_v1_daemon_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clyde_v1_daemon_service_proto_goTypes,
		DependencyIndexes: file_clyde_v1_daemon_service_proto_depIdxs,
	}.Build()
	File_clyde_v1_daemon_service_proto = out.File
	file_clyde_v1_daemon_service_proto_goTypes = nil
	file_clyde_v1_daemon_service_proto_depIdxs = nil
}
