// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: clyde/v1/daemon/service.proto

package clydev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClydeService_ReloadDaemon_FullMethodName           = "/clyde.v1.ClydeService/ReloadDaemon"
	ClydeService_GetProviderStats_FullMethodName       = "/clyde.v1.ClydeService/GetProviderStats"
	ClydeService_SubscribeProviderStats_FullMethodName = "/clyde.v1.ClydeService/SubscribeProviderStats"
)

// ClydeServiceClient is the client API for ClydeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClydeServiceClient interface {
	ReloadDaemon(ctx context.Context, in *ReloadDaemonRequest, opts ...grpc.CallOption) (*ReloadDaemonResponse, error)
	GetProviderStats(ctx context.Context, in *GetProviderStatsRequest, opts ...grpc.CallOption) (*GetProviderStatsResponse, error)
	SubscribeProviderStats(ctx context.Context, in *SubscribeProviderStatsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProviderStatsEvent], error)
}

type clydeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClydeServiceClient(cc grpc.ClientConnInterface) ClydeServiceClient {
	return &clydeServiceClient{cc}
}

func (c *clydeServiceClient) ReloadDaemon(ctx context.Context, in *ReloadDaemonRequest, opts ...grpc.CallOption) (*ReloadDaemonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReloadDaemonResponse)
	err := c.cc.Invoke(ctx, ClydeService_ReloadDaemon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clydeServiceClient) GetProviderStats(ctx context.Context, in *GetProviderStatsRequest, opts ...grpc.CallOption) (*GetProviderStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProviderStatsResponse)
	err := c.cc.Invoke(ctx, ClydeService_GetProviderStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clydeServiceClient) SubscribeProviderStats(ctx context.Context, in *SubscribeProviderStatsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProviderStatsEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ClydeService_ServiceDesc.Streams[0], ClydeService_SubscribeProviderStats_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeProviderStatsRequest, ProviderStatsEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClydeService_SubscribeProviderStatsClient = grpc.ServerStreamingClient[ProviderStatsEvent]

// ClydeServiceServer is the server API for ClydeService service.
// All implementations should embed UnimplementedClydeServiceServer
// for forward compatibility.
type ClydeServiceServer interface {
	ReloadDaemon(context.Context, *ReloadDaemonRequest) (*ReloadDaemonResponse, error)
	GetProviderStats(context.Context, *GetProviderStatsRequest) (*GetProviderStatsResponse, error)
	SubscribeProviderStats(*SubscribeProviderStatsRequest, grpc.ServerStreamingServer[ProviderStatsEvent]) error
}

// UnimplementedClydeServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClydeServiceServer struct{}

func (UnimplementedClydeServiceServer) ReloadDaemon(context.Context, *ReloadDaemonRequest) (*ReloadDaemonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReloadDaemon not implemented")
}
func (UnimplementedClydeServiceServer) GetProviderStats(context.Context, *GetProviderStatsRequest) (*GetProviderStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProviderStats not implemented")
}
func (UnimplementedClydeServiceServer) SubscribeProviderStats(*SubscribeProviderStatsRequest, grpc.ServerStreamingServer[ProviderStatsEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeProviderStats not implemented")
}
func (UnimplementedClydeServiceServer) testEmbeddedByValue() {}

// UnsafeClydeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClydeServiceServer will
// result in compilation errors.
type UnsafeClydeServiceServer interface {
	mustEmbedUnimplementedClydeServiceServer()
}

func RegisterClydeServiceServer(s grpc.ServiceRegistrar, srv ClydeServiceServer) {
	// If the following call panics, it indicates UnimplementedClydeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClydeService_ServiceDesc, srv)
}

func _ClydeService_ReloadDaemon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadDaemonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClydeServiceServer).ReloadDaemon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClydeService_ReloadDaemon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClydeServiceServer).ReloadDaemon(ctx, req.(*ReloadDaemonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClydeService_GetProviderStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProviderStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClydeServiceServer).GetProviderStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClydeService_GetProviderStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClydeServiceServer).GetProviderStats(ctx, req.(*GetProviderStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClydeService_SubscribeProviderStats_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeProviderStatsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ClydeServiceServer).SubscribeProviderStats(m, &grpc.GenericServerStream[SubscribeProviderStatsRequest, ProviderStatsEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClydeService_SubscribeProviderStatsServer = grpc.ServerStreamingServer[ProviderStatsEvent]

// ClydeService_ServiceDesc is the grpc.ServiceDesc for ClydeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClydeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clyde.v1.ClydeService",
	HandlerType: (*ClydeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReloadDaemon",
			Handler:    _ClydeService_ReloadDaemon_Handler,
		},
		{
			MethodName: "GetProviderStats",
			Handler:    _ClydeService_GetProviderStats_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeProviderStats",
			Handler:       _ClydeService_SubscribeProviderStats_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "clyde/v1/daemon/service.proto",
}
