// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: clyde/v1/daemon/session.proto

package clydev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionExportFormat int32

const (
	SessionExportFormat_SESSION_EXPORT_FORMAT_UNSPECIFIED SessionExportFormat = 0
	SessionExportFormat_SESSION_EXPORT_FORMAT_MARKDOWN    SessionExportFormat = 1
	SessionExportFormat_SESSION_EXPORT_FORMAT_HTML        SessionExportFormat = 2
	SessionExportFormat_SESSION_EXPORT_FORMAT_JSON        SessionExportFormat = 3
	SessionExportFormat_SESSION_EXPORT_FORMAT_PLAIN_TEXT  SessionExportFormat = 4
)

// Enum value maps for SessionExportFormat.
var (
	SessionExportFormat_name = map[int32]string{
		0: "SESSION_EXPORT_FORMAT_UNSPECIFIED",
		1: "SESSION_EXPORT_FORMAT_MARKDOWN",
		2: "SESSION_EXPORT_FORMAT_HTML",
		3: "SESSION_EXPORT_FORMAT_JSON",
		4: "SESSION_EXPORT_FORMAT_PLAIN_TEXT",
	}
	SessionExportFormat_value = map[string]int32{
		"SESSION_EXPORT_FORMAT_UNSPECIFIED": 0,
		"SESSION_EXPORT_FORMAT_MARKDOWN":    1,
		"SESSION_EXPORT_FORMAT_HTML":        2,
		"SESSION_EXPORT_FORMAT_JSON":        3,
		"SESSION_EXPORT_FORMAT_PLAIN_TEXT":  4,
	}
)

func (x SessionExportFormat) Enum() *SessionExportFormat {
	p := new(SessionExportFormat)
	*p = x
	return p
}

func (x SessionExportFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionExportFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_clyde_v1_daemon_session_proto_enumTypes[0].Descriptor()
}

func (SessionExportFormat) Type() protoreflect.EnumType {
	return &file_clyde_v1_daemon_session_proto_enumTypes[0]
}

func (x SessionExportFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionExportFormat.Descriptor instead.
func (SessionExportFormat) EnumDescriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_session_proto_rawDescGZIP(), []int{0}
}

type SessionExportWhitespaceCompression int32

const (
	SessionExportWhitespaceCompression_SESSION_EXPORT_WHITESPACE_COMPRESSION_UNSPECIFIED SessionExportWhitespaceCompression = 0
	SessionExportWhitespaceCompression_SESSION_EXPORT_WHITESPACE_COMPRESSION_PRESERVE    SessionExportWhitespaceCompression = 1
	SessionExportWhitespaceCompression_SESSION_EXPORT_WHITESPACE_COMPRESSION_TIDY        SessionExportWhitespaceCompression = 2
	SessionExportWhitespaceCompression_SESSION_EXPORT_WHITESPACE_COMPRESSION_COMPACT     SessionExportWhitespaceCompression = 3
	SessionExportWhitespaceCompression_SESSION_EXPORT_WHITESPACE_COMPRESSION_DENSE       SessionExportWhitespaceCompression = 4
)

// Enum value maps for SessionExportWhitespaceCompression.
var (
	SessionExportWhitespaceCompression_name = map[int32]string{
		0: "SESSION_EXPORT_WHITESPACE_COMPRESSION_UNSPECIFIED",
		1: "SESSION_EXPORT_WHITESPACE_COMPRESSION_PRESERVE",
		2: "SESSION_EXPORT_WHITESPACE_COMPRESSION_TIDY",
		3: "SESSION_EXPORT_WHITESPACE_COMPRESSION_COMPACT",
		4: "SESSION_EXPORT_WHITESPACE_COMPRESSION_DENSE",
	}
	SessionExportWhitespaceCompression_value = map[string]int32{
		"SESSION_EXPORT_WHITESPACE_COMPRESSION_UNSPECIFIED": 0,
		"SESSION_EXPORT_WHITESPACE_COMPRESSION_PRESERVE":    1,
		"SESSION_EXPORT_WHITESPACE_COMPRESSION_TIDY":        2,
		"SESSION_EXPORT_WHITESPACE_COMPRESSION_COMPACT":     3,
		"SESSION_EXPORT_WHITESPACE_COMPRESSION_DENSE":       4,
	}
)

func (x SessionExportWhitespaceCompression) Enum() *SessionExportWhitespaceCompression {
	p := new(SessionExportWhitespaceCompression)
	*p = x
	return p
}

func (x SessionExportWhitespaceCompression) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionExportWhitespaceCompression) Descriptor() protoreflect.EnumDescriptor {
	return file_clyde_v1_daemon_session_proto_enumTypes[1].Descriptor()
}

func (SessionExportWhitespaceCompression) Type() protoreflect.EnumType {
	return &file_clyde_v1_daemon_session_proto_enumTypes[1]
}

func (x SessionExportWhitespaceCompression) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionExportWhitespaceCompression.Descriptor instead.
func (SessionExportWhitespaceCompression) EnumDescriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_session_proto_rawDescGZIP(), []int{1}
}

type AcquireSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionName   string                 `protobuf:"bytes,1,opt,name=session_name,json=sessionName,proto3" json:"session_name,omitempty"`
	WrapperId     string                 `protobuf:"bytes,2,opt,name=wrapper_id,json=wrapperId,proto3" json:"wrapper_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireSessionRequest) Reset() {
	*x = AcquireSessionRequest{}
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireSessionRequest) ProtoMessage() {}

func (x *AcquireSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireSessionRequest.ProtoReflect.Descriptor instead.
func (*AcquireSessionRequest) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_session_proto_rawDescGZIP(), []int{0}
}

func (x *AcquireSessionRequest) GetSessionName() string {
	if x != nil {
		return x.SessionName
	}
	return ""
}

func (x *AcquireSessionRequest) GetWrapperId() string {
	if x != nil {
		return x.WrapperId
	}
	return ""
}

type AcquireSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FakeHome      string                 `protobuf:"bytes,1,opt,name=fake_home,json=fakeHome,proto3" json:"fake_home,omitempty"`
	RealClaude    string                 `protobuf:"bytes,2,opt,name=real_claude,json=realClaude,proto3" json:"real_claude,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	SettingsFile  string                 `protobuf:"bytes,4,opt,name=settings_file,json=settingsFile,proto3" json:"settings_file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireSessionResponse) Reset() {
	*x = AcquireSessionResponse{}
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireSessionResponse) ProtoMessage() {}

func (x *AcquireSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireSessionResponse.ProtoReflect.Descriptor instead.
func (*AcquireSessionResponse) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_session_proto_rawDescGZIP(), []int{1}
}

func (x *AcquireSessionResponse) GetFakeHome() string {
	if x != nil {
		return x.FakeHome
	}
	return ""
}

func (x *AcquireSessionResponse) GetRealClaude() string {
	if x != nil {
		return x.RealClaude
	}
	return ""
}

func (x *AcquireSessionResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AcquireSessionResponse) GetSettingsFile() string {
	if x != nil {
		return x.SettingsFile
	}
	return ""
}

type ReleaseSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WrapperId     string                 `protobuf:"bytes,1,opt,name=wrapper_id,json=wrapperId,proto3" json:"wrapper_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseSessionRequest) Reset() {
	*x = ReleaseSessionRequest{}
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseSessionRequest) ProtoMessage() {}

func (x *ReleaseSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseSessionRequest.ProtoReflect.Descriptor instead.
func (*ReleaseSessionRequest) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_session_proto_rawDescGZIP(), []int{2}
}

func (x *ReleaseSessionRequest) GetWrapperId() string {
	if x != nil {
		return x.WrapperId
	}
	return ""
}

type ReleaseSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseSessionResponse) Reset() {
	*x = ReleaseSessionResponse{}
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseSessionResponse) ProtoMessage() {}

func (x *ReleaseSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseSessionResponse.ProtoReflect.Descriptor instead.
func (*ReleaseSessionResponse) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_session_proto_rawDescGZIP(), []int{3}
}

type HookEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	WrapperId     string                 `protobuf:"bytes,2,opt,name=wrapper_id,json=wrapperId,proto3" json:"wrapper_id,omitempty"`
	RawJson       []byte                 `protobuf:"bytes,3,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookEventRequest) Reset() {
	*x = HookEventRequest{}
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookEventRequest) ProtoMessage() {}

func (x *HookEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookEventRequest.ProtoReflect.Descriptor instead.
func (*HookEventRequest) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_session_proto_rawDescGZIP(), []int{4}
}

func (x *HookEventRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *HookEventRequest) GetWrapperId() string {
	if x != nil {
		return x.WrapperId
	}
	return ""
}

func (x *HookEventRequest) GetRawJson() []byte {
	if x != nil {
		return x.RawJson
	}
	return nil
}

type HookEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookEventResponse) Reset() {
	*x = HookEventResponse{}
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookEventResponse) ProtoMessage() {}

func (x *HookEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookEventResponse.ProtoReflect.Descriptor instead.
func (*HookEventResponse) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_session_proto_rawDescGZIP(), []int{5}
}

func (x *HookEventResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type ListActiveSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActiveSessionsRequest) Reset() {
	*x = ListActiveSessionsRequest{}
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActiveSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveSessionsRequest) ProtoMessage() {}

func (x *ListActiveSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListActiveSessionsRequest) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_session_proto_rawDescGZIP(), []int{6}
}

type ListActiveSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*ActiveSession       `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActiveSessionsResponse) Reset() {
	*x = ListActiveSessionsResponse{}
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActiveSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveSessionsResponse) ProtoMessage() {}

func (x *ListActiveSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListActiveSessionsResponse) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_session_proto_rawDescGZIP(), []int{7}
}

func (x *ListActiveSessionsResponse) GetSessions() []*ActiveSession {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type ActiveSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionName   string                 `protobuf:"bytes,1,opt,name=session_name,json=sessionName,proto3" json:"session_name,omitempty"`
	WrapperId     string                 `protobuf:"bytes,2,opt,name=wrapper_id,json=wrapperId,proto3" json:"wrapper_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActiveSession) Reset() {
	*x = ActiveSession{}
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveSession) ProtoMessage() {}

func (x *ActiveSession) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveSession.ProtoReflect.Descriptor instead.
func (*ActiveSession) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_session_proto_rawDescGZIP(), []int{8}
}

func (x *ActiveSession) GetSessionName() string {
	if x != nil {
		return x.SessionName
	}
	return ""
}

func (x *ActiveSession) GetWrapperId() string {
	if x != nil {
		return x.WrapperId
	}
	return ""
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_session_proto_rawDescGZIP(), []int{9}
}

type SessionSummary struct {
	state                 protoimpl.MessageState   `protogen:"open.v1"`
	Name                  string                   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MetadataName          string                   `protobuf:"bytes,2,opt,name=metadata_name,json=metadataName,proto3" json:"metadata_name,omitempty"`
	SessionId             string                   `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TranscriptPath        string                   `protobuf:"bytes,4,opt,name=transcript_path,json=transcriptPath,proto3" json:"transcript_path,omitempty"`
	WorkDir               string                   `protobuf:"bytes,5,opt,name=work_dir,json=workDir,proto3" json:"work_dir,omitempty"`
	CreatedNanos          int64                    `protobuf:"varint,6,opt,name=created_nanos,json=createdNanos,proto3" json:"created_nanos,omitempty"`
	LastAccessedNanos     int64                    `protobuf:"varint,7,opt,name=last_accessed_nanos,json=lastAccessedNanos,proto3" json:"last_accessed_nanos,omitempty"`
	ParentSession         string                   `protobuf:"bytes,8,opt,name=parent_session,json=parentSession,proto3" json:"parent_session,omitempty"`
	IsForkedSession       bool                     `protobuf:"varint,9,opt,name=is_forked_session,json=isForkedSession,proto3" json:"is_forked_session,omitempty"`
	IsIncognito           bool                     `protobuf:"varint,10,opt,name=is_incognito,json=isIncognito,proto3" json:"is_incognito,omitempty"`
	PreviousSessionIds    []string                 `protobuf:"bytes,11,rep,name=previous_session_ids,json=previousSessionIds,proto3" json:"previous_session_ids,omitempty"`
	Context               string                   `protobuf:"bytes,12,opt,name=context,proto3" json:"context,omitempty"`
	HasCustomOutputStyle  bool                     `protobuf:"varint,13,opt,name=has_custom_output_style,json=hasCustomOutputStyle,proto3" json:"has_custom_output_style,omitempty"`
	WorkspaceRoot         string                   `protobuf:"bytes,14,opt,name=workspace_root,json=workspaceRoot,proto3" json:"workspace_root,omitempty"`
	ContextMessageCount   int32                    `protobuf:"varint,15,opt,name=context_message_count,json=contextMessageCount,proto3" json:"context_message_count,omitempty"`
	DisplayTitle          string                   `protobuf:"bytes,16,opt,name=display_title,json=displayTitle,proto3" json:"display_title,omitempty"`
	Model                 string                   `protobuf:"bytes,17,opt,name=model,proto3" json:"model,omitempty"`
	RemoteControl         bool                     `protobuf:"varint,18,opt,name=remote_control,json=remoteControl,proto3" json:"remote_control,omitempty"`
	MessageCount          int32                    `protobuf:"varint,19,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	TranscriptSizeBytes   int64                    `protobuf:"varint,20,opt,name=transcript_size_bytes,json=transcriptSizeBytes,proto3" json:"transcript_size_bytes,omitempty"`
	LastActivityNanos     int64                    `protobuf:"varint,21,opt,name=last_activity_nanos,json=lastActivityNanos,proto3" json:"last_activity_nanos,omitempty"`
	Bridge                *Bridge                  `protobuf:"bytes,22,opt,name=bridge,proto3" json:"bridge,omitempty"`
	ContextTotalTokens    int32                    `protobuf:"varint,23,opt,name=context_total_tokens,json=contextTotalTokens,proto3" json:"context_total_tokens,omitempty"`
	ContextMaxTokens      int32                    `protobuf:"varint,24,opt,name=context_max_tokens,json=contextMaxTokens,proto3" json:"context_max_tokens,omitempty"`
	ContextPercentage     int32                    `protobuf:"varint,25,opt,name=context_percentage,json=contextPercentage,proto3" json:"context_percentage,omitempty"`
	ContextMessagesTokens int32                    `protobuf:"varint,26,opt,name=context_messages_tokens,json=contextMessagesTokens,proto3" json:"context_messages_tokens,omitempty"`
	ContextUsageLoaded    bool                     `protobuf:"varint,27,opt,name=context_usage_loaded,json=contextUsageLoaded,proto3" json:"context_usage_loaded,omitempty"`
	ContextUsageStatus    string                   `protobuf:"bytes,28,opt,name=context_usage_status,json=contextUsageStatus,proto3" json:"context_usage_status,omitempty"`
	Provider              string                   `protobuf:"bytes,29,opt,name=provider,proto3" json:"provider,omitempty"`
	Runtime               *ProviderRuntimeBoundary `protobuf:"bytes,30,opt,name=runtime,proto3" json:"runtime,omitempty"`
	AutoNameState         string                   `protobuf:"bytes,31,opt,name=auto_name_state,json=autoNameState,proto3" json:"auto_name_state,omitempty"`
	AutoNameSource        string                   `protobuf:"bytes,32,opt,name=auto_name_source,json=autoNameSource,proto3" json:"auto_name_source,omitempty"`
	LastAutoNameNanos     int64                    `protobuf:"varint,33,opt,name=last_auto_name_nanos,json=lastAutoNameNanos,proto3" json:"last_auto_name_nanos,omitempty"`
	AutoNameSourceHash    string                   `protobuf:"bytes,34,opt,name=auto_name_source_hash,json=autoNameSourceHash,proto3" json:"auto_name_source_hash,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SessionSummary) Reset() {
	*x = SessionSummary{}
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionSummary) ProtoMessage() {}

func (x *SessionSummary) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionSummary.ProtoReflect.Descriptor instead.
func (*SessionSummary) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_session_proto_rawDescGZIP(), []int{10}
}

func (x *SessionSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SessionSummary) GetMetadataName() string {
	if x != nil {
		return x.MetadataName
	}
	return ""
}

func (x *SessionSummary) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionSummary) GetTranscriptPath() string {
	if x != nil {
		return x.TranscriptPath
	}
	return ""
}

func (x *SessionSummary) GetWorkDir() string {
	if x != nil {
		return x.WorkDir
	}
	return ""
}

func (x *SessionSummary) GetCreatedNanos() int64 {
	if x != nil {
		return x.CreatedNanos
	}
	return 0
}

func (x *SessionSummary) GetLastAccessedNanos() int64 {
	if x != nil {
		return x.LastAccessedNanos
	}
	return 0
}

func (x *SessionSummary) GetParentSession() string {
	if x != nil {
		return x.ParentSession
	}
	return ""
}

func (x *SessionSummary) GetIsForkedSession() bool {
	if x != nil {
		return x.IsForkedSession
	}
	return false
}

func (x *SessionSummary) GetIsIncognito() bool {
	if x != nil {
		return x.IsIncognito
	}
	return false
}

func (x *SessionSummary) GetPreviousSessionIds() []string {
	if x != nil {
		return x.PreviousSessionIds
	}
	return nil
}

func (x *SessionSummary) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *SessionSummary) GetHasCustomOutputStyle() bool {
	if x != nil {
		return x.HasCustomOutputStyle
	}
	return false
}

func (x *SessionSummary) GetWorkspaceRoot() string {
	if x != nil {
		return x.WorkspaceRoot
	}
	return ""
}

func (x *SessionSummary) GetContextMessageCount() int32 {
	if x != nil {
		return x.ContextMessageCount
	}
	return 0
}

func (x *SessionSummary) GetDisplayTitle() string {
	if x != nil {
		return x.DisplayTitle
	}
	return ""
}

func (x *SessionSummary) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *SessionSummary) GetRemoteControl() bool {
	if x != nil {
		return x.RemoteControl
	}
	return false
}

func (x *SessionSummary) GetMessageCount() int32 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

func (x *SessionSummary) GetTranscriptSizeBytes() int64 {
	if x != nil {
		return x.TranscriptSizeBytes
	}
	return 0
}

func (x *SessionSummary) GetLastActivityNanos() int64 {
	if x != nil {
		return x.LastActivityNanos
	}
	return 0
}

func (x *SessionSummary) GetBridge() *Bridge {
	if x != nil {
		return x.Bridge
	}
	return nil
}

func (x *SessionSummary) GetContextTotalTokens() int32 {
	if x != nil {
		return x.ContextTotalTokens
	}
	return 0
}

func (x *SessionSummary) GetContextMaxTokens() int32 {
	if x != nil {
		return x.ContextMaxTokens
	}
	return 0
}

func (x *SessionSummary) GetContextPercentage() int32 {
	if x != nil {
		return x.ContextPercentage
	}
	return 0
}

func (x *SessionSummary) GetContextMessagesTokens() int32 {
	if x != nil {
		return x.ContextMessagesTokens
	}
	return 0
}

func (x *SessionSummary) GetContextUsageLoaded() bool {
	if x != nil {
		return x.ContextUsageLoaded
	}
	return false
}

func (x *SessionSummary) GetContextUsageStatus() string {
	if x != nil {
		return x.ContextUsageStatus
	}
	return ""
}

func (x *SessionSummary) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *SessionSummary) GetRuntime() *ProviderRuntimeBoundary {
	if x != nil {
		return x.Runtime
	}
	return nil
}

func (x *SessionSummary) GetAutoNameState() string {
	if x != nil {
		return x.AutoNameState
	}
	return ""
}

func (x *SessionSummary) GetAutoNameSource() string {
	if x != nil {
		return x.AutoNameSource
	}
	return ""
}

func (x *SessionSummary) GetLastAutoNameNanos() int64 {
	if x != nil {
		return x.LastAutoNameNanos
	}
	return 0
}

func (x *SessionSummary) GetAutoNameSourceHash() string {
	if x != nil {
		return x.AutoNameSourceHash
	}
	return ""
}

type ListSessionsResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Sessions            []*SessionSummary      `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	GlobalRemoteControl bool                   `protobuf:"varint,2,opt,name=global_remote_control,json=globalRemoteControl,proto3" json:"global_remote_control,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_session_proto_rawDescGZIP(), []int{11}
}

func (x *ListSessionsResponse) GetSessions() []*SessionSummary {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *ListSessionsResponse) GetGlobalRemoteControl() bool {
	if x != nil {
		return x.GlobalRemoteControl
	}
	return false
}

type DetailMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Role           string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Text           string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	TimestampNanos int64                  `protobuf:"varint,3,opt,name=timestamp_nanos,json=timestampNanos,proto3" json:"timestamp_nanos,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DetailMessage) Reset() {
	*x = DetailMessage{}
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailMessage) ProtoMessage() {}

func (x *DetailMessage) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailMessage.ProtoReflect.Descriptor instead.
func (*DetailMessage) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_session_proto_rawDescGZIP(), []int{12}
}

func (x *DetailMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *DetailMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *DetailMessage) GetTimestampNanos() int64 {
	if x != nil {
		return x.TimestampNanos
	}
	return 0
}

type ToolUse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolUse) Reset() {
	*x = ToolUse{}
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolUse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolUse) ProtoMessage() {}

func (x *ToolUse) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolUse.ProtoReflect.Descriptor instead.
func (*ToolUse) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_session_proto_rawDescGZIP(), []int{13}
}

func (x *ToolUse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolUse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetSessionDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionName   string                 `protobuf:"bytes,1,opt,name=session_name,json=sessionName,proto3" json:"session_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionDetailRequest) Reset() {
	*x = GetSessionDetailRequest{}
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionDetailRequest) ProtoMessage() {}

func (x *GetSessionDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionDetailRequest.ProtoReflect.Descriptor instead.
func (*GetSessionDetailRequest) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_session_proto_rawDescGZIP(), []int{14}
}

func (x *GetSessionDetailRequest) GetSessionName() string {
	if x != nil {
		return x.SessionName
	}
	return ""
}

type GetSessionDetailResponse struct {
	state                 protoimpl.MessageState   `protogen:"open.v1"`
	SessionName           string                   `protobuf:"bytes,1,opt,name=session_name,json=sessionName,proto3" json:"session_name,omitempty"`
	Model                 string                   `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	RecentMessages        []*DetailMessage         `protobuf:"bytes,3,rep,name=recent_messages,json=recentMessages,proto3" json:"recent_messages,omitempty"`
	AllMessages           []*DetailMessage         `protobuf:"bytes,4,rep,name=all_messages,json=allMessages,proto3" json:"all_messages,omitempty"`
	Tools                 []*ToolUse               `protobuf:"bytes,5,rep,name=tools,proto3" json:"tools,omitempty"`
	TotalMessages         int32                    `protobuf:"varint,6,opt,name=total_messages,json=totalMessages,proto3" json:"total_messages,omitempty"`
	VisibleTokensEstimate int32                    `protobuf:"varint,7,opt,name=visible_tokens_estimate,json=visibleTokensEstimate,proto3" json:"visible_tokens_estimate,omitempty"`
	LastMessageTokens     int32                    `protobuf:"varint,8,opt,name=last_message_tokens,json=lastMessageTokens,proto3" json:"last_message_tokens,omitempty"`
	CompactionCount       int32                    `protobuf:"varint,9,opt,name=compaction_count,json=compactionCount,proto3" json:"compaction_count,omitempty"`
	LastPreCompactTokens  int32                    `protobuf:"varint,10,opt,name=last_pre_compact_tokens,json=lastPreCompactTokens,proto3" json:"last_pre_compact_tokens,omitempty"`
	TranscriptSizeBytes   int64                    `protobuf:"varint,11,opt,name=transcript_size_bytes,json=transcriptSizeBytes,proto3" json:"transcript_size_bytes,omitempty"`
	LastActivityNanos     int64                    `protobuf:"varint,12,opt,name=last_activity_nanos,json=lastActivityNanos,proto3" json:"last_activity_nanos,omitempty"`
	Provider              string                   `protobuf:"bytes,13,opt,name=provider,proto3" json:"provider,omitempty"`
	Runtime               *ProviderRuntimeBoundary `protobuf:"bytes,14,opt,name=runtime,proto3" json:"runtime,omitempty"`
	// Context usage fields mirror SessionSummary so the detail RPC carries
	// a coherent self-contained snapshot. Populated lazily from the
	// daemon's context-usage cache. Loaded=false with Status="probing"
	// means a refresh is in flight and the next detail call should hit
	// a warm cache.
	ContextTotalTokens    int32  `protobuf:"varint,15,opt,name=context_total_tokens,json=contextTotalTokens,proto3" json:"context_total_tokens,omitempty"`
	ContextMaxTokens      int32  `protobuf:"varint,16,opt,name=context_max_tokens,json=contextMaxTokens,proto3" json:"context_max_tokens,omitempty"`
	ContextPercentage     int32  `protobuf:"varint,17,opt,name=context_percentage,json=contextPercentage,proto3" json:"context_percentage,omitempty"`
	ContextMessagesTokens int32  `protobuf:"varint,18,opt,name=context_messages_tokens,json=contextMessagesTokens,proto3" json:"context_messages_tokens,omitempty"`
	ContextUsageLoaded    bool   `protobuf:"varint,19,opt,name=context_usage_loaded,json=contextUsageLoaded,proto3" json:"context_usage_loaded,omitempty"`
	ContextUsageStatus    string `protobuf:"bytes,20,opt,name=context_usage_status,json=contextUsageStatus,proto3" json:"context_usage_status,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetSessionDetailResponse) Reset() {
	*x = GetSessionDetailResponse{}
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionDetailResponse) ProtoMessage() {}

func (x *GetSessionDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionDetailResponse.ProtoReflect.Descriptor instead.
func (*GetSessionDetailResponse) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_session_proto_rawDescGZIP(), []int{15}
}

func (x *GetSessionDetailResponse) GetSessionName() string {
	if x != nil {
		return x.SessionName
	}
	return ""
}

func (x *GetSessionDetailResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GetSessionDetailResponse) GetRecentMessages() []*DetailMessage {
	if x != nil {
		return x.RecentMessages
	}
	return nil
}

func (x *GetSessionDetailResponse) GetAllMessages() []*DetailMessage {
	if x != nil {
		return x.AllMessages
	}
	return nil
}

func (x *GetSessionDetailResponse) GetTools() []*ToolUse {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *GetSessionDetailResponse) GetTotalMessages() int32 {
	if x != nil {
		return x.TotalMessages
	}
	return 0
}

func (x *GetSessionDetailResponse) GetVisibleTokensEstimate() int32 {
	if x != nil {
		return x.VisibleTokensEstimate
	}
	return 0
}

func (x *GetSessionDetailResponse) GetLastMessageTokens() int32 {
	if x != nil {
		return x.LastMessageTokens
	}
	return 0
}

func (x *GetSessionDetailResponse) GetCompactionCount() int32 {
	if x != nil {
		return x.CompactionCount
	}
	return 0
}

func (x *GetSessionDetailResponse) GetLastPreCompactTokens() int32 {
	if x != nil {
		return x.LastPreCompactTokens
	}
	return 0
}

func (x *GetSessionDetailResponse) GetTranscriptSizeBytes() int64 {
	if x != nil {
		return x.TranscriptSizeBytes
	}
	return 0
}

func (x *GetSessionDetailResponse) GetLastActivityNanos() int64 {
	if x != nil {
		return x.LastActivityNanos
	}
	return 0
}

func (x *GetSessionDetailResponse) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *GetSessionDetailResponse) GetRuntime() *ProviderRuntimeBoundary {
	if x != nil {
		return x.Runtime
	}
	return nil
}

func (x *GetSessionDetailResponse) GetContextTotalTokens() int32 {
	if x != nil {
		return x.ContextTotalTokens
	}
	return 0
}

func (x *GetSessionDetailResponse) GetContextMaxTokens() int32 {
	if x != nil {
		return x.ContextMaxTokens
	}
	return 0
}

func (x *GetSessionDetailResponse) GetContextPercentage() int32 {
	if x != nil {
		return x.ContextPercentage
	}
	return 0
}

func (x *GetSessionDetailResponse) GetContextMessagesTokens() int32 {
	if x != nil {
		return x.ContextMessagesTokens
	}
	return 0
}

func (x *GetSessionDetailResponse) GetContextUsageLoaded() bool {
	if x != nil {
		return x.ContextUsageLoaded
	}
	return false
}

func (x *GetSessionDetailResponse) GetContextUsageStatus() string {
	if x != nil {
		return x.ContextUsageStatus
	}
	return ""
}

type GetSessionExportStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionName   string                 `protobuf:"bytes,1,opt,name=session_name,json=sessionName,proto3" json:"session_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionExportStatsRequest) Reset() {
	*x = GetSessionExportStatsRequest{}
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionExportStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionExportStatsRequest) ProtoMessage() {}

func (x *GetSessionExportStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionExportStatsRequest.ProtoReflect.Descriptor instead.
func (*GetSessionExportStatsRequest) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_session_proto_rawDescGZIP(), []int{16}
}

func (x *GetSessionExportStatsRequest) GetSessionName() string {
	if x != nil {
		return x.SessionName
	}
	return ""
}

type GetSessionExportStatsResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	SessionName           string                 `protobuf:"bytes,1,opt,name=session_name,json=sessionName,proto3" json:"session_name,omitempty"`
	VisibleTokensEstimate int32                  `protobuf:"varint,2,opt,name=visible_tokens_estimate,json=visibleTokensEstimate,proto3" json:"visible_tokens_estimate,omitempty"`
	VisibleMessages       int32                  `protobuf:"varint,3,opt,name=visible_messages,json=visibleMessages,proto3" json:"visible_messages,omitempty"`
	UserMessages          int32                  `protobuf:"varint,4,opt,name=user_messages,json=userMessages,proto3" json:"user_messages,omitempty"`
	AssistantMessages     int32                  `protobuf:"varint,5,opt,name=assistant_messages,json=assistantMessages,proto3" json:"assistant_messages,omitempty"`
	ToolResultMessages    int32                  `protobuf:"varint,6,opt,name=tool_result_messages,json=toolResultMessages,proto3" json:"tool_result_messages,omitempty"`
	ToolCalls             int32                  `protobuf:"varint,7,opt,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	SystemPrompts         int32                  `protobuf:"varint,8,opt,name=system_prompts,json=systemPrompts,proto3" json:"system_prompts,omitempty"`
	Compactions           int32                  `protobuf:"varint,9,opt,name=compactions,proto3" json:"compactions,omitempty"`
	TranscriptSizeBytes   int64                  `protobuf:"varint,10,opt,name=transcript_size_bytes,json=transcriptSizeBytes,proto3" json:"transcript_size_bytes,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetSessionExportStatsResponse) Reset() {
	*x = GetSessionExportStatsResponse{}
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionExportStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionExportStatsResponse) ProtoMessage() {}

func (x *GetSessionExportStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionExportStatsResponse.ProtoReflect.Descriptor instead.
func (*GetSessionExportStatsResponse) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_session_proto_rawDescGZIP(), []int{17}
}

func (x *GetSessionExportStatsResponse) GetSessionName() string {
	if x != nil {
		return x.SessionName
	}
	return ""
}

func (x *GetSessionExportStatsResponse) GetVisibleTokensEstimate() int32 {
	if x != nil {
		return x.VisibleTokensEstimate
	}
	return 0
}

func (x *GetSessionExportStatsResponse) GetVisibleMessages() int32 {
	if x != nil {
		return x.VisibleMessages
	}
	return 0
}

func (x *GetSessionExportStatsResponse) GetUserMessages() int32 {
	if x != nil {
		return x.UserMessages
	}
	return 0
}

func (x *GetSessionExportStatsResponse) GetAssistantMessages() int32 {
	if x != nil {
		return x.AssistantMessages
	}
	return 0
}

func (x *GetSessionExportStatsResponse) GetToolResultMessages() int32 {
	if x != nil {
		return x.ToolResultMessages
	}
	return 0
}

func (x *GetSessionExportStatsResponse) GetToolCalls() int32 {
	if x != nil {
		return x.ToolCalls
	}
	return 0
}

func (x *GetSessionExportStatsResponse) GetSystemPrompts() int32 {
	if x != nil {
		return x.SystemPrompts
	}
	return 0
}

func (x *GetSessionExportStatsResponse) GetCompactions() int32 {
	if x != nil {
		return x.Compactions
	}
	return 0
}

func (x *GetSessionExportStatsResponse) GetTranscriptSizeBytes() int64 {
	if x != nil {
		return x.TranscriptSizeBytes
	}
	return 0
}

type ExportSessionRequest struct {
	state                  protoimpl.MessageState             `protogen:"open.v1"`
	SessionName            string                             `protobuf:"bytes,1,opt,name=session_name,json=sessionName,proto3" json:"session_name,omitempty"`
	Format                 SessionExportFormat                `protobuf:"varint,2,opt,name=format,proto3,enum=clyde.v1.SessionExportFormat" json:"format,omitempty"`
	HistoryStart           int32                              `protobuf:"varint,3,opt,name=history_start,json=historyStart,proto3" json:"history_start,omitempty"`
	WhitespaceCompression  SessionExportWhitespaceCompression `protobuf:"varint,4,opt,name=whitespace_compression,json=whitespaceCompression,proto3,enum=clyde.v1.SessionExportWhitespaceCompression" json:"whitespace_compression,omitempty"`
	IncludeChat            bool                               `protobuf:"varint,5,opt,name=include_chat,json=includeChat,proto3" json:"include_chat,omitempty"`
	IncludeThinking        bool                               `protobuf:"varint,6,opt,name=include_thinking,json=includeThinking,proto3" json:"include_thinking,omitempty"`
	IncludeSystemPrompts   bool                               `protobuf:"varint,7,opt,name=include_system_prompts,json=includeSystemPrompts,proto3" json:"include_system_prompts,omitempty"`
	IncludeToolCalls       bool                               `protobuf:"varint,8,opt,name=include_tool_calls,json=includeToolCalls,proto3" json:"include_tool_calls,omitempty"`
	IncludeToolOutputs     bool                               `protobuf:"varint,9,opt,name=include_tool_outputs,json=includeToolOutputs,proto3" json:"include_tool_outputs,omitempty"`
	IncludeRawJsonMetadata bool                               `protobuf:"varint,10,opt,name=include_raw_json_metadata,json=includeRawJsonMetadata,proto3" json:"include_raw_json_metadata,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ExportSessionRequest) Reset() {
	*x = ExportSessionRequest{}
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportSessionRequest) ProtoMessage() {}

func (x *ExportSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportSessionRequest.ProtoReflect.Descriptor instead.
func (*ExportSessionRequest) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_session_proto_rawDescGZIP(), []int{18}
}

func (x *ExportSessionRequest) GetSessionName() string {
	if x != nil {
		return x.SessionName
	}
	return ""
}

func (x *ExportSessionRequest) GetFormat() SessionExportFormat {
	if x != nil {
		return x.Format
	}
	return SessionExportFormat_SESSION_EXPORT_FORMAT_UNSPECIFIED
}

func (x *ExportSessionRequest) GetHistoryStart() int32 {
	if x != nil {
		return x.HistoryStart
	}
	return 0
}

func (x *ExportSessionRequest) GetWhitespaceCompression() SessionExportWhitespaceCompression {
	if x != nil {
		return x.WhitespaceCompression
	}
	return SessionExportWhitespaceCompression_SESSION_EXPORT_WHITESPACE_COMPRESSION_UNSPECIFIED
}

func (x *ExportSessionRequest) GetIncludeChat() bool {
	if x != nil {
		return x.IncludeChat
	}
	return false
}

func (x *ExportSessionRequest) GetIncludeThinking() bool {
	if x != nil {
		return x.IncludeThinking
	}
	return false
}

func (x *ExportSessionRequest) GetIncludeSystemPrompts() bool {
	if x != nil {
		return x.IncludeSystemPrompts
	}
	return false
}

func (x *ExportSessionRequest) GetIncludeToolCalls() bool {
	if x != nil {
		return x.IncludeToolCalls
	}
	return false
}

func (x *ExportSessionRequest) GetIncludeToolOutputs() bool {
	if x != nil {
		return x.IncludeToolOutputs
	}
	return false
}

func (x *ExportSessionRequest) GetIncludeRawJsonMetadata() bool {
	if x != nil {
		return x.IncludeRawJsonMetadata
	}
	return false
}

type ExportSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          []byte                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportSessionResponse) Reset() {
	*x = ExportSessionResponse{}
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportSessionResponse) ProtoMessage() {}

func (x *ExportSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportSessionResponse.ProtoReflect.Descriptor instead.
func (*ExportSessionResponse) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_session_proto_rawDescGZIP(), []int{19}
}

func (x *ExportSessionResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type RenameSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldName       string                 `protobuf:"bytes,1,opt,name=old_name,json=oldName,proto3" json:"old_name,omitempty"`
	NewName       string                 `protobuf:"bytes,2,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameSessionRequest) Reset() {
	*x = RenameSessionRequest{}
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameSessionRequest) ProtoMessage() {}

func (x *RenameSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameSessionRequest.ProtoReflect.Descriptor instead.
func (*RenameSessionRequest) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_session_proto_rawDescGZIP(), []int{20}
}

func (x *RenameSessionRequest) GetOldName() string {
	if x != nil {
		return x.OldName
	}
	return ""
}

func (x *RenameSessionRequest) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

type RenameSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameSessionResponse) Reset() {
	*x = RenameSessionResponse{}
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameSessionResponse) ProtoMessage() {}

func (x *RenameSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameSessionResponse.ProtoReflect.Descriptor instead.
func (*RenameSessionResponse) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_session_proto_rawDescGZIP(), []int{21}
}

type DeleteSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionRequest) Reset() {
	*x = DeleteSessionRequest{}
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionRequest) ProtoMessage() {}

func (x *DeleteSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSessionRequest) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_session_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteSessionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionResponse) Reset() {
	*x = DeleteSessionResponse{}
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionResponse) ProtoMessage() {}

func (x *DeleteSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionResponse.ProtoReflect.Descriptor instead.
func (*DeleteSessionResponse) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_session_proto_rawDescGZIP(), []int{23}
}

type UpdateSessionMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	WorkspaceRoot string                 `protobuf:"bytes,2,opt,name=workspace_root,json=workspaceRoot,proto3" json:"workspace_root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSessionMetadataRequest) Reset() {
	*x = UpdateSessionMetadataRequest{}
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSessionMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSessionMetadataRequest) ProtoMessage() {}

func (x *UpdateSessionMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSessionMetadataRequest.ProtoReflect.Descriptor instead.
func (*UpdateSessionMetadataRequest) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_session_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateSessionMetadataRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateSessionMetadataRequest) GetWorkspaceRoot() string {
	if x != nil {
		return x.WorkspaceRoot
	}
	return ""
}

type UpdateSessionMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSessionMetadataResponse) Reset() {
	*x = UpdateSessionMetadataResponse{}
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSessionMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSessionMetadataResponse) ProtoMessage() {}

func (x *UpdateSessionMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_session_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSessionMetadataResponse.ProtoReflect.Descriptor instead.
func (*UpdateSessionMetadataResponse) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_session_proto_rawDescGZIP(), []int{25}
}

var File_clyde_v1_daemon_session_proto protoreflect.FileDescriptor

const file_clyde_v1_daemon_session_proto_rawDesc = "" +
	"\n" +
	"\x1dclyde/v1/daemon/session.proto\x12\bclyde.v1\x1a\x1cclyde/v1/daemon/bridge.proto\x1a\x1eclyde/v1/daemon/provider.proto\"Y\n" +
	"\x15AcquireSessionRequest\x12!\n" +
	"\fsession_name\x18\x01 \x01(\tR\vsessionName\x12\x1d\n" +
	"\n" +
	"wrapper_id\x18\x02 \x01(\tR\twrapperId\"\x91\x01\n" +
	"\x16AcquireSessionResponse\x12\x1b\n" +
	"\tfake_home\x18\x01 \x01(\tR\bfakeHome\x12\x1f\n" +
	"\vreal_claude\x18\x02 \x01(\tR\n" +
	"realClaude\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12#\n" +
	"\rsettings_file\x18\x04 \x01(\tR\fsettingsFile\"6\n" +
	"\x15ReleaseSessionRequest\x12\x1d\n" +
	"\n" +
	"wrapper_id\x18\x01 \x01(\tR\twrapperId\"\x18\n" +
	"\x16ReleaseSessionResponse\"f\n" +
	"\x10HookEventRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12\x1d\n" +
	"\n" +
	"wrapper_id\x18\x02 \x01(\tR\twrapperId\x12\x19\n" +
	"\braw_json\x18\x03 \x01(\fR\arawJson\"0\n" +
	"\x11HookEventResponse\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\"\x1b\n" +
	"\x19ListActiveSessionsRequest\"Q\n" +
	"\x1aListActiveSessionsResponse\x123\n" +
	"\bsessions\x18\x01 \x03(\v2\x17.clyde.v1.ActiveSessionR\bsessions\"Q\n" +
	"\rActiveSession\x12!\n" +
	"\fsession_name\x18\x01 \x01(\tR\vsessionName\x12\x1d\n" +
	"\n" +
	"wrapper_id\x18\x02 \x01(\tR\twrapperId\"\x15\n" +
	"\x13ListSessionsRequest\"\xa4\v\n" +
	"\x0eSessionSummary\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rmetadata_name\x18\x02 \x01(\tR\fmetadataName\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12'\n" +
	"\x0ftranscript_path\x18\x04 \x01(\tR\x0etranscriptPath\x12\x19\n" +
	"\bwork_dir\x18\x05 \x01(\tR\aworkDir\x12#\n" +
	"\rcreated_nanos\x18\x06 \x01(\x03R\fcreatedNanos\x12.\n" +
	"\x13last_accessed_nanos\x18\a \x01(\x03R\x11lastAccessedNanos\x12%\n" +
	"\x0eparent_session\x18\b \x01(\tR\rparentSession\x12*\n" +
	"\x11is_forked_session\x18\t \x01(\bR\x0fisForkedSession\x12!\n" +
	"\fis_incognito\x18\n" +
	" \x01(\bR\visIncognito\x120\n" +
	"\x14previous_session_ids\x18\v \x03(\tR\x12previousSessionIds\x12\x18\n" +
	"\acontext\x18\f \x01(\tR\acontext\x125\n" +
	"\x17has_custom_output_style\x18\r \x01(\bR\x14hasCustomOutputStyle\x12%\n" +
	"\x0eworkspace_root\x18\x0e \x01(\tR\rworkspaceRoot\x122\n" +
	"\x15context_message_count\x18\x0f \x01(\x05R\x13contextMessageCount\x12#\n" +
	"\rdisplay_title\x18\x10 \x01(\tR\fdisplayTitle\x12\x14\n" +
	"\x05model\x18\x11 \x01(\tR\x05model\x12%\n" +
	"\x0eremote_control\x18\x12 \x01(\bR\rremoteControl\x12#\n" +
	"\rmessage_count\x18\x13 \x01(\x05R\fmessageCount\x122\n" +
	"\x15transcript_size_bytes\x18\x14 \x01(\x03R\x13transcriptSizeBytes\x12.\n" +
	"\x13last_activity_nanos\x18\x15 \x01(\x03R\x11lastActivityNanos\x12(\n" +
	"\x06bridge\x18\x16 \x01(\v2\x10.clyde.v1.BridgeR\x06bridge\x120\n" +
	"\x14context_total_tokens\x18\x17 \x01(\x05R\x12contextTotalTokens\x12,\n" +
	"\x12context_max_tokens\x18\x18 \x01(\x05R\x10contextMaxTokens\x12-\n" +
	"\x12context_percentage\x18\x19 \x01(\x05R\x11contextPercentage\x126\n" +
	"\x17context_messages_tokens\x18\x1a \x01(\x05R\x15contextMessagesTokens\x120\n" +
	"\x14context_usage_loaded\x18\x1b \x01(\bR\x12contextUsageLoaded\x120\n" +
	"\x14context_usage_status\x18\x1c \x01(\tR\x12contextUsageStatus\x12\x1a\n" +
	"\bprovider\x18\x1d \x01(\tR\bprovider\x12;\n" +
	"\aruntime\x18\x1e \x01(\v2!.clyde.v1.ProviderRuntimeBoundaryR\aruntime\x12&\n" +
	"\x0fauto_name_state\x18\x1f \x01(\tR\rautoNameState\x12(\n" +
	"\x10auto_name_source\x18  \x01(\tR\x0eautoNameSource\x12/\n" +
	"\x14last_auto_name_nanos\x18! \x01(\x03R\x11lastAutoNameNanos\x121\n" +
	"\x15auto_name_source_hash\x18\" \x01(\tR\x12autoNameSourceHash\"\x80\x01\n" +
	"\x14ListSessionsResponse\x124\n" +
	"\bsessions\x18\x01 \x03(\v2\x18.clyde.v1.SessionSummaryR\bsessions\x122\n" +
	"\x15global_remote_control\x18\x02 \x01(\bR\x13globalRemoteControl\"`\n" +
	"\rDetailMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12'\n" +
	"\x0ftimestamp_nanos\x18\x03 \x01(\x03R\x0etimestampNanos\"3\n" +
	"\aToolUse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"<\n" +
	"\x17GetSessionDetailRequest\x12!\n" +
	"\fsession_name\x18\x01 \x01(\tR\vsessionName\"\xd3\a\n" +
	"\x18GetSessionDetailResponse\x12!\n" +
	"\fsession_name\x18\x01 \x01(\tR\vsessionName\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12@\n" +
	"\x0frecent_messages\x18\x03 \x03(\v2\x17.clyde.v1.DetailMessageR\x0erecentMessages\x12:\n" +
	"\fall_messages\x18\x04 \x03(\v2\x17.clyde.v1.DetailMessageR\vallMessages\x12'\n" +
	"\x05tools\x18\x05 \x03(\v2\x11.clyde.v1.ToolUseR\x05tools\x12%\n" +
	"\x0etotal_messages\x18\x06 \x01(\x05R\rtotalMessages\x126\n" +
	"\x17visible_tokens_estimate\x18\a \x01(\x05R\x15visibleTokensEstimate\x12.\n" +
	"\x13last_message_tokens\x18\b \x01(\x05R\x11lastMessageTokens\x12)\n" +
	"\x10compaction_count\x18\t \x01(\x05R\x0fcompactionCount\x125\n" +
	"\x17last_pre_compact_tokens\x18\n" +
	" \x01(\x05R\x14lastPreCompactTokens\x122\n" +
	"\x15transcript_size_bytes\x18\v \x01(\x03R\x13transcriptSizeBytes\x12.\n" +
	"\x13last_activity_nanos\x18\f \x01(\x03R\x11lastActivityNanos\x12\x1a\n" +
	"\bprovider\x18\r \x01(\tR\bprovider\x12;\n" +
	"\aruntime\x18\x0e \x01(\v2!.clyde.v1.ProviderRuntimeBoundaryR\aruntime\x120\n" +
	"\x14context_total_tokens\x18\x0f \x01(\x05R\x12contextTotalTokens\x12,\n" +
	"\x12context_max_tokens\x18\x10 \x01(\x05R\x10contextMaxTokens\x12-\n" +
	"\x12context_percentage\x18\x11 \x01(\x05R\x11contextPercentage\x126\n" +
	"\x17context_messages_tokens\x18\x12 \x01(\x05R\x15contextMessagesTokens\x120\n" +
	"\x14context_usage_loaded\x18\x13 \x01(\bR\x12contextUsageLoaded\x120\n" +
	"\x14context_usage_status\x18\x14 \x01(\tR\x12contextUsageStatus\"A\n" +
	"\x1cGetSessionExportStatsRequest\x12!\n" +
	"\fsession_name\x18\x01 \x01(\tR\vsessionName\"\xc7\x03\n" +
	"\x1dGetSessionExportStatsResponse\x12!\n" +
	"\fsession_name\x18\x01 \x01(\tR\vsessionName\x126\n" +
	"\x17visible_tokens_estimate\x18\x02 \x01(\x05R\x15visibleTokensEstimate\x12)\n" +
	"\x10visible_messages\x18\x03 \x01(\x05R\x0fvisibleMessages\x12#\n" +
	"\ruser_messages\x18\x04 \x01(\x05R\fuserMessages\x12-\n" +
	"\x12assistant_messages\x18\x05 \x01(\x05R\x11assistantMessages\x120\n" +
	"\x14tool_result_messages\x18\x06 \x01(\x05R\x12toolResultMessages\x12\x1d\n" +
	"\n" +
	"tool_calls\x18\a \x01(\x05R\ttoolCalls\x12%\n" +
	"\x0esystem_prompts\x18\b \x01(\x05R\rsystemPrompts\x12 \n" +
	"\vcompactions\x18\t \x01(\x05R\vcompactions\x122\n" +
	"\x15transcript_size_bytes\x18\n" +
	" \x01(\x03R\x13transcriptSizeBytes\"\x99\x04\n" +
	"\x14ExportSessionRequest\x12!\n" +
	"\fsession_name\x18\x01 \x01(\tR\vsessionName\x125\n" +
	"\x06format\x18\x02 \x01(\x0e2\x1d.clyde.v1.SessionExportFormatR\x06format\x12#\n" +
	"\rhistory_start\x18\x03 \x01(\x05R\fhistoryStart\x12c\n" +
	"\x16whitespace_compression\x18\x04 \x01(\x0e2,.clyde.v1.SessionExportWhitespaceCompressionR\x15whitespaceCompression\x12!\n" +
	"\finclude_chat\x18\x05 \x01(\bR\vincludeChat\x12)\n" +
	"\x10include_thinking\x18\x06 \x01(\bR\x0fincludeThinking\x124\n" +
	"\x16include_system_prompts\x18\a \x01(\bR\x14includeSystemPrompts\x12,\n" +
	"\x12include_tool_calls\x18\b \x01(\bR\x10includeToolCalls\x120\n" +
	"\x14include_tool_outputs\x18\t \x01(\bR\x12includeToolOutputs\x129\n" +
	"\x19include_raw_json_metadata\x18\n" +
	" \x01(\bR\x16includeRawJsonMetadata\"+\n" +
	"\x15ExportSessionResponse\x12\x12\n" +
	"\x04body\x18\x01 \x01(\fR\x04body\"L\n" +
	"\x14RenameSessionRequest\x12\x19\n" +
	"\bold_name\x18\x01 \x01(\tR\aoldName\x12\x19\n" +
	"\bnew_name\x18\x02 \x01(\tR\anewName\"\x17\n" +
	"\x15RenameSessionResponse\"*\n" +
	"\x14DeleteSessionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x17\n" +
	"\x15DeleteSessionResponse\"Y\n" +
	"\x1cUpdateSessionMetadataRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0eworkspace_root\x18\x02 \x01(\tR\rworkspaceRoot\"\x1f\n" +
	"\x1dUpdateSessionMetadataResponse*\xc6\x01\n" +
	"\x13SessionExportFormat\x12%\n" +
	"!SESSION_EXPORT_FORMAT_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eSESSION_EXPORT_FORMAT_MARKDOWN\x10\x01\x12\x1e\n" +
	"\x1aSESSION_EXPORT_FORMAT_HTML\x10\x02\x12\x1e\n" +
	"\x1aSESSION_EXPORT_FORMAT_JSON\x10\x03\x12$\n" +
	" SESSION_EXPORT_FORMAT_PLAIN_TEXT\x10\x04*\xa3\x02\n" +
	"\"SessionExportWhitespaceCompression\x125\n" +
	"1SESSION_EXPORT_WHITESPACE_COMPRESSION_UNSPECIFIED\x10\x00\x122\n" +
	".SESSION_EXPORT_WHITESPACE_COMPRESSION_PRESERVE\x10\x01\x12.\n" +
	"*SESSION_EXPORT_WHITESPACE_COMPRESSION_TIDY\x10\x02\x121\n" +
	"-SESSION_EXPORT_WHITESPACE_COMPRESSION_COMPACT\x10\x03\x12/\n" +
	"+SESSION_EXPORT_WHITESPACE_COMPRESSION_DENSE\x10\x04B(Z&goodkind.io/clyde/api/clyde/v1;clydev1b\x06proto3"

var (
	file_clyde_v1_daemon_session_proto_rawDescOnce sync.Once
	file_clyde_v1_daemon_session_proto_rawDescData []byte
)

func file_clyde_v1_daemon_session_proto_rawDescGZIP() []byte {
	file_clyde_v1_daemon_session_proto_rawDescOnce.Do(func() {
		file_clyde_v1_daemon_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clyde_v1_daemon_session_proto_rawDesc), len(file_clyde_v1_daemon_session_proto_rawDesc)))
	})
	return file_clyde_v1_daemon_session_proto_rawDescData
}

var file_clyde_v1_daemon_session_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_clyde_v1_daemon_session_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_clyde_v1_daemon_session_proto_goTypes = []any{
	(SessionExportFormat)(0),                // 0: clyde.v1.SessionExportFormat
	(SessionExportWhitespaceCompression)(0), // 1: clyde.v1.SessionExportWhitespaceCompression
	(*AcquireSessionRequest)(nil),           // 2: clyde.v1.AcquireSessionRequest
	(*AcquireSessionResponse)(nil),          // 3: clyde.v1.AcquireSessionResponse
	(*ReleaseSessionRequest)(nil),           // 4: clyde.v1.ReleaseSessionRequest
	(*ReleaseSessionResponse)(nil),          // 5: clyde.v1.ReleaseSessionResponse
	(*HookEventRequest)(nil),                // 6: clyde.v1.HookEventRequest
	(*HookEventResponse)(nil),               // 7: clyde.v1.HookEventResponse
	(*ListActiveSessionsRequest)(nil),       // 8: clyde.v1.ListActiveSessionsRequest
	(*ListActiveSessionsResponse)(nil),      // 9: clyde.v1.ListActiveSessionsResponse
	(*ActiveSession)(nil),                   // 10: clyde.v1.ActiveSession
	(*ListSessionsRequest)(nil),             // 11: clyde.v1.ListSessionsRequest
	(*SessionSummary)(nil),                  // 12: clyde.v1.SessionSummary
	(*ListSessionsResponse)(nil),            // 13: clyde.v1.ListSessionsResponse
	(*DetailMessage)(nil),                   // 14: clyde.v1.DetailMessage
	(*ToolUse)(nil),                         // 15: clyde.v1.ToolUse
	(*GetSessionDetailRequest)(nil),         // 16: clyde.v1.GetSessionDetailRequest
	(*GetSessionDetailResponse)(nil),        // 17: clyde.v1.GetSessionDetailResponse
	(*GetSessionExportStatsRequest)(nil),    // 18: clyde.v1.GetSessionExportStatsRequest
	(*GetSessionExportStatsResponse)(nil),   // 19: clyde.v1.GetSessionExportStatsResponse
	(*ExportSessionRequest)(nil),            // 20: clyde.v1.ExportSessionRequest
	(*ExportSessionResponse)(nil),           // 21: clyde.v1.ExportSessionResponse
	(*RenameSessionRequest)(nil),            // 22: clyde.v1.RenameSessionRequest
	(*RenameSessionResponse)(nil),           // 23: clyde.v1.RenameSessionResponse
	(*DeleteSessionRequest)(nil),            // 24: clyde.v1.DeleteSessionRequest
	(*DeleteSessionResponse)(nil),           // 25: clyde.v1.DeleteSessionResponse
	(*UpdateSessionMetadataRequest)(nil),    // 26: clyde.v1.UpdateSessionMetadataRequest
	(*UpdateSessionMetadataResponse)(nil),   // 27: clyde.v1.UpdateSessionMetadataResponse
	(*Bridge)(nil),                          // 28: clyde.v1.Bridge
	(*ProviderRuntimeBoundary)(nil),         // 29: clyde.v1.ProviderRuntimeBoundary
}
var file_clyde_v1_daemon_session_proto_depIdxs = []int32{
	10, // 0: clyde.v1.ListActiveSessionsResponse.sessions:type_name -> clyde.v1.ActiveSession
	28, // 1: clyde.v1.SessionSummary.bridge:type_name -> clyde.v1.Bridge
	29, // 2: clyde.v1.SessionSummary.runtime:type_name -> clyde.v1.ProviderRuntimeBoundary
	12, // 3: clyde.v1.ListSessionsResponse.sessions:type_name -> clyde.v1.SessionSummary
	14, // 4: clyde.v1.GetSessionDetailResponse.recent_messages:type_name -> clyde.v1.DetailMessage
	14, // 5: clyde.v1.GetSessionDetailResponse.all_messages:type_name -> clyde.v1.DetailMessage
	15, // 6: clyde.v1.GetSessionDetailResponse.tools:type_name -> clyde.v1.ToolUse
	29, // 7: clyde.v1.GetSessionDetailResponse.runtime:type_name -> clyde.v1.ProviderRuntimeBoundary
	0,  // 8: clyde.v1.ExportSessionRequest.format:type_name -> clyde.v1.SessionExportFormat
	1,  // 9: clyde.v1.ExportSessionRequest.whitespace_compression:type_name -> clyde.v1.SessionExportWhitespaceCompression
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_clyde_v1_daemon_session_proto_init() }
func file_clyde_v1_daemon_session_proto_init() {
	if File_clyde_v1_daemon_session_proto != nil {
		return
	}
	file_clyde_v1_daemon_bridge_proto_init()
	file_clyde_v1_daemon_provider_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clyde_v1_daemon_session_proto_rawDesc), len(file_clyde_v1_daemon_session_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_clyde_v1_daemon_session_proto_goTypes,
		DependencyIndexes: file_clyde_v1_daemon_session_proto_depIdxs,
		EnumInfos:         file_clyde_v1_daemon_session_proto_enumTypes,
		MessageInfos:      file_clyde_v1_daemon_session_proto_msgTypes,
	}.Build()
	File_clyde_v1_daemon_session_proto = out.File
	file_clyde_v1_daemon_session_proto_goTypes = nil
	file_clyde_v1_daemon_session_proto_depIdxs = nil
}
