// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: clyde/v1/daemon/settings.proto

package clydev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigControlType int32

const (
	ConfigControlType_CONFIG_CONTROL_TYPE_UNSPECIFIED ConfigControlType = 0
	ConfigControlType_CONFIG_CONTROL_TYPE_BOOL        ConfigControlType = 1
	ConfigControlType_CONFIG_CONTROL_TYPE_ENUM        ConfigControlType = 2
	ConfigControlType_CONFIG_CONTROL_TYPE_STRING      ConfigControlType = 3
	ConfigControlType_CONFIG_CONTROL_TYPE_PATH        ConfigControlType = 4
)

// Enum value maps for ConfigControlType.
var (
	ConfigControlType_name = map[int32]string{
		0: "CONFIG_CONTROL_TYPE_UNSPECIFIED",
		1: "CONFIG_CONTROL_TYPE_BOOL",
		2: "CONFIG_CONTROL_TYPE_ENUM",
		3: "CONFIG_CONTROL_TYPE_STRING",
		4: "CONFIG_CONTROL_TYPE_PATH",
	}
	ConfigControlType_value = map[string]int32{
		"CONFIG_CONTROL_TYPE_UNSPECIFIED": 0,
		"CONFIG_CONTROL_TYPE_BOOL":        1,
		"CONFIG_CONTROL_TYPE_ENUM":        2,
		"CONFIG_CONTROL_TYPE_STRING":      3,
		"CONFIG_CONTROL_TYPE_PATH":        4,
	}
)

func (x ConfigControlType) Enum() *ConfigControlType {
	p := new(ConfigControlType)
	*p = x
	return p
}

func (x ConfigControlType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfigControlType) Descriptor() protoreflect.EnumDescriptor {
	return file_clyde_v1_daemon_settings_proto_enumTypes[0].Descriptor()
}

func (ConfigControlType) Type() protoreflect.EnumType {
	return &file_clyde_v1_daemon_settings_proto_enumTypes[0]
}

func (x ConfigControlType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfigControlType.Descriptor instead.
func (ConfigControlType) EnumDescriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_settings_proto_rawDescGZIP(), []int{0}
}

type Settings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	EffortLevel   string                 `protobuf:"bytes,2,opt,name=effort_level,json=effortLevel,proto3" json:"effort_level,omitempty"`
	OutputStyle   string                 `protobuf:"bytes,3,opt,name=output_style,json=outputStyle,proto3" json:"output_style,omitempty"`
	RemoteControl bool                   `protobuf:"varint,4,opt,name=remote_control,json=remoteControl,proto3" json:"remote_control,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Settings) Reset() {
	*x = Settings{}
	mi := &file_clyde_v1_daemon_settings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Settings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Settings) ProtoMessage() {}

func (x *Settings) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_settings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Settings.ProtoReflect.Descriptor instead.
func (*Settings) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_settings_proto_rawDescGZIP(), []int{0}
}

func (x *Settings) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Settings) GetEffortLevel() string {
	if x != nil {
		return x.EffortLevel
	}
	return ""
}

func (x *Settings) GetOutputStyle() string {
	if x != nil {
		return x.OutputStyle
	}
	return ""
}

func (x *Settings) GetRemoteControl() bool {
	if x != nil {
		return x.RemoteControl
	}
	return false
}

type UpdateSessionSettingsRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Name     string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Settings *Settings              `protobuf:"bytes,2,opt,name=settings,proto3" json:"settings,omitempty"`
	// Field names from Settings to apply. An empty mask applies every
	// non zero field. Listing remote_control alone toggles just that
	// value without overwriting model or anything else.
	UpdateMask    []string `protobuf:"bytes,3,rep,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSessionSettingsRequest) Reset() {
	*x = UpdateSessionSettingsRequest{}
	mi := &file_clyde_v1_daemon_settings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSessionSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSessionSettingsRequest) ProtoMessage() {}

func (x *UpdateSessionSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_settings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSessionSettingsRequest.ProtoReflect.Descriptor instead.
func (*UpdateSessionSettingsRequest) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_settings_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateSessionSettingsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateSessionSettingsRequest) GetSettings() *Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *UpdateSessionSettingsRequest) GetUpdateMask() []string {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type UpdateSessionSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSessionSettingsResponse) Reset() {
	*x = UpdateSessionSettingsResponse{}
	mi := &file_clyde_v1_daemon_settings_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSessionSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSessionSettingsResponse) ProtoMessage() {}

func (x *UpdateSessionSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_settings_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSessionSettingsResponse.ProtoReflect.Descriptor instead.
func (*UpdateSessionSettingsResponse) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_settings_proto_rawDescGZIP(), []int{2}
}

type GlobalDefaults struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RemoteControl bool                   `protobuf:"varint,1,opt,name=remote_control,json=remoteControl,proto3" json:"remote_control,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalDefaults) Reset() {
	*x = GlobalDefaults{}
	mi := &file_clyde_v1_daemon_settings_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalDefaults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalDefaults) ProtoMessage() {}

func (x *GlobalDefaults) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_settings_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalDefaults.ProtoReflect.Descriptor instead.
func (*GlobalDefaults) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_settings_proto_rawDescGZIP(), []int{3}
}

func (x *GlobalDefaults) GetRemoteControl() bool {
	if x != nil {
		return x.RemoteControl
	}
	return false
}

type UpdateGlobalSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Defaults      *GlobalDefaults        `protobuf:"bytes,1,opt,name=defaults,proto3" json:"defaults,omitempty"`
	UpdateMask    []string               `protobuf:"bytes,2,rep,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGlobalSettingsRequest) Reset() {
	*x = UpdateGlobalSettingsRequest{}
	mi := &file_clyde_v1_daemon_settings_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGlobalSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGlobalSettingsRequest) ProtoMessage() {}

func (x *UpdateGlobalSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_settings_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGlobalSettingsRequest.ProtoReflect.Descriptor instead.
func (*UpdateGlobalSettingsRequest) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_settings_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateGlobalSettingsRequest) GetDefaults() *GlobalDefaults {
	if x != nil {
		return x.Defaults
	}
	return nil
}

func (x *UpdateGlobalSettingsRequest) GetUpdateMask() []string {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type UpdateGlobalSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGlobalSettingsResponse) Reset() {
	*x = UpdateGlobalSettingsResponse{}
	mi := &file_clyde_v1_daemon_settings_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGlobalSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGlobalSettingsResponse) ProtoMessage() {}

func (x *UpdateGlobalSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_settings_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGlobalSettingsResponse.ProtoReflect.Descriptor instead.
func (*UpdateGlobalSettingsResponse) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_settings_proto_rawDescGZIP(), []int{5}
}

type ConfigControlOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigControlOption) Reset() {
	*x = ConfigControlOption{}
	mi := &file_clyde_v1_daemon_settings_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigControlOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigControlOption) ProtoMessage() {}

func (x *ConfigControlOption) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_settings_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigControlOption.ProtoReflect.Descriptor instead.
func (*ConfigControlOption) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_settings_proto_rawDescGZIP(), []int{6}
}

func (x *ConfigControlOption) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ConfigControlOption) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ConfigControlOption) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ConfigControl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Section       string                 `protobuf:"bytes,2,opt,name=section,proto3" json:"section,omitempty"`
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Type          ConfigControlType      `protobuf:"varint,5,opt,name=type,proto3,enum=clyde.v1.ConfigControlType" json:"type,omitempty"`
	Value         string                 `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`
	DefaultValue  string                 `protobuf:"bytes,7,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	Options       []*ConfigControlOption `protobuf:"bytes,8,rep,name=options,proto3" json:"options,omitempty"`
	Sensitive     bool                   `protobuf:"varint,9,opt,name=sensitive,proto3" json:"sensitive,omitempty"`
	ReadOnly      bool                   `protobuf:"varint,10,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigControl) Reset() {
	*x = ConfigControl{}
	mi := &file_clyde_v1_daemon_settings_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigControl) ProtoMessage() {}

func (x *ConfigControl) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_settings_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigControl.ProtoReflect.Descriptor instead.
func (*ConfigControl) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_settings_proto_rawDescGZIP(), []int{7}
}

func (x *ConfigControl) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConfigControl) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

func (x *ConfigControl) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ConfigControl) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ConfigControl) GetType() ConfigControlType {
	if x != nil {
		return x.Type
	}
	return ConfigControlType_CONFIG_CONTROL_TYPE_UNSPECIFIED
}

func (x *ConfigControl) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ConfigControl) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *ConfigControl) GetOptions() []*ConfigControlOption {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *ConfigControl) GetSensitive() bool {
	if x != nil {
		return x.Sensitive
	}
	return false
}

func (x *ConfigControl) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

type ListConfigControlsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConfigControlsRequest) Reset() {
	*x = ListConfigControlsRequest{}
	mi := &file_clyde_v1_daemon_settings_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfigControlsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfigControlsRequest) ProtoMessage() {}

func (x *ListConfigControlsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_settings_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfigControlsRequest.ProtoReflect.Descriptor instead.
func (*ListConfigControlsRequest) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_settings_proto_rawDescGZIP(), []int{8}
}

type ListConfigControlsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Controls      []*ConfigControl       `protobuf:"bytes,1,rep,name=controls,proto3" json:"controls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConfigControlsResponse) Reset() {
	*x = ListConfigControlsResponse{}
	mi := &file_clyde_v1_daemon_settings_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfigControlsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfigControlsResponse) ProtoMessage() {}

func (x *ListConfigControlsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_settings_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfigControlsResponse.ProtoReflect.Descriptor instead.
func (*ListConfigControlsResponse) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_settings_proto_rawDescGZIP(), []int{9}
}

func (x *ListConfigControlsResponse) GetControls() []*ConfigControl {
	if x != nil {
		return x.Controls
	}
	return nil
}

type UpdateConfigControlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigControlRequest) Reset() {
	*x = UpdateConfigControlRequest{}
	mi := &file_clyde_v1_daemon_settings_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigControlRequest) ProtoMessage() {}

func (x *UpdateConfigControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_settings_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigControlRequest.ProtoReflect.Descriptor instead.
func (*UpdateConfigControlRequest) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_settings_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateConfigControlRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UpdateConfigControlRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type UpdateConfigControlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Control       *ConfigControl         `protobuf:"bytes,1,opt,name=control,proto3" json:"control,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigControlResponse) Reset() {
	*x = UpdateConfigControlResponse{}
	mi := &file_clyde_v1_daemon_settings_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigControlResponse) ProtoMessage() {}

func (x *UpdateConfigControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clyde_v1_daemon_settings_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigControlResponse.ProtoReflect.Descriptor instead.
func (*UpdateConfigControlResponse) Descriptor() ([]byte, []int) {
	return file_clyde_v1_daemon_settings_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateConfigControlResponse) GetControl() *ConfigControl {
	if x != nil {
		return x.Control
	}
	return nil
}

var File_clyde_v1_daemon_settings_proto protoreflect.FileDescriptor

const file_clyde_v1_daemon_settings_proto_rawDesc = "" +
	"\n" +
	"\x1eclyde/v1/daemon/settings.proto\x12\bclyde.v1\"\xa3\x01\n" +
	"\bSettings\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12!\n" +
	"\feffort_level\x18\x02 \x01(\tR\veffortLevel\x12!\n" +
	"\foutput_style\x18\x03 \x01(\tR\voutputStyle\x12%\n" +
	"\x0eremote_control\x18\x04 \x01(\bR\rremoteControlJ\x04\b\x05\x10\x06R\x0econtext_window\"\x83\x01\n" +
	"\x1cUpdateSessionSettingsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12.\n" +
	"\bsettings\x18\x02 \x01(\v2\x12.clyde.v1.SettingsR\bsettings\x12\x1f\n" +
	"\vupdate_mask\x18\x03 \x03(\tR\n" +
	"updateMask\"\x1f\n" +
	"\x1dUpdateSessionSettingsResponse\"7\n" +
	"\x0eGlobalDefaults\x12%\n" +
	"\x0eremote_control\x18\x01 \x01(\bR\rremoteControl\"t\n" +
	"\x1bUpdateGlobalSettingsRequest\x124\n" +
	"\bdefaults\x18\x01 \x01(\v2\x18.clyde.v1.GlobalDefaultsR\bdefaults\x12\x1f\n" +
	"\vupdate_mask\x18\x02 \x03(\tR\n" +
	"updateMask\"\x1e\n" +
	"\x1cUpdateGlobalSettingsResponse\"c\n" +
	"\x13ConfigControlOption\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\xd3\x02\n" +
	"\rConfigControl\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x18\n" +
	"\asection\x18\x02 \x01(\tR\asection\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12/\n" +
	"\x04type\x18\x05 \x01(\x0e2\x1b.clyde.v1.ConfigControlTypeR\x04type\x12\x14\n" +
	"\x05value\x18\x06 \x01(\tR\x05value\x12#\n" +
	"\rdefault_value\x18\a \x01(\tR\fdefaultValue\x127\n" +
	"\aoptions\x18\b \x03(\v2\x1d.clyde.v1.ConfigControlOptionR\aoptions\x12\x1c\n" +
	"\tsensitive\x18\t \x01(\bR\tsensitive\x12\x1b\n" +
	"\tread_only\x18\n" +
	" \x01(\bR\breadOnly\"\x1b\n" +
	"\x19ListConfigControlsRequest\"Q\n" +
	"\x1aListConfigControlsResponse\x123\n" +
	"\bcontrols\x18\x01 \x03(\v2\x17.clyde.v1.ConfigControlR\bcontrols\"D\n" +
	"\x1aUpdateConfigControlRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"P\n" +
	"\x1bUpdateConfigControlResponse\x121\n" +
	"\acontrol\x18\x01 \x01(\v2\x17.clyde.v1.ConfigControlR\acontrol*\xb2\x01\n" +
	"\x11ConfigControlType\x12#\n" +
	"\x1fCONFIG_CONTROL_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18CONFIG_CONTROL_TYPE_BOOL\x10\x01\x12\x1c\n" +
	"\x18CONFIG_CONTROL_TYPE_ENUM\x10\x02\x12\x1e\n" +
	"\x1aCONFIG_CONTROL_TYPE_STRING\x10\x03\x12\x1c\n" +
	"\x18CONFIG_CONTROL_TYPE_PATH\x10\x04B(Z&goodkind.io/clyde/api/clyde/v1;clydev1b\x06proto3"

var (
	file_clyde_v1_daemon_settings_proto_rawDescOnce sync.Once
	file_clyde_v1_daemon_settings_proto_rawDescData []byte
)

func file_clyde_v1_daemon_settings_proto_rawDescGZIP() []byte {
	file_clyde_v1_daemon_settings_proto_rawDescOnce.Do(func() {
		file_clyde_v1_daemon_settings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clyde_v1_daemon_settings_proto_rawDesc), len(file_clyde_v1_daemon_settings_proto_rawDesc)))
	})
	return file_clyde_v1_daemon_settings_proto_rawDescData
}

var file_clyde_v1_daemon_settings_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_clyde_v1_daemon_settings_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_clyde_v1_daemon_settings_proto_goTypes = []any{
	(ConfigControlType)(0),                // 0: clyde.v1.ConfigControlType
	(*Settings)(nil),                      // 1: clyde.v1.Settings
	(*UpdateSessionSettingsRequest)(nil),  // 2: clyde.v1.UpdateSessionSettingsRequest
	(*UpdateSessionSettingsResponse)(nil), // 3: clyde.v1.UpdateSessionSettingsResponse
	(*GlobalDefaults)(nil),                // 4: clyde.v1.GlobalDefaults
	(*UpdateGlobalSettingsRequest)(nil),   // 5: clyde.v1.UpdateGlobalSettingsRequest
	(*UpdateGlobalSettingsResponse)(nil),  // 6: clyde.v1.UpdateGlobalSettingsResponse
	(*ConfigControlOption)(nil),           // 7: clyde.v1.ConfigControlOption
	(*ConfigControl)(nil),                 // 8: clyde.v1.ConfigControl
	(*ListConfigControlsRequest)(nil),     // 9: clyde.v1.ListConfigControlsRequest
	(*ListConfigControlsResponse)(nil),    // 10: clyde.v1.ListConfigControlsResponse
	(*UpdateConfigControlRequest)(nil),    // 11: clyde.v1.UpdateConfigControlRequest
	(*UpdateConfigControlResponse)(nil),   // 12: clyde.v1.UpdateConfigControlResponse
}
var file_clyde_v1_daemon_settings_proto_depIdxs = []int32{
	1, // 0: clyde.v1.UpdateSessionSettingsRequest.settings:type_name -> clyde.v1.Settings
	4, // 1: clyde.v1.UpdateGlobalSettingsRequest.defaults:type_name -> clyde.v1.GlobalDefaults
	0, // 2: clyde.v1.ConfigControl.type:type_name -> clyde.v1.ConfigControlType
	7, // 3: clyde.v1.ConfigControl.options:type_name -> clyde.v1.ConfigControlOption
	8, // 4: clyde.v1.ListConfigControlsResponse.controls:type_name -> clyde.v1.ConfigControl
	8, // 5: clyde.v1.UpdateConfigControlResponse.control:type_name -> clyde.v1.ConfigControl
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_clyde_v1_daemon_settings_proto_init() }
func file_clyde_v1_daemon_settings_proto_init() {
	if File_clyde_v1_daemon_settings_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clyde_v1_daemon_settings_proto_rawDesc), len(file_clyde_v1_daemon_settings_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_clyde_v1_daemon_settings_proto_goTypes,
		DependencyIndexes: file_clyde_v1_daemon_settings_proto_depIdxs,
		EnumInfos:         file_clyde_v1_daemon_settings_proto_enumTypes,
		MessageInfos:      file_clyde_v1_daemon_settings_proto_msgTypes,
	}.Build()
	File_clyde_v1_daemon_settings_proto = out.File
	file_clyde_v1_daemon_settings_proto_goTypes = nil
	file_clyde_v1_daemon_settings_proto_depIdxs = nil
}
