package sessionrename

import (
	"context"
	"fmt"
	"log/slog"
	"time"

	"goodkind.io/clyde/internal/config"
	"goodkind.io/clyde/internal/session"
	"goodkind.io/clyde/internal/slogger"
)

type decision struct {
	Code       decisionCode
	OldName    string
	NewName    string
	Source     sourceKind
	SourceHash string
	Reason     string
	Skipped    bool
	Applied    bool
	ApplyError error
	ProposedAt time.Time
}

type decisionCode string

const (
	decisionDisabled        decisionCode = "disabled"
	decisionUserRenamed     decisionCode = "user_renamed"
	decisionNotDefaultShape decisionCode = "not_default_shape"
	decisionLiveLeaseHeld   decisionCode = "live_lease_held"
	decisionTooFewMessages  decisionCode = "too_few_messages"
	decisionCooldown        decisionCode = "cooldown"
	decisionRateLimited     decisionCode = "rate_limited"
	decisionSourceUnchanged decisionCode = "source_unchanged"
	decisionNoSource        decisionCode = "no_source"
	decisionRejected        decisionCode = "candidate_rejected"
	decisionApplied         decisionCode = "applied"
	decisionApplyFailed     decisionCode = "apply_failed"
)

// Renamer applies an auto-generated rename through the daemon rename funnel.
type Renamer interface {
	ApplyAutoRename(ctx context.Context, oldName, newName, sourceHash string) error
}

// LiveLeases reports whether a session currently holds a live wrapper or lease.
type LiveLeases interface {
	HasLiveLease(sessionName string) bool
}

// Sessions lists the persisted registry rows the worker uses for collision checks.
type Sessions interface {
	List() ([]*session.Session, error)
}

// Worker evaluates transcript-derived auto-name candidates for one session.
type Worker struct {
	cfg     config.AutoNameConfig
	renamer Renamer
	leases  LiveLeases
	store   Sessions
	limiter *rateLimiter
	log     *slog.Logger
	now     func() time.Time
}

// NewWorker builds a daemon auto-name worker with the supplied dependencies.
func NewWorker(cfg config.AutoNameConfig, renamer Renamer, leases LiveLeases, store Sessions, log *slog.Logger, nowFn func() time.Time) *Worker {
	if nowFn == nil {
		nowFn = time.Now
	}
	if log == nil {
		log = slog.Default()
	}
	return &Worker{
		cfg:     cfg,
		renamer: renamer,
		leases:  leases,
		store:   store,
		limiter: newRateLimiter(effectiveMaxCallsPerHour(cfg), nowFn),
		log:     log,
		now:     nowFn,
	}
}

// Evaluate inspects one session and either applies a rename or reports why it skipped it.
func (w *Worker) Evaluate(ctx context.Context, sess *session.Session) decision {
	if out, stop := w.preflightDecision(sess); stop {
		return out
	}
	src, out, ok := w.sourceDecision(sess)
	if !ok {
		return out
	}
	candidate, out, ok := w.candidateDecision(ctx, sess, src)
	if !ok {
		return out
	}
	return w.applyDecision(ctx, sess, src, candidate)
}

func (w *Worker) preflightDecision(sess *session.Session) (decision, bool) {
	if sess == nil {
		out := newDecision()
		out.Code = decisionNoSource
		out.Reason = "nil_session"
		out.Skipped = true
		return out, true
	}
	if !w.cfg.IsEnabled() {
		out := newDecision()
		out.Code = decisionDisabled
		out.OldName = sess.Name
		out.Skipped = true
		return out, true
	}
	if sess.Metadata.AutoNameSource == session.AutoNameSourceUser || sess.Metadata.AutoNameState == session.AutoNameStateUserLocked {
		out := newDecision()
		out.Code = decisionUserRenamed
		out.OldName = sess.Name
		out.Skipped = true
		return out, true
	}
	if !session.IsAutoGeneratedName(sess.Name) && sess.Metadata.AutoNameState != session.AutoNameStateApplied {
		out := newDecision()
		out.Code = decisionNotDefaultShape
		out.OldName = sess.Name
		out.Skipped = true
		return out, true
	}
	if w.leases != nil && w.leases.HasLiveLease(sess.Name) {
		out := newDecision()
		out.Code = decisionLiveLeaseHeld
		out.OldName = sess.Name
		out.Skipped = true
		return out, true
	}

	cooldown := w.cfg.Cooldown.Duration()
	if cooldown <= 0 {
		cooldown = 30 * time.Minute
	}
	if !sess.Metadata.LastAutoNameAt.IsZero() && w.now().Before(sess.Metadata.LastAutoNameAt.Add(cooldown)) {
		out := newDecision()
		out.Code = decisionCooldown
		out.OldName = sess.Name
		out.Skipped = true
		return out, true
	}
	return newDecision(), false
}

func (w *Worker) sourceDecision(sess *session.Session) (candidateSource, decision, bool) {
	src, err := extractFromSession(sess)
	if err != nil {
		out := newDecision()
		out.Code = decisionNoSource
		out.OldName = sess.Name
		out.Reason = err.Error()
		out.Skipped = true
		return newCandidateSource(), out, false
	}
	minMessages := w.cfg.MinUserMessages
	if minMessages <= 0 {
		minMessages = 3
	}
	if src.Kind == sourceFirstUserMessage && src.UserMsgCount < minMessages {
		out := newDecision()
		out.Code = decisionTooFewMessages
		out.OldName = sess.Name
		out.Source = src.Kind
		out.Skipped = true
		return newCandidateSource(), out, false
	}
	if sess.Metadata.AutoNameSourceHash != "" && sess.Metadata.AutoNameSourceHash == src.Hash {
		out := newDecision()
		out.Code = decisionSourceUnchanged
		out.OldName = sess.Name
		out.Source = src.Kind
		out.SourceHash = src.Hash
		out.Skipped = true
		return newCandidateSource(), out, false
	}
	return src, newDecision(), true
}

func (w *Worker) candidateDecision(ctx context.Context, sess *session.Session, src candidateSource) (candidateName, decision, bool) {
	taken, takenErr := w.takenNames(sess.Name)
	if takenErr != nil {
		w.log.WarnContext(ctx, "daemon.autoname.taken_lookup_failed",
			"component", "daemon",
			"subcomponent", "autoname",
			"session", sess.Name,
			"err", takenErr,
		)
		taken = map[string]bool{}
	}

	candidate, proposeErr := propose(src, taken)
	if proposeErr != nil {
		out := newDecision()
		out.Code = decisionRejected
		out.OldName = sess.Name
		out.Source = src.Kind
		out.Reason = candidate.Reason
		out.Skipped = true
		return newCandidateName("", ""), out, false
	}
	if candidate.Name == sess.Name {
		out := newDecision()
		out.Code = decisionSourceUnchanged
		out.OldName = sess.Name
		out.NewName = candidate.Name
		out.Source = src.Kind
		out.SourceHash = src.Hash
		out.Skipped = true
		return newCandidateName("", ""), out, false
	}
	if !w.limiter.allow() {
		out := newDecision()
		out.Code = decisionRateLimited
		out.OldName = sess.Name
		out.Source = src.Kind
		out.Skipped = true
		return newCandidateName("", ""), out, false
	}
	return candidate, newDecision(), true
}

func (w *Worker) applyDecision(ctx context.Context, sess *session.Session, src candidateSource, candidate candidateName) decision {
	if err := w.renamer.ApplyAutoRename(ctx, sess.Name, candidate.Name, src.Hash); err != nil {
		w.log.WarnContext(ctx, "daemon.autoname.apply_failed",
			"component", "daemon",
			"subcomponent", "autoname",
			"old_name", sess.Name,
			"new_name", candidate.Name,
			"source", string(src.Kind),
			"err", err,
		)
		out := newDecision()
		out.Code = decisionApplyFailed
		out.OldName = sess.Name
		out.NewName = candidate.Name
		out.Source = src.Kind
		out.SourceHash = src.Hash
		out.ApplyError = err
		return out
	}
	w.log.LogAttrs(ctx, slog.LevelInfo, "daemon.autoname.applied",
		slog.String("component", "daemon"),
		slog.String("subcomponent", "autoname"),
		slog.String("old_name", sess.Name),
		slog.String("new_name", candidate.Name),
		slog.String("source", string(src.Kind)),
		slog.String("source_hash", src.Hash),
	)
	out := newDecision()
	out.Code = decisionApplied
	out.OldName = sess.Name
	out.NewName = candidate.Name
	out.Source = src.Kind
	out.SourceHash = src.Hash
	out.Applied = true
	out.ProposedAt = w.now()
	return out
}

func (w *Worker) takenNames(self string) (map[string]bool, error) {
	if w.store == nil {
		return map[string]bool{}, nil
	}
	all, err := w.store.List()
	if err != nil {
		slog.Warn("sessionrename.taken_names_list_failed",
			"component", "daemon",
			"subcomponent", "autoname",
			"concern", slogger.ConcernDaemonWorkersPrune,
			"err", err,
		)
		return nil, fmt.Errorf("list sessions: %w", err)
	}
	taken := make(map[string]bool, len(all))
	for _, sess := range all {
		if sess == nil || sess.Name == self {
			continue
		}
		taken[sess.Name] = true
	}
	return taken, nil
}

func effectiveMaxCallsPerHour(cfg config.AutoNameConfig) int {
	if cfg.MaxCallsPerHour <= 0 {
		return 6
	}
	return cfg.MaxCallsPerHour
}

func newDecision() decision {
	return decision{
		Code:       "",
		OldName:    "",
		NewName:    "",
		Source:     "",
		SourceHash: "",
		Reason:     "",
		Skipped:    false,
		Applied:    false,
		ApplyError: nil,
		ProposedAt: time.Time{},
	}
}

func newCandidateSource() candidateSource {
	return candidateSource{
		Kind:          "",
		Text:          "",
		Hash:          "",
		UserMsgCount:  0,
		HasFirstUser:  false,
		FirstUserTime: time.Time{},
	}
}
