package daemon

import (
	"context"
	"fmt"
	"log/slog"

	"goodkind.io/clyde/internal/config"
	"goodkind.io/clyde/internal/session"
	"goodkind.io/clyde/internal/sessionrename"
)

type autoNameWorker struct {
	worker *sessionrename.Worker
	cfg    config.AutoNameConfig
}

func (s *Server) configureAutoName(cfg config.AutoNameConfig) {
	s.autoNameMu.Lock()
	defer s.autoNameMu.Unlock()
	if !cfg.IsEnabled() {
		s.autoName = nil
		return
	}
	s.autoName = &autoNameWorker{
		cfg:    cfg,
		worker: sessionrename.NewWorker(cfg, s, s, autoNameStoreAdapter{log: s.log}, s.log, nil),
	}
}

type autoNameStoreAdapter struct {
	log *slog.Logger
}

func (autoNameStoreAdapter) List() ([]*session.Session, error) {
	store, err := session.NewGlobalFileStore()
	if err != nil {
		slog.Warn("daemon.autoname.store_adapter_init_failed", "component", "daemon", "subcomponent", "autoname", "err", err)
		return nil, fmt.Errorf("new global file store: %w", err)
	}
	all, err := store.List()
	if err != nil {
		slog.Warn("daemon.autoname.store_adapter_list_failed", "component", "daemon", "subcomponent", "autoname", "err", err)
		return nil, fmt.Errorf("list sessions: %w", err)
	}
	return all, nil
}

func (s *Server) runAutoRenamePass(ctx context.Context) {
	s.autoNameMu.RLock()
	wired := s.autoName
	s.autoNameMu.RUnlock()

	store, err := session.NewGlobalFileStore()
	if err != nil {
		s.log.WarnContext(ctx, "daemon.autoname.store_init_failed",
			"component", "daemon",
			"subcomponent", "autoname",
			"err", err,
		)
		return
	}
	all, err := store.List()
	if err != nil {
		s.log.WarnContext(ctx, "daemon.autoname.list_failed",
			"component", "daemon",
			"subcomponent", "autoname",
			"err", err,
		)
		return
	}
	for _, sess := range all {
		if sess == nil {
			continue
		}
		if backfilled := s.backfillUserLockedIfNeeded(ctx, store, sess); backfilled {
			continue
		}
		if wired == nil {
			continue
		}
		_ = wired.worker.Evaluate(ctx, sess)
	}
}

func (s *Server) backfillUserLockedIfNeeded(ctx context.Context, store *session.FileStore, sess *session.Session) bool {
	if sess.Metadata.AutoNameState == session.AutoNameStateApplied ||
		sess.Metadata.AutoNameState == session.AutoNameStateUserLocked ||
		sess.Metadata.AutoNameSource == session.AutoNameSourceUser {
		return false
	}
	if session.IsAutoGeneratedName(sess.Name) {
		return false
	}
	sess.Metadata.AutoNameState = session.AutoNameStateUserLocked
	sess.Metadata.AutoNameSource = session.AutoNameSourceUser
	if err := store.Update(sess); err != nil {
		s.log.WarnContext(ctx, "daemon.autoname.backfill_user_locked_failed",
			"component", "daemon",
			"subcomponent", "autoname",
			"session", sess.Name,
			"err", err,
		)
		return false
	}
	s.log.LogAttrs(ctx, slog.LevelInfo, "daemon.autoname.backfilled_user_locked",
		slog.String("component", "daemon"),
		slog.String("subcomponent", "autoname"),
		slog.String("session", sess.Name),
	)
	return true
}
